### ISSUE TITLE
callback before render

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#112]
I'm trying to do something whenever the calendar changes (view, date, new events). There is no callback for this. viewDisplay() works only when changing view or date. Not when refetching events (changing to another person calendar in my app). I could use eventAfterAllRender() but I want my code to trigger before fetching events and rendering. Also loading() only triggers when it actually needs to fetch new data, so not when a view is changed. What are your thoughts on:

1) viewDisplay() should be triggered on refetchEvents()
2) introduce new callback which is triggered before rendering. beforeRender()

**Comment by apeace** [comment]
Hi there!

I know this is an old issue, but it sounds like what I need as well.

My goal is to block off certain dates on the calendar. The issue is that these dates need to be fetched _asynchronously_. So the existing `viewRender` doesn't work for me.

Before `dayRender` is called, I need to fetch the blocked-off dates from the backend, based on the new date range the user is looking at.

Right now, my only workaround is to load _all_ of my blocked off dates, for all time, before initializing `fullCalendar()`.
