### ISSUE TITLE
NuGet package official process

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#1225]
Originally reported on Google Code with ID 956

```
Hi

I think it would be great if NuGet could be available as a NuGet (http://nuget.org/)
Package for the .NET environment.

Its a simple feature and would make it even easier to get up and running, and a common
way og populating the component to .NET

I think it is a great component so why not share it on Nuget :).

Best regards 
Rasmus


```

Reported by `rasmus.christensen` on 2011-05-16 19:56:48

Imported with **3** stars.

**Comment by jansokoly** [comment]
At the moment, there's [jQuery.Fullcalendar](https://www.nuget.org/packages/jQuery.Fullcalendar/).
The problem with that NuGet package in my opinion is, that it includes FullCalendar Google Calendar Plugin, which requires gcal.js, jQuery UI and cupertino theme. That's probably not required by most of projects.
Because of that, I would create 3 separate NuGet packages:
- FullCalendar.Core  
  - including fullcalendar.js, fullcalendar.min.js, fullcalendar.css, fullcalendar.min.css, fullcalendar.print.css, fullcalendar.print.min.css (currently missing), locale-all.js, locale-all.min.js (currently missing) and /locale/*.js  
  - with jQuery and Moment.js as Dependencies
- FullCalendar.GoogleCalendarPlugin  
  - including gcal.js  
  - with FullCalendar.Core and jQuery UI as Dependencies

**Comment by arshaw** [comment]
I can't really imagine many people using NuGet. I bet .net developers have somehow found a convenient way to use NPM. I'm closing this issue, but if someone expresses interest ing FullCalendar NuGet support, I'll reopen
