### ISSUE TITLE
Show agenda axis on right side also

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2121]
Originally reported on Google Code with ID 1854

```
Hello,

First of all I thank you for such a great plugin. I have implement fullcalendar and
it's very easy to use and implement.

My requirement is, I require timeline at both side also in agenda week view. I tried
to show it at right side by customizing fullcalendar.js, and it works fine. But while
rendering events there is an issue with designing regarding events postition. 

So I want your help, It will be great if you provide and extra configuration to show
time line (agenda axis) on right side also.

Thanks in advance :).

I am waiting for your positive reply.


With regards,
Chintan Mirani


```

Reported by `chintanm.virtueinfo` on 2013-06-02 19:46:27

**Comment by karthikcrmr** [comment]
HI Arshaw 
I find that function but i did not get it that... where is that file name.. or can you send reference for this axis change in jsfiddle with examples

**Comment by shawe** [comment]
@arshaw if ower customers wants this features, is enough reason for do it, maybe not to include it on the main project, but finally the customers is who say what they need/want, and in my case, this is a required feature by my customer (also including the time on every cell, do it with fc-bgevents on my case with a little code on eventAfterAllRender for re-apply on every day change). It's a "workarround" but complains with needs of my customer.

For me seems to be really unnedded, but speaking with the customer results with a more agile in every-day work for easy to find the correct relation time/column, in this case using FullCalendar Scheduler with multi-colum day.

**Comment by Krzysiek555** [comment]
> i don't understand the need for a time axis on BOTH sides. (thus closing, until someone can communicate the rationale)

@arshaw actually the reason is very simple, if you would have very long TimeGrid (for example week view with multiple resources) and then scroll to the last day of the week you do not see the time axis anymore. It would be very convenient if there was an option to include it on both sides of the calendar.

Also it would be very convenient if time axis could be "repeated" somehow between days/resources or if time labels could be displayed in cells directly (without creating events).

Just like @shawe mentioned I also use background events to "imitate" the time axis, but that's just a hacky workaround. :)

**Comment by arshaw** [comment]
we are actually using this other ticket to track demand:
https://github.com/fullcalendar/fullcalendar/issues/3321
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
