### ISSUE TITLE
AllDay slot returns date as UTC even when using timezone:local

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2477]
Originally reported on Google Code with ID 2212

```
I am not sure if this is a bug but when using "timezone:local" the "select" and "dayClick"
callback return the start date as UTC if I click on the allDay slot. If I click on
a normal slot, it returns the start date as local time. Should not the daySlot return
the date on the same timezone?

This behavior is visible here: http://jsfiddle.net/xZuT3/1/


leo
```

Reported by `ateista` on 2014-07-22 20:02:53

**Comment by jessedvrs** [comment]
@arshaw
Just wondering: how is an allDay-event ambiguously timed? The time being 00:00 till 23:59 doesn't mean the time doesn't matter. It still does, since 00:00-23:59 in timezone A is still different in timezone B. In my opinion, allDay events are only allDay events because they're timed 00:00-23:59 within the current timezone. Not because they have an 'allDay'-flag.

**Real world example:**
I am in Amsterdam. In an availability-calendar, I want to create an all day-event. So, what I'm actually saying, is: I am available on `July 11th 2017 from 0:00:00 until 23:59:59` (time in Amsterdam).
Another person, living in London, wants to check my availability. On his screen, the website will show my availability as `July 11th 2017 from 0:00:00 until 23:59:59` too!!! This is **incorrect**. This should be from `July 10th 2017 at 22:00:00` until `July 11th 2017 at 21:59:59`, because it should be converted to his timezone. From his eyes, my event should not be visible in the allDay-bar, but as a timed event.

To fix this, we should get rid of the `allDay` flag entirely (when communicating with events). It's allDay when `start` is timed 00:00:00 and `end` is timed 23:59:50 (based on times).

**Comment by arshaw** [comment]
i'm moving your discussion to this ticket https://github.com/fullcalendar/fullcalendar/issues/2981
which is serving as a dumping ground for all timezone and ambig moment related gripes.
