### ISSUE TITLE
Overlapping inverse background events with the same ID are highlighting areas that are covered

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2651]
Originally reported on Google Code with ID 2386

```
Reproduction here: http://codepen.io/anon/pen/qEOYrR

Notice that the inverse background is highlighting after 5pm even though the Midnight-Midnight
background event is covering that area.
```

Reported by `titosrevenge` on 2014-12-03 00:25:21

Imported with **3** stars.

**Comment by BethelBoy** [comment]
Hi @arshaw, I'm currently trying to put the availabilities of individuals on the scheduler view, and use the inverse-background render for those with overlap:false so that way you can only drag/drop events onto the open areas which would be when they are available. I have come across this same issue, but appears your patch is labeled issue-2386, and this issue is 2651. I wanted to make sure this was the correct patch for the inverse-background issue.

Thanks,

Nathan

**Comment by arshaw** [comment]
this is because the [issue on google code](https://code.google.com/p/fullcalendar/issues/detail?id=2386) was numbered 2386. other than that, should be no confusion

**Comment by tzyhhaur** [comment]
Hi arshaw, it seems that this patch has not yet been fixed in the latest release. I am having trouble to patch the file above to the main branch and build it. How can I go about it? Or is there a built version of the js/css applying this patch? 

Thank you.

**Comment by arshaw** [comment]
myself or someone else would need to adapt that patch to the latest codebase, which is quite different than when the patch was originally written.

**Comment by arshaw** [comment]
i adapted the repro to v5: https://codepen.io/arshaw/pen/eYJWyRV?editable=true&editors=001

the one inverse bg event was a super-range of the other, forcing it to appear as if it weren't rendered
