### ISSUE TITLE
Customize position of eventLimit popover

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2743]
Originally reported on Google Code with ID 2478
```
I would like the ability to style and orient the placement of a eventLimitClick popover.

```

Reported by `chuckdawit` on 2015-04-01 20:22:17

Imported with **1** stars.

**Comment by arshaw** [comment]
possible to implement your own custom popover for this:
http://fullcalendar.io/docs/display/eventLimitClick/
cumbersome, but provides unlimited flexibility.

if there's demand for a setting to conveniently adjust positioning/sizing of the existing popover, i'd be open to it. would really like to see screenshots of proposed configurations tho

**Comment by negberts** [comment]
@arshaw I would be happy to have a setting where the popover can be positioned statically or at least be completely visible directly.

We have 12 events as limit:

![image](https://user-images.githubusercontent.com/20299260/84365407-aef49300-abd1-11ea-8e09-e4ea301a5642.png)

But when the popover opens the top of the popover is probably centered somewhere near item 6 instead of being completely visible

![image](https://user-images.githubusercontent.com/20299260/84365500-d8adba00-abd1-11ea-805d-dcf6f8b3d1b7.png)

The top position is rendered as something like -122px
