### ISSUE TITLE
header value as false, calendar doesn't render

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2801]
Originally reported on Google Code with ID 2536
```
The documentation specifies that you can set "header" to false. But setting it with
the Boolean value false, it makes the calendar not render at all.

Yet, setting "allDaySlot" to Boolean false creates no error. This feels inconsistent.
```

Reported by `chrisaga.dev` on 2015-07-01 17:45:33

Imported with **1** stars.

**Comment by abenchi** [comment]
Hello,
We have the same problem where the calendar is not rendered when the header is set to ```false```. By searching inside the code, I have found the problem, which is caused by the following function:
```
function elementVisible() {
		return element.is(':visible');
	}
```
This function returns true when the element has height/width. By adding a header, the element will have these metrics thanks to the buttons added to the the header.
However, when the header is set to false, there is no added button which means ```height = width = 0```, and so the calendar will not be rendered.
One of the possible solutions is to use another selector (i.e., other than ```:visible```) where the calendar could be rendered when the element does exist. What do you think about this solution? Do you have another solution?
Thanks a lot.

**Comment by JobaDiniz** [comment]
+1

**Comment by arshaw** [comment]
can someone post a jsbin recreation? http://fullcalendar.io/wiki/Reporting-Bugs/

here is my barebones example with `header:false` and it works great: http://jsbin.com/reneqamexo/1/edit?js,output

**Comment by zlorkovic** [comment]
The same here. Although, it doesn't render on Chrome and Firefox, but it does on Safari.

**Comment by mennova** [comment]
Reproduced in a google chrome app.  

JS Code:
  var calendar = $('#calendar').fullCalendar({
    height: $(window).height()-52,
    header: false,
    defaultView: 'agendaWeek',
  });

If my element is this, it doesn't show a calendar:
<div id="calendar"></div>
http://jsbin.com/vezaruhole/edit?html,js,output

If I populate at least something in the div, it works:
<div id="calendar">calendar placeholder</div>
http://jsbin.com/doqefafoqu/edit?html,js,output

Seems that if the calendar element is not initially visible, when there is no header, it ends up not displaying anything.  probably back to @abenchi comment.

**Comment by mennova** [comment]
FWIW - I'm using bootstrap's header at the top of the application.  My calendar div had a "float: left" style attached to it (worked with fullcalendar v1, not sure why I still have it?), and it seems to be causing the positioning issue, where it appears behind the header, and probably is not flagged as "visible".

**Comment by arshaw** [comment]
this has less to do with the `header` option and more to do with how absolute positioning works. In [your example](http://jsbin.com/vezaruhole/edit?html,js,output) you have `position:absolute` which essentially shrinks the div down to zero-width. FullCalendar needs a width in order to render. I made a new JSBin showing how things now work with a hardcoded width: http://jsbin.com/fecububula/1/edit?html,output

the reason this behavior doesn't emerge when there's a header is that the header has buttons and such that guarantee a natural width, albeit pretty squished.
