### ISSUE TITLE
selectHelper function doesn't work

### ISSUE THREAD

**Issue by UziTech** [fullcalendar/fullcalendar#2832]
In the documentation selectHelper accepts a function which returns a DOM element. 

The function never gets called and it acts the same as setting selectHelper to true

**Comment by arshaw** [comment]
this was definitely working at some point. it would be infinitely helpful if you could post a JSBin demo. instructions here: http://fullcalendar.io/wiki/Reporting-Bugs/

will reopen when you do. thanks so much!

**Comment by UziTech** [comment]
http://output.jsbin.com/xixuvulaqi/

The calendar on the left uses a selectHelper function that returns a div with a red background.

The calendar on the right set selectHelper to true.

The result is the same. A div with a blueish background.

**Comment by UziTech** [comment]
jsbin link stopped working. Here is a jsfiddle link

https://jsfiddle.net/UziTech/zyxjs9bp/

**Comment by arshaw** [comment]
i made a JSBin because the rawgit in your jsfiddle stopped working: http://jsbin.com/raboqadusa/1/edit?js,output

i can reproduce. thank you for the report.

**Comment by Chris136** [comment]
The code-block containing "isFunction" for selectHelper was removed in 2.1.0.
In 2.0.3 it was still present.

**Comment by arshaw** [comment]
I'm now remembering I *intentionally* removed the function signature for `selectHelper`. I will update the [docs](https://fullcalendar.io/docs/selection/selectHelper/) to reflect.

For v2.0.3 and prior, the select-helper was only ever a single element. After v2.0.3, the select helper would span across multiple days to match the user's selection, thus being multiple DOM elements. Since the selectHelper function could only generate a single element, it could not accommodate.

### better solution: use `eventRender` instead

[eventRender](https://fullcalendar.io/docs/event_rendering/eventRender/) will be called for the select helper elements, just like a normal element rendering pass. Here's how you can detect if it's a helper element:

```js
eventRender: function(event, el) {
    if (el.hasClass('fc-helper')) {
        // mutate el, or return a new el
    }
}
```

**Comment by arshaw** [comment]
update docs: https://fullcalendar.io/docs/selection/selectHelper/
