### ISSUE TITLE
Specifying View-Specific Options for a language doesn't work

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar#2850]
Before it was possible to specify the view hash for one language settings. After converting to View-Specific Options that is not possible. I can provide a full failing example but basically this doesn't work:

``` javascript
$.fullCalendar.lang('nb', {
  views: {
    month: {
      titleFormat: 'MMMM YYYY',
      columnFormat: 'ddd'
    }
 }
});
```

**Comment by arshaw** [comment]
I would expect those settings to resolve to the same format strings anyway:

titleFormat:
https://github.com/fullcalendar/fullcalendar/blob/master/src/common/View.js#L213
-> https://github.com/fullcalendar/fullcalendar/blob/master/src/lang.js#L90

columnFormat:
https://github.com/fullcalendar/fullcalendar/blob/master/src/common/DayTableMixin.js#L141

**Comment by arshaw** [comment]
but i guess that's beside the point. I would actually prefer to not allow i18n files to specify settings specific to views, because that won't scale up when new views are introduced, or in situations where a view can have an arbitrary duration (like Timeline or a custom view of basic/agenda).

I'd rather come up with a way to more intelligently compute a title format string based on the given lang settings, like [computeTitleFormat](https://github.com/fullcalendar/fullcalendar/blob/master/src/common/View.js#L208), even if that means adding new settings to the core options.
