### ISSUE TITLE
Events by day of week

### ISSUE THREAD

**Issue by ivlevdenis** [fullcalendar/fullcalendar#2883]
What you think about adding support of events by day of week?

**Comment by espen** [comment]
Like recurring events? Every Monday?

**Comment by ivlevdenis** [comment]
Yes

**Comment by espen** [comment]
Personally I think recurring events should be solved on the backend. But there is some discussion on this feature here: #387

**Comment by phumphries** [comment]
No matter how you are determining whether or not to send the data for the
recurring events from the back-end to the client, you have to do *something* to
ask for them.  So, if you are going to ask for a special kind of event, it seems
that, with a little bit more understanding of the problem, you can figure out
(from the many examples) how to send "actual" events that do not need any
additional processing by the client.

I am not opposed to the client having more capabilities.  It just seems to me
that, in order to use this proposed capability, you would have to understand
recurring events well enough to solve the problem at the source, anyway.

As an aside, I have always been impressed with the recurring events handling
that Palm used in its devices' calendar application.  You can check out the
database configuration of Palm's "databook" database, here:
http://www.notsofaqs.com/palmrecs.php  -- if you can read that, you definitely
will have no problem implementing a back-end solution. :-)

Peter E. Humphries

**Comment by chrisjcalderon** [comment]
Hello all,

I have a working solution for recurring events with fulcalendar. It isn't
perfect, but works really well for what I need. It is based on momentjs
recur plugin:  https://github.com/c-trimm/moment-recur  and using the dow
setting for the events in fullcalendar (so I could test matching rules).

It is all client side and very light weight. For capturing the event
information (and recurrence settings) I used bootstrap + knockout. For what
I needed, I can share what I prepared if you guys want it. I think moment
recur integrates well  given that full calendar already uses moment objects.

cheers

On Sun, Oct 4, 2015 at 8:56 PM, phumphries <notifications@github.com> wrote:

> No matter how you are determining whether or not to send the data for the
> recurring events from the back-end to the client, you have to do
> *something* to
> ask for them. So, if you are going to ask for a special kind of event, it
> seems
> that, with a little bit more understanding of the problem, you can figure
> out
> (from the many examples) how to send "actual" events that do not need any
> additional processing by the client.
>
> I am not opposed to the client having more capabilities. It just seems to
> me
> that, in order to use this proposed capability, you would have to
> understand
> recurring events well enough to solve the problem at the source, anyway.
>
> As an aside, I have always been impressed with the recurring events
> handling
> that Palm used in its devices' calendar application. You can check out the
> database configuration of Palm's "databook" database, here:
> http://www.notsofaqs.com/palmrecs.php -- if you can read that, you
> definitely
> will have no problem implementing a back-end solution. :-)
>
> Peter E. Humphries
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcalendar/fullcalendar/issues/2883#issuecomment-145410173>
> .
>



-- 
-- Christian Calderon

**Comment by espen** [comment]
Well @phumphries event entry is (at least for now) out of scope for Fullcalendar - you have to create the form input for event manually anyways.

moment-recur looks interesting @chrisjcalderon. I ended up making a very simple input (weekly/monthly and count) which produces RRULE string which I then parse with the icalendar-recurrence gem on the backend to generate each occurrence.

There is also http://jkbrzt.github.io/rrule/ and https://github.com/collective/jquery.recurrenceinput.js for generating icalendar-based recurrence on the client.

**Comment by arshaw** [comment]
there should be recurring event support in some way/shape/form in fullcalendar. #387 is where the discussion is, so closing this out

btw, there is a secret `dow` property on event objects, but not 100% exposed or supported yet. had to implement to get businessHours to work
