### ISSUE TITLE
timelineDay view does not work with jQuery 1.7.2

### ISSUE THREAD

**Issue by ryanbimmer** [fullcalendar/fullcalendar#2891]
timelineDay view throws the following error when using jQuery 1.7.2.

 
![image](https://cloud.githubusercontent.com/assets/5064970/10435509/78f49822-70ee-11e5-8644-319674594107.png)

**Comment by aherrick** [comment]
FYI I was able to get this to render by setting 'prefFetching' = true

I'm not exactly sure why or what the 'fetching' variable does. Probably isn't the right fix either.

`ResourceManager.prototype.fetchResources = function() {
    var prevFetching;
    prevFetching = true;`

**Comment by aherrick** [comment]
I may have been a bit premature here with this "fix" it doesn't appear to be correct.

You can see it not working with 1.7.2 here: http://jsbin.com/davogisoka/2/edit?html,js,console,output

Any ideas? Thanks guys!

**Comment by arshaw** [comment]
thanks! recreated

**Comment by 4levels** [comment]
I can confirm this issue with jQuery 1.7.1

**Comment by arshaw** [comment]
jQuery 1.8 introduced new behavior for the deferred `.then` method, which fullcalendar-scheduler is heavily relying on, so instead of trying to make it work with an old version of jquery, I'm simply going to make the minimum requirement for fullcalendar-scheduler be jquery>=1.8.0. I hope this doesn't inconvenience too many people.

**Comment by 4levels** [comment]
Hi Adam,

thank you for your reply.
I do however wonder what could be the issue as the calendar works fine
after selecting a date or changing the view.
I'm not sure what the negative impact of switching the whole CMS to jQuery
1.8 might comprehend as the CMS is very extended and uses quite some
internal jQuery methods to handle it's more advanced features.
As a paying customer I'd like to insist to have you at least have a look as
this seems like something definitely doable with jQuery 1.7 as the calendar
actually works after a single user interaction.  It must be related to some
initialization calls that have changed with jQuery 1.8

So please, could you have a look at this issue with your skills and
experience?

Kind regards,

Erik

**Comment by aherrick** [comment]
HI Adam,

We are very excited to use the calendar as well, unfortunately we are also bound with the fact that we HAVE to use jQuery 1.7.2

I'm now concerned about going forward that bug fixes will be done using jQuery 1.8+ APIs. We just found this bug locally in 1.0 (https://github.com/fullcalendar/fullcalendar-scheduler/issues/15) which we've now upgraded and things still seem to be working, however we have to use a local work around still in order to load resources for 1.7.2.

Is it that drastic of a difference between 1.7.2 and 1.8 that we can't load resources, even though 1.7.2 handles loading events just fine? Thanks for your time!

**Comment by espen** [comment]
What is the issue with upgrading to 1.8? From what I have seen jQuery didn't deprecate many things. They did however introduce some new stuff that makes it harder to downgrade to 1.7 than to upgrade to 1.8.

**Comment by arshaw** [comment]
@aherrick as @espen mentions, hopefully the upgrade to from 1.7.2 (which was released 3.5 years ago) to 1.8 isn't too difficult. I'm sorry, but the promise-related enhancements of 1.8 just make things too convenient and somewhat painful for the fullcalendar project to downgrade to.

**Comment by aherrick** [comment]
Hey @arshaw thanks for the reply. Unfortunately we are working within the confines of a "hosted CMS" similar to SharePoint that ships with 1.7.2 that we don't have control of. I agree it's old sitting at 3.5 years. It just hampers us in the ability to ensure a working solution and a license from a commercial perspective If you'd like to take this off thread (email) i'd be glad to.

**Comment by arshaw** [comment]
@aherrick if you'd like to hack this yourself, replace all the reference to `.then` in this file
https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/src/ResourceManager.coffee

... with jQuery's deprecate [.pipe](https://api.jquery.com/deferred.pipe/)

I apologize for not being able to help much further than this.

**Comment by arshaw** [comment]
it would just be a matter of a simple string replace of `.then` with `.pipe` i believe. easier than i thought. but hope u understand i don't want to introduce deprecated jquery method calls into the codebase at this point

**Comment by aherrick** [comment]
@arshaw thanks for the response! I understand what you're saying...All I ask is that you attempt to keep us  slaved to 1.7.2 in mind. thanks! :)
