### ISSUE TITLE
Month view: On days with a single event starting after midday, align event at bottom

### ISSUE THREAD

**Issue by martin-langhoff** [fullcalendar/fullcalendar#2920]
See the screenshot below. The two events on the bottom right of the screenshot should be displayed towards the bottom of the cell.

![calendar-screenshot](https://cloud.githubusercontent.com/assets/5116932/10800808/555c75b2-7d8a-11e5-9d3b-d5d9ad37e715.png)

**Comment by espen** [comment]
This is a feature, not a bug. Each day is just a list of events, not a visual representation of the hour of the day (and thus align evening appointments to the bottom).

You might be able to override the CSS to accomplish what you want, otherwise you could create a custom view calculates the top-margin or something for events. See http://fullcalendar.io/docs/views/Custom_Views/

**Comment by arshaw** [comment]
sounds like u desire something more like the `agenda` views, which convey time better

**Comment by martin-langhoff** [comment]
Yes, this is a feature request. ACLs on this github repo don't let me mark it as feature -- or maybe I used the wrong form.

Thanks for the suggestion to use agenda or Custom Views, but I find them overkill. Hopefully I can achieve this with CSS.
