### ISSUE TITLE
drop event returns mouseDown jsEvent

### ISSUE THREAD

**Issue by martin-langhoff** [fullcalendar/fullcalendar#2926]
the jsEvent returned is the mouseDown jsEvent. This is not documented, and I expected (and need!) the mouseUp event.

Currently working on a patch for this, adding a second jsEvent in the callback. If there's interest in merging it, I'll be happy to update docs, tests.

**Comment by martin-langhoff** [comment]
@arshaw -- so updated PR #2927 to tip of master (at v2.6.0). Should be straightforward, if you think this is the right fix.

**Comment by arshaw** [comment]
@martin-langhoff i appreciate the effort to make this backwards-compatible by adding an additional parameter, but I feel that the current behavior is a "bug"... any sort of final drop handler should only ever get the mouseup event. should not get the mousedown event at all. this is consistent with how `eventDragStop`, `eventDrop`, and `eventResize` do it.

So, I would simply take the event that `listenToExternalDrag` gets from `dragStop` and pass that into `reportExternalDrop` instead of the current `ev` (the mousedown). Make sense?

**Comment by martin-langhoff** [comment]
+1 from me!

As the project is yours, you get to decide compatibility or fix on subtle API bugs such as these. I took the conservative approach.

**Comment by arshaw** [comment]
thanks for taking the conservative approach. i think we can move ahead with this slightly-breaking approach. if you want to make another PR that threads `dragStop`'s `ev` parameter through, I would accept it.

**Comment by arshaw** [comment]
this is fixed for v4: 8715e098fad09a77c9e0426d4cf348d326ae13bb

i'll comment again on this issue when v4 is officially released

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
