### ISSUE TITLE
businessHours, doesn't display on agendaDay on weekends

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#2944]
the whole day should technically be grayed out. inconsistent with all the other views, which grays out whole Saturdays/Sundays.

http://jsbin.com/wegafolayo/1/edit?js,output

bug is happening somewhere near here:
https://github.com/fullcalendar/fullcalendar/blob/master/src/EventManager.js#L632

**Comment by Kyunghwa-Yoo** [comment]
Hi, i found this issue while doing my project using fullcalendar.
And i fixed it last night.
i want contribute this bugfix, but i don't know how to do this because it's my first contribution.

first of all, i forked repository and i edited code.
here is what i edited code
https://github.com/Kyunghwa-Yoo/fullcalendar/blob/master/src/EventManager.js#L874

i checked CONTRIBUTING.md document and successfully  `run grunt check`

next, what can i do? 
i create pull request. but i don't know it is right way to contribute bugfix.
please reply to me.

here is my pull request creation.
https://github.com/fullcalendar/fullcalendar/pull/3096

thank you.

**Comment by arshaw** [comment]
this has been fixed and release in [v2.9.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.9.1).
