### ISSUE TITLE
Business Hours is not working on Fullcalendar timelineDay view

### ISSUE THREAD

**Issue by smartkid77** [fullcalendar/fullcalendar#2995]
Here is the Url of the  demo : http://eo14.com/static/fullcalendar/

Demo is prepared for agenda view, but I want it to be worked for timelineDay, I tried to change the defaultView and view functions to fix it but I can't fix it. Please help me to fix it.

Regards
Dina

**Comment by arshaw** [comment]
would strongly prefer a [JSBin](http://fullcalendar.io/support/) to ensure that the demo never goes away from the internet.

the demo will only be useful if you allow clicking to `timelineDay` to demonstrate the problem.

can you post this to the [scheduler issue tracker](https://github.com/fullcalendar/fullcalendar-scheduler/issues) since this seems to be a timeline-specific problem?
