### ISSUE TITLE
allDay events lose end date when dragged

### ISSUE THREAD

**Issue by flack** [fullcalendar/fullcalendar#3037]
I have an event looking like this:

```json
{
    "id":"e6cccdde405155bf58e52401ea871df4",
    "title":"Test",
    "location":"",
    "start":"2016-02-09T09:30:01",
    "end":"2016-02-09T18:00:00",
    "allDay":true
}
```

and the following code to save it when dragged:

```js
function save_event(event, delta, revertFunc, jsEvent, ui, view) {
     $.post(url + 'event/move/' + event.id + '/', {start: event.start.add(1, 's').format('YYYY-MM-DD HH:mm:ss'), end: event.end.format('YYYY-MM-DD HH:mm:ss')})
        .fail(function(){
            revertFunc();
        });
}
```

This works fine for regular events, but for allDay events, I get `TypeError: event.end is null`

You can also (kind of) see the problem on your demo: 

http://fullcalendar.io/js/fullcalendar-2.6.0/demos/selectable.html 

If you go to the week view and drag the "Conference" event into the normal timeslots, the duration changes to two hours instead of two days.

**Comment by arshaw** [comment]
If your event data input doesn't have `end` properties, and you don't have [`forceEventDuration`](http://fullcalendar.io/docs/event_data/forceEventDuration/), then the Event Objects in the callbacks will have a `null` `end`. You'll just need to anticipate this scenario when attempting to do anything with these event objects

**Comment by arshaw** [comment]
ah, wait, i see you specified an `end`. strange.

will be hard for me to debug without a JSBin: http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by flack** [comment]
Here you go:

http://jsbin.com/fayekobodu/edit?js,output

Try dragging the event from the allday lane down to the timeslots. This will produce an error in the console

**Comment by arshaw** [comment]
thx for the jsbin. i will begin reproducing and debugging soon

**Comment by arshaw** [comment]
Sorry for the delay. Looking at this now, the answer is obvious to me: removing an event's end date upon a user drag-n-drop from all-day slots to timed slots is by design. See this issue for more info:

#2764
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

PS- your `end` date won't have its time processed anyway because it is allDay. See #2985 for more info.
