### ISSUE TITLE
Angular JS version for Scheduler

### ISSUE THREAD

**Issue by jdriesen** [fullcalendar/fullcalendar#3053]
Hello All,
Does smb know if there is an agular version available for Scheduler ?
In other words... is it possible to build a page like this http://fullcalendar.io/js/fullcalendar-scheduler-1.2.1/demos/vertical-resource-view.html with Angular

Thanks for your answer !
Grtz,
Johnny

**Comment by jdriesen** [comment]
Hi Sir,
With all respect, but why did you close my question ?
I'm super interested in your component ... I just want to use it with Angular.

Thanks,
Johnny

**Comment by espen** [comment]
@jdriesen http://fullcalendar.io/support/

**Comment by jdriesen** [comment]
Well Espen, I DID search on Stackoverflow, and it seems that more people are having the same question. That's why I came here ...

 http://stackoverflow.com/questions/35768154/combine-angularui-calendar-with-fullcalendar-io-scheduler
 
Grtz,
Johnny

**Comment by arshaw** [comment]
http://angular-ui.github.io/ui-calendar/ (not affiliated with this project)

**Comment by jdriesen** [comment]
Thanks Arshaw,
Found that one already, and I know it's not affiliated with this project), but I'm searching for your Schedular in Angular ... (I hope you might have it ...)

Thanks in advance for your reply,
Johnny

**Comment by espen** [comment]
@jdriesen I have never used Angular but be aware that a wrapper like that might complicate things. When refactored my FullCalendar implementation last year I was considering going down the MVC-route but ended up with vanilla JavaScript and a major reason was because FullCalendar already acts as a model (has all the data and can interact with it) and view (the calendar widget). FullCalendar will always store the calendar events so if you have a separate MVC framework with data you introduce complexity. FullCalendar should already be quite trivial to implement with your backend in a same way that Angular so I really don't see the benefit of combining the two. I might be wrong here given my lack of experience with Angular so my two cents here might not be the best recommendation for your app though.

(as for the support-link it's more about the issue tracker not being a place for questions, it's for issues)

**Comment by arshaw** [comment]
FWIW, there is a continuation of this discussion, as an (open) ticket on the fullcalendar-scheduler issue tracker: https://github.com/fullcalendar/fullcalendar-scheduler/issues/11
