### ISSUE TITLE
Calendar render eventEnd wrong

### ISSUE THREAD

**Issue by agmadt** [fullcalendar/fullcalendar#3072]
I see basic calendar in fullcalendar.io, the long event that start at Thursday 7 and ended in Saturday 9, the argument set in http://fullcalendar.io/js/home.js is actually ended in 10. Is it really like this or actually a bug?
Here's a jsfiddle https://jsfiddle.net/adhityoradeon/9qb5Lj7m/

**Comment by HartLarsson** [comment]
i think there is a bug or a strange behaviour

i've tested with this record:

        {
          title: 'Event test',
          start: '2016-01-16T08:00:00',
          end: '2016-01-20T08:00:00',
          allDay : true
        }

and the bug is present as you showed in the jsfiddle.

So i've tried to use the time parameter to explore if there is a sort of "limit":

        {
          title: 'Event test',
          start: '2016-01-16T08:00:00',
          end: '2016-01-20T09:00:00',
          allDay : true
        }

the event end will keep the 20 of the day as expected. seems for a strange reason that 09:00:00 si the limit to show the event bar in the day.

Don't know if there is something to enable to fix this problem.

**Comment by arshaw** [comment]
having an allDay event with times is a little contradictory. please see #2985 for more discussion

**Comment by HartLarsson** [comment]
ty for the answer but as you can see even without allday option not workign correctly

https://jsfiddle.net/adhityoradeon/9qb5Lj7m/
