### ISSUE TITLE
updateEvent, allDay to timed, when no end, wrong end date

### ISSUE THREAD

**Issue by damangio** [fullcalendar/fullcalendar#3144]
As demonstrated in [this fiddle](https://jsfiddle.net/kwyxwnv1/13/), when updateEvent changes an event from all-day to regular and specifies new start and end times, the resulting end time is 22 hours earlier than the specified end time. It happens with or without a time zone.

In the example the end time is set to April 29, 14:00, but the resulting end time is April 28, 16:00.

**EDIT**

This happens only if the original all-day event lasted only a single day, i.e. either the begin and end dates were the same, or there was no end date (these two situations are treated the same in FullCalendar).

~~**Workaround:** For such events, adjust the time by 22 hours before calling updateEvent().~~

**EDIT**

Also, if the specified begin and end times are exactly 24 hours apart, the resulting end time will be null.

**Workaround:** For such events, adjust the time by 22 hours and one second before calling updateEvent(). If you aren't displaying seconds to the user, the difference of a second won't affect the user.

**Comment by damangio** [comment]
Another manifestation of the bug, this time not involving all-day events. When an event has an end time of null, and updateEvent() sets the end time, if the begin and end times are exactly two hours apart, the resulting end time will still be null.

**Workaround:** For such events, add one second to the end time.

**Comment by arshaw** [comment]
Your example was a tiny bit confusing to me because the `end` date is invalid (needs to be after the start date because end dates are exclusive), but even after removing it, the bug still happens. thanks for the report.

**Comment by sebastienratez** [comment]
Quite related, when registering an all day event spanning from end - start = x days (x>1), it shows spanning over x-1 days in the week-view. 

I quickly checked the Moment date object stored for event.end and it looks like it's using the browser timezone offset instead of utc for rendering, but I'm not too sure about the internals.

**Comment by ooskapenaar** [comment]
@arshaw @sebastienratez  This is definitely a bug affecting "allDay" events.  This bug is easy to see on the timezone demo:  https://fullcalendar.io/js/fullcalendar-3.2.0/demos/timezones.html

When you set the time to "Hong Kong", you see all Sundays appointments move to Monday, excepting the AllDay events.

@arshaw: Any idea when this could be fixed?

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
Released in [v3.6.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.0)
