### ISSUE TITLE
Protractor e2e test fullcalendar drag & drop

### ISSUE THREAD

**Issue by grimimirg** [fullcalendar/fullcalendar#3171]
The issue is still opened on [Stackoverflow](http://stackoverflow.com/questions/37302207/protractor-e2e-test-fullcalendar-drag-drop) and I'm still not figuring out how to test it. 

Do have someone ever done a test like that?

**Comment by arshaw** [comment]
i dont know what Protractor is, but it sounds like the problem you describe is a shortcoming of Protractor and not FC

**Comment by DHFW** [comment]
For others, I had the same problem but then for Cypress (similar to Protractor, an e2e testing tool).
I posted my answer on the same StackOverflow question.

But also here for easy referencing:

Context:
We plan items from an external list and assign it to a resource on a certain day/time in the FullCalendar (we use the scheduler plugin).

I found out that the `drag` and `drop` event is somehow intercepted by code, enriching it with for example properties of the event (like date, title and others). How I enriched this data is in the Cypress `trigger('drop', data)` command. Data is the evenData that is set by the `Draggable` class:

```javascript
// Executed on the external list items, where every item we want to plan has class `.fc-event`.
this.draggableContainer = new Draggable(this.containerEl.nativeElement, {
        itemSelector: '.fc-event',
        eventData(eventEl) {
          const id = eventEl.dataset.id;
          
          return {
            duration,
            id: currentWorkItem.id,
            title: currentWorkItem.description,
            extendedProps: {
              duration,
              customRender: true,
              data: currentWorkItem,
            },
          };
        }

```

Then, in your test file (Cypress)

```javascript
const eventData = {
      date: new Date(),
      dateStr: new Date().toISOString(),
      draggedEl: {
        dataset: {
          notificationId: '123',
          priority: '0',
          title: 'Test',
        },
      },
      jsEvent: null,
      resource: {
        id: '123',
      },
      event: null,
      oldEvent: null,
    };

cy.get('.fc-event') // selector for the external event I want to drag in the calendar

      .trigger('dragstart')
      .get('.fc-time-grid table tr[data-time="07:00:00"] td.fc-widget-content:nth-child(2)') // selector for where I want to drop the event.
      .trigger('drop', eventData) // this will fire the eventDrop event

```

So, `.trigger('drop', eventData)` will fill the eventDrop info. It is not exactly the same as doing it manually, but works for me.

Caveats:

- I haven't found a way to plan it on another resource (we use the resource scheduling plugin of FullCalendar.io). It does not matter that much, because you can specify it in the evenData (`resource: { id: 'my-resource-id' } }`.
- No visual feedback because the drag mirror is not shown. Not a big problem during e2e testing, but it is a bit of a blackbox now. Maybe this is fixable
