### ISSUE TITLE
material design theme

### ISSUE THREAD

**Issue by TejasCMehta** [fullcalendar/fullcalendar#3184]
I want to use this calendar in Angular Material SPA application but it looks very oldish  design in compare to glorious material design.

**Comment by arshaw** [comment]
i understand, this would be very cool. but lower on the priority list compared to other features unfortunately

**Comment by arshaw** [comment]
I'm going to close this ticket because it seems this issue has gained some momentum for making a material design theme:
#2836
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
