### ISSUE TITLE
Fire dayClick when clicking on the header row

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar#3225]
I think it would be a good feature to fire `dayClick` when clicking on a header row in both FullCalendar and Scheduler, this will be useful for example when you have a 'navigate to day' function on the `dayClick` callback.

AgendaWeek screenshot:
![AgendaWeek screenshot](https://cloud.githubusercontent.com/assets/6674662/16078777/f416efbc-3300-11e6-8b43-30182396e41d.png)

Scheduler screenshot:
![Scheduler screenshot](https://cloud.githubusercontent.com/assets/6674662/16078787/ff6cd02a-3300-11e6-8cb2-77bcf49a01e6.png)

I wasn't sure whether to address this in the Scheduler or this repository, but since it also applies to the agenda views I decided to post it here.

**Comment by arshaw** [comment]
similar in nature to #424, but will keep this ticket around to remind to implement in Timeline view. thanks

**Comment by arshaw** [comment]
actually, since this has also been entered on the core tracker, we'll use the existing issue to keep track, so i'll close this one. ill remember to do it for Timeline

#424
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
