### ISSUE TITLE
Mobile device scrolling problem

### ISSUE THREAD

**Issue by foxalfabravo** [fullcalendar/fullcalendar#3227]
In my configuration, I have the following : 
            minTime : '08:00',
            maxTime : '20:00',
            height : "auto",
            longPressDelay: 1500,
=> No calendar scrollbar
On small screen devices, the displayed range in day view with title and fc-toolbar shows time from 8:00 to 15:00. 
When an event is selected by touch, it is not possible to move it after 15:00 as the view scrollbar won't be triggered.

http://jsbin.com/geyenu

**Comment by arshaw** [comment]
the bad behavior you're describing is almost certainly being caused by this bug:
https://github.com/fullcalendar/fullcalendar/issues/2761
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
