### ISSUE TITLE
addEventSources method, similarly to the removeEventSources

### ISSUE THREAD

**Issue by rizoom** [fullcalendar/fullcalendar#3262]
The purposes of this method would be to avoid multiple full events re-rendering when adding several event sources in a batch, similarly to the new removeEventSources method.
While this is not an issue when event sources are added during the full calendar initialization it is when event sources are added dynamically.

**Examples**
Simple jsbin to show the rerendering (see console output), event 1 is rendered twice when sources are dynamically added.
[dynamic sources](http://jsbin.com/jubiyoyugu/1/edit?js,console,output) / [static sources](http://jsbin.com/qizuruqoxa/1/edit?js,console,output)

**Comment by DanielTung** [comment]
Would be nice!
Currently I can remove a bunch of event sources with an array but adding them requires an iterator. Would be nice just to pass the array of sources I have already constructed.

**Comment by arshaw** [comment]
in v4, you can combine [addEventSource](https://fullcalendar.io/docs/v4/Calendar-addEventSource) with [batchRendering](https://fullcalendar.io/docs/v4/Calendar-batchRendering) to get this effect.

I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
