### ISSUE TITLE
FullCalendar display is different from Google Calendar display

### ISSUE THREAD

**Issue by fanmusic** [fullcalendar/fullcalendar#3264]
Hi support team,

I'm using FullCalendar to display events from our public Google Calendar. I found that the calendar rendered by FullCalendar is different from the one rendered by Google Calendar. 

Here is the details:
-My local timezone is UTC+07:00
-My event ends on 05:00 AM 07/06/2016 in UTC+07:00, which means 10:00 PM 07/05/2016 in UTC
-In FullCalendar display(using timezone="local"), the event ends on 07/05/2016, while on Google Calendar, the event ends on 07/06/2016 which is correct for me.
-I tried to clear the timezone options or specify a timezone string "Asia/Ho_Chi_Minh", "Asia/Bangkok" but it didn't work.

Could you show me how to render FullCalendar correctly in this case?

Thanks,
Huy Tran.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it.

**Comment by fanmusic** [comment]
@arshaw I created a demo here http://jsbin.com/pihiyuf.

I am from Vietnam, my local timezone is UTC+07:00. The event in the demo starts at 05:00 AM 08/16/2016 and ends at 05:00 AM 08/17/2016. In Google Calendar, the event displays in 2 days which is correct but in FullCalendar, it displays only in 08/16/2016. See attached screenshots.
![test_event_displayed_on_fullcalendar](https://cloud.githubusercontent.com/assets/8974213/17657717/d44900de-62ef-11e6-8176-1b05b01f9fe3.png)
![test_event_displayed_on_google_calendar](https://cloud.githubusercontent.com/assets/8974213/17657718/d454ecd2-62ef-11e6-84bb-0e15266ee4e3.png)

Thanks,
Huy Tran.

**Comment by fanmusic** [comment]
Here is the test calendar url https://calendar.google.com/calendar/embed?src=96setpscl5jsplel6da01hnf3o%40group.calendar.google.com&ctz=Asia/Saigon.

**Comment by arshaw** [comment]
first off, you'll want to remove the `timezone: 'local'` and do `timezone:false` instead (which is the default. so, just remove the line). this will display the dates exactly according to the defaults of the google calendar.

second, set your `nextDayThreshold: '05:00'`
http://fullcalendar.io/docs/event_rendering/nextDayThreshold/

The nextDayThreshold is set to 9:00 by default in order to match what google calendar was previously doing, but it seems that google calendar changed the value.

I have plans to set the default to `00:00` anyway:
https://github.com/fullcalendar/fullcalendar/issues/2902

updated demo:
http://jsbin.com/gamofawipe/1/edit?html,js,output

**Comment by fanmusic** [comment]
Thanks @arshaw,

I set nextDayThreshold: '05:00' and it works as expected. I still keep timezone: 'local' because I want the calendar displays in my user's timezone.
