### ISSUE TITLE
Fullcalendar using a CSS grid

### ISSUE THREAD

**Issue by pezza3434** [fullcalendar/fullcalendar#3318]
Hi all,

I'm trying to create a custom view so that full calendar will use a div based css table instead of a table and I'm not getting very far.

As soon as I change the wrapping table to a div it renders nothing inside the calendar.

Any idea how what I want to do may be achieved?

Thanks a lot

**Comment by arshaw** [comment]
it will be really hard to move away from table-based layout via just CSS. the JS will need to be changed drastically because it relies on the structure. the project started using this convoluted CSS/DOM setup to work better with rendering for printers, but plan to move away from that especially to implement [better responsiveness](https://github.com/fullcalendar/fullcalendar/issues/3187)
