### ISSUE TITLE
columnHeader : Option to not escape the format. (And fc-today class on week view issue)

### ISSUE THREAD

**Issue by Rouche** [fullcalendar/fullcalendar#3337]
### Feature Requests
Hello,

First i dont know if its a bug or feature request, but fc-today does not appear in week view on the header.

Main request: could you add an option for the columnFormat to not escape the formatting result?

I would like to style just a part of the string. The day number is inside a pill.
```columnFormat: 'ddd [<span class="my-custom-day-number">]D[</span>]'```

Add an option like ```columnFormatRaw: true```

And then
```
    renderHeadDateCellHtml: function(date, colspan, otherAttrs) {
        var view = this.view;

        return '' +
            '<th class="fc-day-header ' + view.widgetHeaderClass + ' fc-' + dayIDs[date.day()] + '"' +
                (this.rowCnt === 1 ?
                    ' data-date="' + date.format('YYYY-MM-DD') + '"' :
                    '') +
                (colspan > 1 ?
                    ' colspan="' + colspan + '"' :
                    '') +
                (otherAttrs ?
                    ' ' + otherAttrs :
                    '') +
                '>' +
                // don't make a link if the heading could represent multiple days, or if there's only one day (forceOff)
                view.buildGotoAnchorHtml(
                    { date: date, forceOff: this.rowCnt > 1 || this.colCnt === 1 },
                    this.columnFormatRaw? date.format(this.colHeadFormat) : htmlEscape(date.format(this.colHeadFormat)) // inner HTML
                ) +
            '</th>';
    }
```

Thanks

**Comment by Rouche** [comment]
I could actually take care of those two and do a pull request if you want.

Just tell me if its acceptable (will be) or not.

Thanks.

**Comment by arshaw** [comment]
hi @Rouche, this existing ticket captures what you want:
https://github.com/fullcalendar/fullcalendar/issues/3331
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

There are a lot of instances of people wanting certain settings to accept HTML instead of text (see the [Text/HTML tag](https://github.com/fullcalendar/fullcalendar/labels/Text%2FHTML), and I prefer to come up with a solution/convention that solves everything rather than do one-offs. In the meantime, your hax are the best way to achieve.

**Comment by Rouche** [comment]
Oops, i did not catch that one. Definatelly could solve the custom heading.

But the ```.fc-today``` class on week view tough, is still an issue.

**Comment by arshaw** [comment]
for the fc-today issue, could you post a separate ticket? a runnable [jsbin](https://fullcalendar.io/wiki/Reduced-Test-Cases/) is a requirement, thanks!

**Comment by Rouche** [comment]
Will do.

Thx.
