### ISSUE TITLE
No Title w/Google Business Calendar

### ISSUE THREAD

**Issue by rhukster** [fullcalendar/fullcalendar#3338]
The Calendar in question is here:

https://calendar.google.com/calendar/embed?src=rockettheme.com_vmapoeesqfgbp6fo6biadiqj7s%40group.calendar.google.com&ctz=America/Denver

**JSBin here**: http://jsbin.com/kohasimiwo/edit?html,js,console,output

As you can see it has one event (tonight), with a title, description etc. However, when I try to view this with FullCalendar, it displays weirdly with no title:

![js bin - collaborative javascript debugging 2016-09-08 17-35-56](https://cloud.githubusercontent.com/assets/1084697/18370502/bac4d3dc-75ea-11e6-9591-b45184bd6db2.png)

![js bin - collaborative javascript debugging 2016-09-08 17-36-25](https://cloud.githubusercontent.com/assets/1084697/18370510/cb5595e2-75ea-11e6-809e-5e64c47acd54.png)

![js bin - collaborative javascript debugging 2016-09-08 17-35-18](https://cloud.githubusercontent.com/assets/1084697/18370492/ae06d6a4-75ea-11e6-8dc7-093ad9d63e46.png)

**Comment by arshaw** [comment]
when i visit your embed, the event title is simply "busy", which means the title is not publicly available because it has been blocked by your gcal's busy/free setting. you can see this if you log out of your google account. fullcalendar simply displays these events as empty titles. we might be able to come up with a way to better visually communicate this, but that is probably tangential to your main concern.
