### ISSUE TITLE
Unselect Callback Return Order

### ISSUE THREAD

**Issue by acidnine** [fullcalendar/fullcalendar#3341]
Per documentation: https://fullcalendar.io/docs/selection/unselect_callback/
Expected: function(view, jsEvent)
Actual: function(jsEvent, view)

Reproduced: http://jsbin.com/yequqolufu/1/edit?html,js,console,output

Easiest fix is updating the documentation to read function(jsEvent, view)? since convention seems to return jsEvent before view on other callbacks.

**Comment by arshaw** [comment]
yes, ill update the docs. thanks!

**Comment by caseyjhol** [comment]
@arshaw Actually, this appears to be more than just a documentation issue. The second argument is indeed the view, but the first argument is not jsEvent, it's `undefined`. It looks like jsEvent in `unselect` hasn't worked properly since v2.0.3.

- v2.0.3: http://jsbin.com/pihekagegu/edit?html,js,output
- v3.5.1: http://jsbin.com/bumutohezu/edit?html,js,output

**Comment by arshaw** [comment]
the docs are now fixed for this

and the unselect() callback is receive in the `ev` now

**Comment by arshaw** [comment]
(in v3.6.0, just released)
