### ISSUE TITLE
method to changeView and gotoDate

### ISSUE THREAD

**Issue by harish0000** [fullcalendar/fullcalendar#3366]
Version 3.0.1
Js Bin : [http://jsbin.com/dalacivoye/edit?html,css,js,output]

On click of day viewRender is called twice. In the previous versions viewRender is only calling once.

I am using Ajax to fetch the events ,so double viewRender makes the event render twice.
check the above JS Bin[3.0.1].

But with Version 3.0.0
viewRender is only calling once 
JS BIN [3.0.0.] : http://jsbin.com/zaciricavo/1/edit?html,output

**Comment by arshaw** [comment]
It's called twice because the `changeView` and `gotoDate` method calls both trigger a rerender. The `gotoDate` won't rerender however if the date being navigated to is already in view. Probably why it seems intermittent or different across versions. I can bet it's actually the same for both versions. Both demos fire it twice for me.

This is more of a request to batch the render together. This will likely be solved then [the debounce technique](https://github.com/fullcalendar/fullcalendar/issues/2938) is implemented, which is not just for event rendering.

**Comment by michaeldever** [comment]
Having this issue too, changing view is calling events twice, which results in duplicated API calls.

**Comment by arshaw** [comment]
Released in **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

See [changeView](https://fullcalendar.io/docs/views/changeView/)'s new argument
