### ISSUE TITLE
in release @3.0.1 prev month and next month dates are not disabled

### ISSUE THREAD

**Issue by Sandip9021** [fullcalendar/fullcalendar#3386]
Hi @arshaw ,

In release @3.0.1 prev month and next month dates are not disabled for a current month. 
In @2.7.3 it was there. 
Screenshot attached ,
![image](https://cloud.githubusercontent.com/assets/17237067/19597417/f92f4100-97b1-11e6-8847-e180a4f6566d.png)

Previously in @2.7.3 it was like below ,

![image](https://cloud.githubusercontent.com/assets/17237067/19597486/8b6eaa9c-97b2-11e6-9308-c434e30e8aae.png)

**Comment by arshaw** [comment]
you sure? this is working for me:
https://fullcalendar.io/js/fullcalendar-3.0.1/demos/agenda-views.html

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by arshaw** [comment]
you are likely seeing this problem because v3 introduces a slightly different classname structure for the day headers. i bet you have custom css targeting the headers.
