### ISSUE TITLE
Mouse scroll wheel stops event dragging immediately

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3487]
1. begin dragging an event with a *mouse*
2. start scrolling the mouse's scroll while the drag is happening
3. the wheel will immediately kill the drag, even before a mouseup

DESIRED: drag should continue until a mouseup happens. dragging should adjust to the scrolling while it happens.

Recreatable on:
https://fullcalendar.io/
https://fullcalendar.io/scheduler/

The previously used to work. Funny enough, if you use an Apple touchpad to do the scroll while dragging, that event drag correctly persists.

**Comment by arshaw** [comment]
This might only be affecting me because of my specific mouse.

**Comment by SirDre** [comment]
Which brand/model mouse are you using? Maybe check if the driver is up to date to improve your experience (click-ability).

**Comment by dreadnautxbuddha** [comment]
currently using fullCalendar 3.1.0 and this issue still exists.
1. Drag external event
2. While "carrying" the draggable object, scroll through the calendar (e.g., you started scrolling on row 1)
3. Drop the object. (e.g., drop the object on row 3)

The eventDrop function will receive row 1 instead of row 3

**Comment by korengal** [comment]
Hi,
any news :) ?

**Comment by arshaw** [comment]
this is fixed when i try it out with v4. can anyone else confirm?

**Comment by arshaw** [comment]
this seems fixed!
