### ISSUE TITLE
Event is showing in the next day only after 9am, but why?

### ISSUE THREAD

**Issue by mok-liee** [fullcalendar/fullcalendar#3503]
Hello fullcalendar Team,

i cannot explain it good with words, i try to explain it with images:

Situation 1:
**Event is from 1/24 7:00am to 11:30am**
![1](https://cloud.githubusercontent.com/assets/6745620/22251101/de671c20-e249-11e6-8d22-0767aa1c8b6b.PNG)

![2](https://cloud.githubusercontent.com/assets/6745620/22251143/026b89e4-e24a-11e6-9aed-688cf70d85af.PNG)

![3](https://cloud.githubusercontent.com/assets/6745620/22251144/04bdcb76-e24a-11e6-9db5-246629339edf.PNG)

Everything is great!

Bad Situation 2:
**Event is from 1/24 7:00am to 1/25 07:30am**

![4](https://cloud.githubusercontent.com/assets/6745620/22251232/4e638b6c-e24a-11e6-9626-9268fc0950bd.PNG)
In week view is everything great.

![5](https://cloud.githubusercontent.com/assets/6745620/22251247/5c8941a0-e24a-11e6-81bc-088f32eb82bc.PNG)

![6](https://cloud.githubusercontent.com/assets/6745620/22251257/61dd2112-e24a-11e6-85fd-44a98b7b5f7a.PNG)
Why is the Event in month view not in 1/25?

Situation 3:
**Event is from 1/24 7:00am to 1/25 09:00am**
![7](https://cloud.githubusercontent.com/assets/6745620/22251322/a281a42c-e24a-11e6-8d20-36d35c82f25f.PNG)

![8](https://cloud.githubusercontent.com/assets/6745620/22251325/a568d278-e24a-11e6-9e92-b82caf4a81f8.PNG)

![9](https://cloud.githubusercontent.com/assets/6745620/22251329/a78fb710-e24a-11e6-82cc-b22326a11c59.PNG)

Here is everything okay. I think that is not normal or did i misunderstood?

I hope u can help me, greetings mok

**Comment by criztovyl** [comment]
:+1: for the visualization.

**Comment by arshaw** [comment]
this is because of [nextDayThreshold](https://fullcalendar.io/docs/event_rendering/nextDayThreshold/). if you set it to `00:00`, it will work the way you expect.

can you please upvote this ticket? it addresses change the default to be more reasonable.
https://github.com/fullcalendar/fullcalendar/issues/2902
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
