### ISSUE TITLE
Callback when a view's type or dates change (viewChange?)

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3521]
The [viewRender](https://fullcalendar.io/docs/display/viewRender/) callback is called every time a view's DOM is rendered/rerendered. It gets fired on a view's initial render, but it also gets fired when a [dynamic options change](https://fullcalendar.io/docs/utilities/dynamic_options/) occurs that requires a view rerender. [Or potentially for other reasons](https://github.com/fullcalendar/fullcalendar/issues/2709).

However, there is no callback that gets fired exclusively when there is a **view-switch** or the **date-range change**.

A common usecase: want to do post-processing on the DOM of the `fc-title` element at the top of the calendar, which is dependent on the date range but independent of the view.

Potential names for this callback: `viewChange` ?

Question: what if the view's *type* changes (ex: agenda->basic), but the date range does not. should it still fire?

**Comment by arshaw** [comment]
Brought to my attention by https://github.com/fullcalendar/fullcalendar/issues/3519

Many people have requested this in the past. Some tickets:
https://github.com/fullcalendar/fullcalendar/issues/2239
https://github.com/fullcalendar/fullcalendar/issues/969

**Comment by FreexD** [comment]
@arshaw any updates on this after fullcalendar-v4 release? 

I'm asking because we are currently trying to upgrade to fullcalendar v4 and in this new release the `viewRender` callback got replaced with `datesRender` - only renamed according to https://fullcalendar.io/docs/upgrading-from-v3 - but `datesRender` does not fire when view type switches, just when the set of dates is rendered.

In our project we need the `view.name` for fetching events in `eventSource`. Previously with `viewRender` triggering on view change, we were able to cache the `view.name` before `eventSource.refetch` function was triggered. Right now with `datesRender` and `viewSkeletonRender` running after `eventSource.refetch`, we have no callback to cache the `view.name` at and the (React wrapper) `calendarRef.getApi().view` still returns the old view at that point. It break calendar navigation for us - we need to use custom buttons, custom nav links, and pretty much have to cache the view type before every `changeView` or `gotoDate` call.

The solution for our case would be implementing the `viewChange` method that you mentioned before. It would be best if it fired on both view type and date range change, and would take them as arguments because then we would be able to use native navLinks, navigation buttons and methods with our handler in one place.

**Comment by Phibedy** [comment]
Would be great if this was added in V5 #5342 :+1:

**Comment by gongAll** [comment]
@Phibedy V5 already has a [milestone list](https://github.com/fullcalendar/fullcalendar/milestone/27). I believe it is static.

**Comment by arshaw** [comment]
In the [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features) this is called [datesSet](https://fullcalendar.io/docs/v5/datesSet)

**Comment by mirlannur** [comment]
> In the [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features) this is called [datesSet](https://fullcalendar.io/docs/v5/datesSet)

datesSet callback is not working in my case.

**Comment by joaolisboa** [comment]
@mirlannur Have you figured out a solution? The callback isn't working for me either

**Comment by serhsavchuk** [comment]
@mirlannur Looks like you put methods in data, you need to put methods after the data. But thanks, it helps me a lot!
@joaolisboa Pin code for betters undersanding. @mirlannur  is missed some curly braces, if you fix it, it works.
Example below

```
<template>
  <FullCalendar ref="fullCalendar"
    class='demo-app-calendar'
    :options='calendarOptions' 
  >
    <template v-slot:eventContent='arg'>
      <b>{{ arg.timeText }}</b>
      <i>{{ arg.event.title }}</i>
    </template>
  </FullCalendar>
</template>

<script>
import FullCalendar from '@fullcalendar/vue'
import dayGridPlugin from '@fullcalendar/daygrid'
import timeGridPlugin from '@fullcalendar/timegrid'
import interactionPlugin from '@fullcalendar/interaction'
export default {
  components: {
    FullCalendar,
  },
  data: function() {
    return {
      calendarOptions: {
        //...
            headerToolbar: {
              left: "prev,today,next",
              center: "",
             right: "dayGridMonth,timeGridWeek,timeGridDay",
            },
            datesSet: this.handleDatesSet,
        //...
      }
    },  //was missed
  }     // was missed too
  methods: {
    handleDatesSet(dateInfo){
       console.log("handleDatesSet handled", dateInfo);
    },
  },
}
</script>
```
