### ISSUE TITLE
The timeline starts with the incorrect of the day in mode of the month

### ISSUE THREAD

**Issue by AnnaKuzova** [fullcalendar/fullcalendar#3538]
Hello!

In our calendar the timeline starts with the incorrect of the day in mode of the month.
In other modes correctly
I have attached screenshot https://drive.google.com/file/d/0BwzedJ6VKLxWbzJKbEkwVThCUnM/view?usp=sharing

**Comment by criztovyl** [comment]
Isn't that rather a problem of the event dates rather than of FullCalendar?
The weeks itself always starts on Monday, every "WK X"  starts with "Mo Y".

![header](https://cloud.githubusercontent.com/assets/2174918/23093020/567e3e4a-f5d8-11e6-9ea2-772ee34755b7.png)

**Comment by AnnaKuzova** [comment]
Hi,

My colleague will respond better to this question. Add please volodgel@yandex.ru

**Comment by criztovyl** [comment]
Your Colleague should create a GitHub account and comment on this issue, (s)he does not need to be added anywhere.

**Comment by nikolaevvladimir** [comment]
Hi

>>Isn't that rather a problem of the event dates

May be
But why in other modes the events look ok?

Thanks!

**Comment by criztovyl** [comment]
Could you attach some more screenshots, i.e. if other modes?

**Comment by AnnaKuzova** [comment]
Of course
https://drive.google.com/drive/folders/0BwzedJ6VKLxWUVVmWmg5TTc0cmM?usp=sharing

**Comment by arshaw** [comment]
could you please open a ticket on the [fullcalendar-scheduler issue tracker](https://github.com/fullcalendar/fullcalendar-scheduler/issues), since this is an issue about timeline view?

To briefly dig into your question.. do you mean to say that the *week number* calculation is off? There are ways to manipulate that:
https://fullcalendar.io/docs/display/weekNumberCalculation/
