### ISSUE TITLE
renderEvent next button problem in angendaWeek

### ISSUE THREAD

**Issue by bandess** [fullcalendar/fullcalendar#3561]
If I set up a calendar, and give allDay repeating event through renderEvent it appears on the first week. But if I click on the next button this event disappears from allDay and appears at 12a.m. and stays like this if you keep clicking on the next and prev buttons. 

Here is my example:
https://jsbin.com/wedebew/edit?html,output

**Comment by arshaw** [comment]
Since the `dow` property is not officially supported for events (only business hours), I won't try to debug this. Things should be all better once recurring events is officially implemented:
https://github.com/fullcalendar/fullcalendar/issues/387
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
