### ISSUE TITLE
Event wrong in fullcalendar when use IOS (IPhone or IPad)

### ISSUE THREAD

**Issue by wiiwilasinee** [fullcalendar/fullcalendar#3583]
## When open calendar in IOS show event wrong but when open in android it true.
How can it fix it?
Thank you for your help :) 

## **In android** 
![photo_2017-03-17_17-27-32](https://cloud.githubusercontent.com/assets/22979416/24039352/6d1acb72-0b37-11e7-9c50-b8ae1812c5cb.jpg)

## **In IPhone**
![s_5795863022058](https://cloud.githubusercontent.com/assets/22979416/24039389/8f4f23fa-0b37-11e7-8424-840f4b0df04d.jpg)

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

If you post a reduced test case, I will open it up on both Android and iOS and witness the problem hopefully.
