### ISSUE TITLE
oldMomentProto.time error raised when rerendering edited event end date

### ISSUE THREAD

**Issue by toxaq** [fullcalendar/fullcalendar#3726]
If you change a rendered event's end date, rerendering the calendar will error with `Uncaught TypeError: Cannot read property 'apply' of undefined  at r.newMomentProto.time` is raised.

Reproduction below:

https://codepen.io/toxaq/pen/LLbrgx

I may be doing something wrong but this seems to have happened in a recent upgrade to v3 from v2.

**Comment by arshaw** [comment]
As you have discovered, after an event object is created, it must always have a "fullcalendar" moment rather than a merely a "raw" moment made with the plain `moment()` constructor. Your fix, which works:

```js
mike.end = $.fullCalendar.moment('2017-06-16T10:30:00').add(60,'minutes');
```

I wish the system were robust enough to handle it regardless. But this API is a bit primitive for mutating events, I must admit. Rather than investing more work into it, I'm planning on making a more formal model layer for the next major version of FC, so please stay tuned,

**Comment by toxaq** [comment]
Ok, thanks for the update @arshaw Adds an ugly reference to my Pojo models but I can live with that for now. When looking at the fullcalendar moment decorator code it seemed to just be missing a null check, so I thought that might have been an easy fix from a quick laymans look.
