### ISSUE TITLE
Event list at onDayClick Listener

### ISSUE THREAD

**Issue by wofdwid** [fullcalendar/fullcalendar#3741]
It is possible with fullcalendar to retrieve the list of all events linked with the day in `onDayClick` Listener? At now, I just see the parameters `date`, `allDay`, `jsEvent` and `view`.  
  
Thank you all.

**Comment by arshaw** [comment]
this issue is a more general version of what you describe:
https://github.com/fullcalendar/fullcalendar/issues/3217
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by wofdwid** [comment]
Okay, did. Really thank you and, sorry for didn't search it and release that it's already created before, as an another opened discussion.  
I hope you enjoy the day. **:-)**
