### ISSUE TITLE
Event Object "date" property removed after "updateEvent" call

### ISSUE THREAD

**Issue by nikolaglumac** [fullcalendar/fullcalendar#3835]
Hi!

In the latest FullCalendar version (`v3.5.1`) when an `event` containing `date` property is saved via `$('#calendar').fullCalendar('updateEvent', event)` call the `date` property is omitted from the event.

This issue is probably similar to this one I have reported earlier: https://github.com/fullcalendar/fullcalendar/issues/3819

Thanks for looking into this!

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

The `start` property is probably taking priority over the `date` property, which has always been the case tho

**Comment by arshaw** [comment]
as i touched on in my previous comment, the `event` object will already have a `start`, and if you set the `date`, and then pass it into updateEvent, then the `date` will be ignored. This is expected behavior ... `start` will take precedence.

I will keep this behavior as-is (It must have existed for a while).

Things will change when I introduce a new API for manipulating event objects in 4.x

**Comment by nikolaglumac** [comment]
@arshaw it is expected that date property is ignored and this is correct behaviour. The problem is that date property is removed/omitted from the event object. Can't we just ignore it and leave it there?
