### ISSUE TITLE
themeSystem not available for angular2

### ISSUE THREAD

**Issue by ultimasoul** [fullcalendar/fullcalendar#3867]
Hello,
by downloading the latest **fullcalendar** (3.6.0) via npm with the command

**$ npm install fullcalendar**

as explained [here](https://fullcalendar.io/download/), I don't see the _themeSystem_ parameter in the @types/fullcalendar@types/fullcalendar/index.d.ts

Actually In the **index.d.ts** file I see that the version is older:

_// Type definitions for FullCalendar **2.7**_

This happens also if I try to download the specific package 3.6.0:

**$ npm install fullcalendar@3.6.0**

Does anybody know the reason?

**Comment by arshaw** [comment]
It's because the [DefinitelyTyped definition](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/fullcalendar) is not up to date w/ the latest API change. You could submit a PR for a proposed change to that file.

Also, here are some longer term plans that might affect you: https://github.com/fullcalendar/fullcalendar/issues/3889
