### ISSUE TITLE
Now Indicator arrow not properly updated since 3.6

### ISSUE THREAD

**Issue by neroux** [fullcalendar/fullcalendar#3872]
Since 3.6 the _Now Indicator arrow_ does not get updated properly anymore after changing dates. It appears the way how `.fc-content-skeleton` containers are created was changed and the previous one does not get replaced anymore upon a change but the new one is simply appended.

In this context it seems the `.fc-now-indicator-arrow` element is added to all those containers now but only removed from the first (most recent?) in the DOM.

**Comment by neroux** [comment]
@arshaw Re-opened as I can now actually reproduce it. Still works under 3.5.1, seems to have been introduced with 3.6.

**Comment by neroux** [comment]
@arshaw From what I could debug so far, it seems the problem is a few layers above the arrow element. The `div.fc-content-skeleton` element seems to be duplicated on each period change since 3.6.

**Comment by dhiemstra** [comment]
Also have this issue. FC doesn't remove the element from the DOM at all.

![image](https://user-images.githubusercontent.com/37780/31770037-6abc9100-b4d6-11e7-9ca3-590cb38f11e0.png)

**Comment by arshaw** [comment]
thanks, I'll take a look at this for the next bugfix release

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
released in [3.6.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.6.2)

**Comment by joseluismolinasoria** [comment]
Hi.

In version 3.8.0, the same problem occurs again. Fullcalendar doesn't erase the previous "now 

**Html source:**
![now-indicator](https://user-images.githubusercontent.com/3055726/34209222-98b2e5be-e591-11e7-9e13-8fc63def1700.png)

**Render:**
![now-indicator1](https://user-images.githubusercontent.com/3055726/34209223-98d25444-e591-11e7-865d-1452fb3abe27.png)

Thank you.

**Comment by acerix** [comment]
@joseluismolinasoria Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tried to reproduce the issue, but it's working as expected here:

https://codepen.io/anon/pen/YYGQXq?editors=0010

**Comment by joseluismolinasoria** [comment]
@acerix, I can't isolate the problem in codepen.io. I will keep trying. But I have been able to observe the following behavior:
![image](https://user-images.githubusercontent.com/3055726/34291187-58c97f6a-e6fb-11e7-8bd3-8fdcbc0a8108.png)
As seen in the image the tag fc-content-skeleton is duplicated.

**Comment by acerix** [comment]
I adjusted the example to be like "vertical resources", but don't have any issue like the original one above.  

https://codepen.io/anon/pen/WdGqQX?editors=0010

There is an `indicator-arrow` on each column which is why it's you see more than one, and the 2 `skeleton` divs are different parts of the calendar.

**Comment by acutus** [comment]
We are seeing this with Fullcalendar 3.9.0 and scheduler 1.9.4. Seems to be especially when the calendar is idling in a background tab if that is any useful as a hint. 

@acerix Let me know if I should report this as a new issue instead of reopen.

![screenshot from 2018-09-05 10-22-32](https://user-images.githubusercontent.com/2551825/45077695-84b99b80-b0f6-11e8-9e56-dac1a6facd1c.png)
![screenshot from 2018-09-05 10-28-31](https://user-images.githubusercontent.com/2551825/45077699-86835f00-b0f6-11e8-962f-ea6e5841ff35.png)
