### ISSUE TITLE
Add TimeGridEventRenderer to FC namespace so that it becomes easy to extend it.

### ISSUE THREAD

**Issue by mlakhara** [fullcalendar/fullcalendar#3885]
Add TimeGridEventRenderer to FC namespace so that it becomes easy to extend it.

**Comment by arshaw** [comment]
This is already possible by accessing `FC.TimeGrid.prototype. eventRendererClass `

I'd prefer not to expose any more internal classes of this nature.

**Comment by mlakhara** [comment]
@arshaw I ended up doing the same thing. btw, thanks for the awesome library.

**Comment by MiguelQueiroz** [comment]
How do you actually extend this? because i get some errors about some "dependency like utils_1" to undefined? did you just replace the prototype directly? If someone could guide me.

For example i would like to modify the TimeGrid.prototype.renderSlatRowHtml to append a extra class to the axis in some conditions.  Right now, im chaging the source code directly but, would prefer to replace the TimeGrid.prototype.renderSlatRowHtml with other TimeGrid.prototype.renderSlatRowHtml copy but modified? but util_1 become undefined ;x

**Comment by acerix** [comment]
@MiguelQueiroz Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.
