### ISSUE TITLE
Typescript definition within project

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3889]
One of my goals is to move FullCalendar to Typescript.

Once this happens, the **index.d.ts** file that is maintained by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) will be obsolete. This is good because the responsibility will rest on the fullcalendar project to maintain the definition, and there won't be any lag when API changes arise.

Will only matter for internal development. Will not force users of FullCalendar to use typescript of course.

**Comment by stehag** [comment]
This is really great news!
Can you elaborate a bit how the transition will be done and when it will start?
Just asking since i'd like to chip in :)

**Comment by arshaw** [comment]
hi @stehag thank you for offering to help. I'd like to keep nearly all JS files as-is, and port them over to .ts modules one by one. I'd like to devise an incremental approach for this. Will be very manual work. I'd like to avoid using TypeScript features as first, leaving types optional, until all modules have been converted over, and then begin to clamp down on type enforcement.

Could you please email at arshaw at fullcalendar.io if you are interested?

**Comment by arshaw** [comment]
as of 3.8.0
https://github.com/fullcalendar/fullcalendar/releases/tag/v3.8.0

fullcalendar.d.ts is included in the npm package and is wired up:
https://github.com/fullcalendar/fullcalendar/blob/v3.8.0/dist/fullcalendar.d.ts

**Comment by Adrael** [comment]
@arshaw Thanks for the great work!
I'm having a bad time trying to work with fullcalendar.d.ts.
The following error always pop out whenever I try to use the project's definition file instead of the one provided by DefinitelyTyped.
The only solution I found so far is to remove your .d.ts from the npm package once installed locally and switch to DefinitelyTyped, which is not what I want to do with Jenkins...

Any idea how to fix this issue?

Thanks

**Comment by DaceloNovaeguineae** [comment]
Here is solution: [https://github.com/fullcalendar/fullcalendar/issues/3991](https://github.com/fullcalendar/fullcalendar/issues/3991)

**Comment by arshaw** [comment]
yes, i've made a reminder to myself on that other ticket to update the docs

**Comment by davidkarlsson** [comment]
I get the following errors in dist/fullcalendar.d.ts with 3.8.0:
`(283,26): Parameter 'ev' implicitly has an 'any' type.`
`(284,29): Parameter 'ev' implicitly has an 'any' type.`

The problem is that `handleScrollProxy: (ev) => void` and `handleTouchMoveProxy: (ev) => void` doesn't define a type for the ev parameter like the other functions do which gets reported as an error if you have noImplicitAny set to true and skipLibCheck set to false.

**Comment by newradius** [comment]
@davidkarlsson I have the same issue, this shouldn't be colosed.

**Comment by sudosandwich3** [comment]
@arshaw I'm experiencing the same issue as @davidkarlsson . The parameters need types.

**Comment by lupari** [comment]
fullcalendar 3.8.0 fullcalendar.d.ts: 

TS (2.6.2) compiler giving me errors because of wrong indexer type in this interface:
```
export interface ButtonTextCompoundInput {
		prev?: string;
		next?: string;
		prevYear?: string;
		nextYear?: string;
		today?: string;
		month?: string;
		week?: string;
		day?: string;
		[viewId: string]: string;
	}
```
 
```
file: 'node_modules/fullcalendar/dist/fullcalendar.d.ts'
severity: 'Error'
message: 'Property 'prev' of type 'string | undefined' is not assignable to string index type 'string'.'
at: '1429,3'
source: 'ts'
code: '2411'
```

Given that the properties may be absent should the indexer have type string | undefined instead of string, i.e. "[viewId: string]: string | undefined" ?

**Comment by eckstaedt** [comment]
@lupari 
Getting the same error also with version 3.8.1.

**Comment by arshaw** [comment]
@lupari @eckstaedt , yes, i'm seeing this problem as well. 

please follow #4035 for this

its fixed in master and released
