### ISSUE TITLE
ghost click on touch devices

### ISSUE THREAD

**Issue by Brandinga** [fullcalendar/fullcalendar#3895]
We want to open a popup on dayclick. This works fine on non-touch devices.

On touch devices the popup opens, but instantly closes, because a click event is fired which should not.
If you make a longpress touch gesture, all works correct. So the problem only occur on a short tap.

You can see this problem here: https://codepen.io/anon/pen/RLzOWG

how can we avoid this "ghost" click on touch devices?

Thank you.
Christoph

**Comment by AndersBachLarsen** [comment]
I have the same problem.

**Comment by AndersBachLarsen** [comment]
If I drag a selection there is no "Ghost click"

**Comment by Brandinga** [comment]
in our codepen example, we added the "popup" functionality also to the eventClick handler, there it works correct

currently we only have "ghost" clicks on a dayClick handler

**Comment by arshaw** [comment]
I've recreated this problem but the issue lies on the browser-level and I'm afraid it will be difficult for fullcalendar to deal with it.

touch browsers fire artificial mouse events (like mouse click) after a touch event, on a delay.
this article does a good job of explaining it:
https://www.creativebloq.com/javascript/make-your-site-work-touch-devices-51411644

It must be that after the delay, the artificial mouse click is being fired and the browser is making whatever is underneath the touch coordinates at the time of the delay the click "target".

My suggestion is to do something like what they suggested in the article. DON'T call a `.preventDefault` because it will cause side effects, but DO ignore the mouse click event if you know a touch end event happened really recently.

**Comment by Brandinga** [comment]
@arshaw 
Thank you for clarification.

I'm intensiv tried out some solutions the last days.

I come up to simple use an debounce. [debounce events](https://stackoverflow.com/a/40043385)
also mentioned here: [setTimeout](https://stackoverflow.com/a/7019461)

**BUT:**
**this causes a delay on scrolling** --> scrolling starts after debounce time --> better than ghostclicks but not very smooth.

Also interesting: its only a problem on ChromeMobile, Safari on IOs handles this smoothly without flickering or waiting on debounce delay before start scrolling.

Would be nice, if you keep this in mind, and find a better solution (for Example: a version thats only binds on touchevents?)

Christoph

**Comment by Brandinga** [comment]
the scrolling delay comes from my hammerjs implementation...

if i change the order how i bind the swipe gesture, then the delay is gone:
must be first grid-container, then widget header

`const fcContent = jQuery('.fc-time-grid-container');

        fcContent.hammer().on("swipeleft", function (event) {

            const action: ProducedAction = { action: event, type: actionType.swipe }
            swipeSubject.next(action);

        });

        fcContent.hammer().on("swiperight", function (event) {

            const action: ProducedAction = { action: event, type: actionType.swipe }
            swipeSubject.next(action);

        });

        const fcHeader = jQuery('.fc-widget-header');

        fcHeader.hammer().on("swipeleft", function (event) {

            const action: ProducedAction = { action: event, type: actionType.swipe }
            swipeSubject.next(action);

        });

        fcHeader.hammer().on("swiperight", function (event) {

            const action: ProducedAction = { action: event, type: actionType.swipe }
            swipeSubject.next(action);

        });`

**Comment by arshaw** [comment]
@Brandinga , thanks, I'm going to start looking at hammerjs for fullcalendar v4. internally it uses `touch-action` i believe to achieve this
