### ISSUE TITLE
className for day-of-week header of week/month view

### ISSUE THREAD

**Issue by jasonsavard** [fullcalendar/fullcalendar#3919]
The week view has the class fc-today to the th tag to target the current day of the week.
But the month view does not add this class, can this be added?

![image](https://user-images.githubusercontent.com/1268278/32557326-d2a9c8de-c46f-11e7-9b2d-a10531a1d0cd.png)

**Comment by arshaw** [comment]
if the today date was on the second row of days, would you also expect the `th` to have the className?

**Comment by jasonsavard** [comment]
Yes.
ps. thanks for all the wonderful work you're doing on this project.

**Comment by arshaw** [comment]
hmm ok. i can see why someone would want a classname for this, tho not sure i want it to be `fc-today` since it might be a bit disconnected. maybe `fc-current-day-of-week` or something

**Comment by arshaw** [comment]
I feel that the day-of-week header in a multi-week view should not have a 'today' class because it is not explicitly linked to that day but rather shared across multiple weeks.

However, you can inject whatever classes you want with the new day-header render hooks in v5:
https://fullcalendar.io/docs/day-header-render-hooks
