### ISSUE TITLE
Multiday events in Google Calendar cause TypeError: r[(e + 1)] is undefined

### ISSUE THREAD

**Issue by newkind** [fullcalendar/fullcalendar#3925]
First of all let me apologise for not pasting JSFiddle. I wanted to prepare one but I'm not sure why it wouldn't fetch the events from Google Calendar making it useless.

The issue itself is about the JS error that appears when you try to view a week with multi-day event from Google Calendar in the `listWeek` view.

`TypeError: r[(e + 1)] is undefined`

This is a sample event configured in the Google Calendar : 

![Event](https://monosnap.com/file/p6gQsbcOa0g9mcXwDOYVczd6sIZwz3.png)

You can see the issue live here on webiste : https://www.kubana.me/calendar
Simply jump to the week showing 11-17 Dez (December) and JS error will appear in your console.

**Comment by acerix** [comment]
I also get a JS error on Dec 11 view, but I get: `Uncaught TypeError: Cannot read property 'startMs' of undefined` and the origin is not obviouse.

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It sounds like your API key is not working for JSFiddle. Here's an example that might be a good starting point for your test, you can find other examples in the [issue history](https://github.com/fullcalendar/fullcalendar/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20google%20calendar%20).

https://codepen.io/dyhrdmet/pen/NaJqKR

**Comment by newkind** [comment]
I just tested the CodePen and yes my API worked in that one. But also I have found out that the FullCalendar script was an older version (3.5.1) and that the newest one 3.7.0 is working just fine!

I'm sorry for bugging you :)
