### ISSUE TITLE
unselectAuto = false not working  in version 3.7.0

### ISSUE THREAD

**Issue by korengal** [fullcalendar/fullcalendar#3966]
Hi,
the unselectAuto = false not working 

Fiddler : 
https://jsfiddle.net/korengal/fwdea0qk/2/

thanks.

**Comment by neroux** [comment]
It seems to work just as expected.

**Comment by korengal** [comment]
@neroux how?
its unselect my selection no meter where i click on the calendar.

**Comment by neroux** [comment]
Where are you clicking?

**Comment by acerix** [comment]
@korengal In your example, if I make a selection and click on December in the date (for example) it leaves the selection because `unselectAuto` is turned off.  If I click a timeslot, it clears the selection to replace it with the new one.

Please describe how you expect it to work differently, or what is working differently in the new version.

**Comment by korengal** [comment]
I need the selection to be canceled only if I press the same place again.

I need to implement for mobile devices the above logic:
one click on timeslot: mark the time slot  with + sign,
second click on the same timeslot:  will  open a popup for adding new event.


![image](https://user-images.githubusercontent.com/5110512/34179222-b9f1604a-e512-11e7-94db-12d85e5261a5.png)

**Comment by acerix** [comment]
It sounds like you could create the event in the [`select` callback](https://fullcalendar.io/docs/selection/select_callback/), then your popup would add more details to the event.

If this is a question, please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.
