### ISSUE TITLE
AgendaDay view column width

### ISSUE THREAD

**Issue by ugrincic** [fullcalendar/fullcalendar#3985]
Is it possible to set different column width for each resource?
Some columns contain many events in same time period while other contain no events or few of them. I want to manually resize each column width so the columns with many events take more width.

Example:
![calendar example](https://user-images.githubusercontent.com/34715113/34212424-8891b024-e59c-11e7-89f6-ed59c8047175.png)

**Comment by acerix** [comment]
You could use CSS to set the widths of the columns, but there is not built-in support, so it doesn't re-size the events automatically.

Since this is specific to the Scheduler, please open an issue there instead to request this as a new feature:

https://github.com/fullcalendar/fullcalendar-scheduler
