### ISSUE TITLE
slotDuration ruins events rendering

### ISSUE THREAD

**Issue by valon91** [fullcalendar/fullcalendar#3988]
Hello, I am using timelineMonth and timelineYear from scheduler full calendar, and in the timelineMonth view i set slotDuration:{weeks:1} and it works but events are not rendering properly, and when i remove the slotDuration events are back to normall, it is the same by timelineYear , please help

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by valon91** [comment]
https://jsfiddle.net/9470mtqm/ here you have my code

**Comment by valon91** [comment]
![ffffffffff](https://user-images.githubusercontent.com/9461249/34293413-069d69f4-e705-11e7-8c0d-9e2a2b71a80c.png)
this is how events look like

**Comment by valon91** [comment]
@acerix

**Comment by acerix** [comment]
Your example isn't working, seems libraries are missing so I pasted it in the codepen demo:

https://codepen.io/anon/pen/KZgOZK?editors=0010

It doesn't look like your screenshot though, and I don't see any issue with how the events are displayed which `slotDuration` is set.

Also, since this is specific to the Scheduler addon, please open the issue there instead if you still have an issue:

https://github.com/fullcalendar/fullcalendar-scheduler
