### ISSUE TITLE
clientEvents is empty on JSON feed

### ISSUE THREAD

**Issue by zertex** [fullcalendar/fullcalendar#3993]
`events: 'SOME_URL',
    dayRender: function(date, cell) { 
      console.log($('#calendar').fullCalendar('clientEvents'));
    }`

Why $('#calendar').fullCalendar('clientEvents') is empty on JSON feed?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I'm guessing that the events are not loaded before `dayRender` is called, you might want to use [eventAfterAllRender](https://fullcalendar.io/docs/event_rendering/eventAfterAllRender/) instead.
