### ISSUE TITLE
Error when using fullcalendar with BAT Drupal module

### ISSUE THREAD

**Issue by Moranbzh** [fullcalendar/fullcalendar#3998]
Hello, 

I have a JS error by using fullcalendar within BAT Drupal 7.x module. I have installed fullcalendar-3.6.2 and fullcalendar-scheduler-1.9.1. When I tried to display the View Event Data in Drupal, nothing is displayed and I have the following error :

`TypeError: spec.class is not a constructor`

This error is raised in this part of **fullcalendar.js** file : 

`instantiateView: function(viewType) {var spec = this.getViewSpec(viewType);return new spec['class'](this, spec);},`

![erreur_fullcalendar](https://user-images.githubusercontent.com/25210066/34492407-b708976a-efe7-11e7-8b6a-225e7e46a7a3.png)

It seems that fullcalendar can't instantiate the view. I have printed the return value of this.getViewSpec(viewType) and it is FALSE.

I don't see from where comes this error, i have configured BAT module correctly and installed the right fullcalendar version.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

If the calendar works outside of BAT Drupal, you should ask them for support. 

I tested with jquery-migrate (from your screenshot) with latest versions and didn't get an error:

https://codepen.io/anon/pen/JMJmBb?editors=0010

**Comment by Moranbzh** [comment]
I tried why the verion **3.8.0** of fullcalendar and it works !
