### ISSUE TITLE
Incorrect date format  in query string for JSON events with agendaWeek/Day view.

### ISSUE THREAD

**Issue by RoelVR** [fullcalendar/fullcalendar#4004]
When using a JSON feed as event source together with either agendaWeek or agendaDay views, the requested URL is incorrect: the start and end dates include a time portion, whereas the documentation states they should be ISO8601 date strings (which implies no time portion should be present).

Affected versions: 3.5.0+

See minimal test case at https://jsfiddle.net/4vv1b3uo/2/
Please note that you will need to use Firebug/Inspector/... to verify the URL used by FullCalendar. Since the fiddle uses a static feed which the ignores query string, it is not visibly broken to the user.

**Comment by acerix** [comment]
Thanks for the report.  Makes sense that `agendaWeek` and `agendaDay` should make the same JSON requests as `basicWeek` and `basicDay`, ie. without the time.

For example:

`/events/?start=2018-01-28&end=2018-03-11&_=1515449990064`

instead of:

`/events/?start=2018-01-28T00%3A00%3A00&end=2018-03-11T00%3A00%3A00&_=1515450000029`

There's a related issue for better documentation of JSON format:

https://github.com/fullcalendar/fullcalendar/issues/1042

**Comment by arshaw** [comment]
this was fixed in v4.

look at https://fullcalendar.io/docs/upgrading-from-v3
and search for the text "Would previously generate strings like" ...
