### ISSUE TITLE
Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined

### ISSUE THREAD

**Issue by abdulmanan7** [fullcalendar/fullcalendar#4010]
### Bug Reports
I added fr.js for my locale setup but when the calendar runs it gives error
`Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tested with fr.js as [specified in the docs](https://fullcalendar.io/docs/text/locale/), and it works properly:

https://codepen.io/anon/pen/vpjrLd?editors=0010
