### ISSUE TITLE
DayGridEventRenderer resizing from end, allowing resize on non-allDay or showing starting time on long-spanning(allDay) events

### ISSUE THREAD

**Issue by lukgri** [fullcalendar/fullcalendar#4015]
Hey, in the DayGridEventRenderer.prototype.fgSegHtml function, there is a isResizableFromEnd variable, which includes these conditions: 
`!disableResizing && isAllDay && seg.isEnd && view.isEventDefResizableFromEnd(eventDef) `
the isAllDay variable, which is allDay attr of the event
`var isAllDay = seg.footprint.componentFootprint.isAllDay;`
denies resizing of the event from end even if the event is 4 days long without the 'allDay' attribute - (i.e.: 15.1.2018 15:00 to 18.1.2018 15:00).

- obvious fix to this would be setting allDay attr of these events to true, and altough it solves one of my problems, it creates another one, which is hidden starting time of such event spanning across multiple days

Is there any way we could get either an 'option' to allow resizing of non-allDay events or to show the starting time of such long-spanning events (keeping the allDay logic) ?

**Comment by acerix** [comment]
If I understand, are you looking to be able to resize events which have start/end times (ie. not just dates) in the Month view?

Currently, they can be resized in other views like Week, where there is control over the time.  It's not obvious if stretching the event by 1 calendar day would always add 24 hours to the end time, or add one day to the end time to preserve the time of day (since some days are 23/25 hours with daylight savings changes).

Might be easier to keep the events as allDay and show the time another way. (eg. add it at the beginning of the title)

**Comment by lukgri** [comment]
yes, it would be great to have an option to keep the starting time no matter what allDay attr on event is (instead of adding it each time I put new events in)

**Comment by acerix** [comment]
To confirm, you are requesting an option for allDay events to show the start time in Month view?

**Comment by lukgri** [comment]
yes, that's exactly it, thanks for clearing it up

**Comment by pabrams** [comment]
I have the same requirement.  I don't understand why the "allDay" flag is used to control two different things:
1: whether to show time portion of events
2: whether to render in the 'allDay' slot

I need to be able to show the time portion of dates regardless of whether the event is rendered in the allDay slot.  The allDay slot would be useful to prevent long-running events from cluttering up my week/day views, if it weren't for the fact that setting allDay to true seems to prevent all time data from showing in the month view.  

Couldn't there be two different flags? Like 'allDaySlot' to put the event in the allday slot in weekly/daily views, and something like a 'hideTime' flag if people want to render a time of midnight instead of what is actually stored on the event.

**Comment by arshaw** [comment]
this is probably no longer an issue with the v5 codebase
