### ISSUE TITLE
Typescript definition file, with noImplicitAny, complains

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#4017]
from @davidkarlsson:

> I get the following errors in dist/fullcalendar.d.ts with 3.8.0:
> `(283,26): Parameter 'ev' implicitly has an 'any' type.`
> `(284,29): Parameter 'ev' implicitly has an 'any' type.`
>
> The problem is that `handleScrollProxy: (ev) => void` and `handleTouchMoveProxy: (ev) => void` doesn't define a type for the ev parameter like the other functions do which gets reported as an error if you have noImplicitAny set to true and skipLibCheck set to false.

**Comment by arshaw** [comment]
Question for @davidkarlsson @newradius @sudosandwich3 from #3889

FullCalendar source code and definitions file (which is derived from the source code) does not have types for every parameter, and has not yet been weened off of implicit-any. Eventually, yes, but in the meantime, I'm wondering if you could just use `skipLibCheck: false` ? What is the problem with that?

**Comment by davidkarlsson** [comment]
Thanks for working towards fixing the implicit any usage. It seems like you're close to resolving this already since the .d.ts file only had the two errors I reported in my previous comment?

The problem with setting `skipLibCheck: true` is that it affects all .d.ts files and we have a lot of definition files (both our own and 3rd party files) that we really want type checking for and FullCalendar is the only one that is forcing us to disable lib checks at the moment.

So I hope you'll consider compiling the .d.ts with the `--strict` flag in the future to cater to as many users of the library as possible.

**Comment by azampagl** [comment]
+1

**Comment by arshaw** [comment]
this is fixed in 3.8.1, and now there's linting for this

**Comment by arshaw** [comment]
this is fixed in core 3.8.1 / scheduler 1.9.2

did my own fix along w/ linting to prevent this from happening in the future
