### ISSUE TITLE
Last hour column width is crashing

### ISSUE THREAD

**Issue by tapan8** [fullcalendar/fullcalendar#4026]
I have updated my calendar from 3.1 to 3.8, 

1. After updating last hour column width in day or week view is not correct. 
Day time range - 6:00am - 11:30pm

Week View
![image](https://user-images.githubusercontent.com/29919706/35388583-620e1864-01fa-11e8-82e4-e88767735cec.png)

Day View
![image](https://user-images.githubusercontent.com/29919706/35388597-729cb000-01fa-11e8-8eac-7643dd213010.png)

2. I need to load calendar for schedule range 1st Dec 2017 - 31st March 2018, but need to get events for the selected week/day, on every prev or next the respected event should be loaded. How can I get the selected week/day value.

3. I need to print the whole calendar, is there any in built function which can print the calendar in the tabular format? After adding fullcalendar.print.min.css application breaks, Please suggest

Thanks
Tapan

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for questions.

To load events automatically on prev/next time range, you can supply [events as JSON](https://fullcalendar.io/docs/event_data/events_json_feed/).

"fullcalendar.print.min.css" should be specified with media="print" so it only effects the print version.

**Comment by tapan8** [comment]
Hi,

Thanks, for the quick response.  All below issues are coming after updating the calendar version from 3.1 to 3.8

1. I am not able to get what do you mean by runnable, stripped-down demo, i am attaching my calendar.cshtml for your reference (licese id removed)
[Calendar.zip](https://github.com/fullcalendar/fullcalendar/files/1673825/Calendar.zip)

2. I am able to get the events for the particular date range. Thanks for the help

3. Calendar is still not printing.

4. While I am doing search on the classrooms, it search just for the classroom but didn't refreshes the calendar grid, what is that i am missing and it also removes the heading of calendar and removes the grid lines of calendar

$("#myInput").on("keyup", function () {
                    var value = $(this).val().toLowerCase();
                    $(".fc-body .fc-time-area tr").hide()
                    $(".fc-resource-area tr").filter(function (i, v) {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        if (($(this).text().toLowerCase().indexOf(value) > -1) == true)
                        {
                            var res = $(this).attr("data-resource-id");
                            $("[data-resource-id="+res+"]").show()
                        }
                    });
                });

5. One more issue that i am getting is when i switch the views, calendar crash
      1. load as day
      2. change to week
      3. move next week
      4. next day
     5. select week
     6. calendar crashes
number of classrooms = 80
number of courses = 310
json attached = 
[result.json.txt](https://github.com/fullcalendar/fullcalendar/files/1673850/result.json.txt)

![image](https://user-images.githubusercontent.com/29919706/35514556-93418468-052c-11e8-86c2-cecd122ed4ca.png)

**Comment by acerix** [comment]
1. It helps if you can provide an example that we can run to see your issue.  I can't easily test that cshtml file because it has server side variables so it needs to run on your server.  You should be able to copy the scripts from your output page and paste into a codepen like this to get a working demo:

https://codepen.io/acerix/pen/bLGKEB?editors=0010

3. Take a look at the [basic demo](https://fullcalendar.io/js/fullcalendar-3.8.1/demos/basic-views.html) which has print styles.  Maybe you have other print CSS which is interfering.

4. Are you trying to search the resource titles for some text, and hide all the resources that don't match? Might work better to get the list of resources with [getResources](https://fullcalendar.io/docs/resource_data/getResources/). It would help if you can demonstrate the issue in codepen.

5. Do you get any error message in the console when it crashes? Again, helps if you can send a runnable demo, and please open separate issues for problems that are not related.

**Comment by tapan8** [comment]
1. Not able to generate the runnable demo for this issue.

2. Closed

3. Attached report html and printed report.pdf and all the css I have used. Issue how can i get the header and gridlines for hours
[Print Report.zip](https://github.com/fullcalendar/fullcalendar/files/1677983/Print.Report.zip)

4. Demo for classroom search https://codepen.io/tapan8/pen/QQWeEL 
    change view to week and than to day 
    grid lines come after every 30 min, but after search for classroom grid lines for 30 min gets clear, and it also searches on the classroom heading

5. Not getting any client or server side error.

**Comment by acerix** [comment]
3. It looks like your CSS in Site.css needs to be updated for new version, although the print 

4. The issue is searching for any child `tr`, here's a quick fix to only find resource rows:

https://codepen.io/acerix/pen/jZEvEo?editors=0010

5. By "crashing", do you mean it disappears like in your screenshot? It might help to turn off your CSS and inspect the DOM to see if the calendar HTML is still there.

**Comment by tapan8** [comment]
1. Space is still appearing at the end only if calendar is ending at xx:30 min

3. I have updated all js and css and print is still crashing, I have attached all js and css files with html and report output. 
After updating now I getting the issue when select the week, the date gets crashed and start and end date values are not set for 

events: function (start, end, timezone, callback) {     }

[report3.8.zip](https://github.com/fullcalendar/fullcalendar/files/1681901/report3.8.zip)

4. Thanks, it fixed the search 

5. Nothing is crashing it just giving the same attached output.

**Comment by acerix** [comment]
I can't tell what you issue is from your output, you need to isolate the issues on your side:

https://fullcalendar.io/wiki/Reduced-Test-Cases/

**Comment by SheikoSN** [comment]
Hi guys!
I found an example of this bug in official example.
https://fullcalendar.io/docs/timeline-standard-view-demo

[http://joxi.ru/l2ZOl0oUwYkBoA](url)

**Comment by acerix** [comment]
Thanks for the example, but for me it looks good in Chrome or Firefox.  Which OS are you using?

**Comment by SheikoSN** [comment]
I use Windows 10. On Ubuntu everything looks ok.

**Comment by acerix** [comment]
I just tested in Windows 10 and 8 and can't reproduce the issue.  Did you try turning off browser addons?

**Comment by xNaii** [comment]
What he ment was this look at nr. 23
![bug1](https://user-images.githubusercontent.com/22669597/54345905-ad45c380-464c-11e9-9353-d1916654c1c5.png)

and how to get table look like this ? as I need all week in one page
![bug2](https://user-images.githubusercontent.com/22669597/54345947-c189c080-464c-11e9-865d-798fe657d9d1.jpg)
