### ISSUE TITLE
Dual View ( Normal event view + Resources Vertical View )

### ISSUE THREAD

**Issue by MiguelQueiroz** [fullcalendar/fullcalendar#4036]
In the agendaDay view, i would like to see for example Monday. And having events that have resouces, to be shown on the right side.

This can be done with the resources vertical view, but doing so, will hide the normal events? 

For example event 1, uses resources A and B.  And then i have event 2 that does not uses resources.
But i want to be able to see the event B on the calendar, although it was no "event" of the corresponding resource on the right columns ( resource columns).

For me this is hard to solve, because i have to make "agents" a resource too, so i can assign an appointment to an Agent, and sometimes a resource.  But doing so, allow the resouce as an agent column to be dragged to the "real resource" column, and that cannot happen because  all events should have an agent assigned to it.

The eventAllow does not let me specify which "event" instance im clicking, since the draggedEvent is all the same info. With disallows me to do something like ( if this is the main event, return false if the dropped location is a "real resouce" but can drop on "agent as resources")

Not sure if i was clear.

also doing the resources array equal to:

  resources.push({ id: "3108", title: 'Agent1' , eventClassName:"EventIsNotResource" });

the eventClassName is empty, not passed to the draggedEvent information , which makes worse to define the dragging event instance.

**Comment by acerix** [comment]
It would help if you can provide a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/). I made this example to better understand:

https://codepen.io/acerix/pen/ddyKBM?editors=0010

Since events without any resource do not appear in the vertical resource view, you could either make a dummy resource (like "none" in my example) for them, or you could display those events outside the calendar, and follow [dropping external elements](https://fullcalendar.io/docs/dropping/) for dropping them to a resource.

I used `eventAllow` to make event 5 so it can only be dropped on the Agent resource.  I did the same for event 1, but it doesn't seem to work for events with more than one resource. Is that the issue you are facing?

**Comment by MiguelQueiroz** [comment]
Yea thats the issue, when there are multiple resources, it does not work.
Because the variable resourcesId is null. But when there is only one it is
filled. I found it strange because the allowEvent appears to have different
behavior. The allowEvent would be useful to make an event assigned always
to an agent resource, nut never allow to drop to a real resource column,
since that would wipe the agent of the event.  Also resources events should
not cross to the agents resources. ( Would be easy with an indexOf check on
agent id array vs real resource array).

Also i think it would be nice to have the events instances that are clones
(when multiple  resources) have a way to identify which event is the
master? In this case an event having a resource id that would match the
agent is list.

**Comment by acerix** [comment]
In my example, `resourceId` always has a value, when are you seeing it null? If you mean the event, it is null when there is more than one resource (in `resourceIds`).

Since the issue with multiple resources is specific to the scheduler, I created an issue in that repo instead:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/412
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

I'm not sure what you feature you are looking for to handle different types of resource.  You could maybe use nested resources for that, ie. one parent is Agent Resources and another Event Resources and you would check the parent in `allowEvent`.

`eventAllow` is called twice when dragging an event with 2 resources, so are you looking to know in that callback which resource it is being dragged from?

**Comment by MiguelQueiroz** [comment]
Well thanks, about the last part yes, the event does not tell directly
which event is being dragged, so i cannot tell it this logic (if the event
im dragging is an agent resource then do not allow to drop on event
resource) or the opposite i dont want to drag event resources to an agent
column resource. The thing with the nested resource is that i dont want to
show the parent on the column only their children
