### ISSUE TITLE
EventObject and ViewObject no longer Types

### ISSUE THREAD

**Issue by pabrams** [fullcalendar/fullcalendar#4067]
I'm trying to upgrade from 3.6.2 to 3.8.2, but I get a bunch of compiler errors, including TS2694 'missing exported members' such as ViewObject and EventObject.

When I go and look in fullcalendar.d.ts, sure enough they are not there.  But if I downgrade back to 3.6.2 and add types/fullcalendar, I can see EventObject does exist in index.d.ts.

I looked at https://fullcalendar.io/docs/event_data/Event_Object/ and it doesn't say it's deprecated or anything.

I was about to say this seems similar to #4006, but OptionsInput at least still exists as a type, whereas ViewObject and EventObject are completely missing.  It looks like someone has gone and done some major refactoring.  Is it just that the documentation has not been updated yet?

**Comment by pabrams** [comment]
I'm having to change my code in various ways:

- fullcalendar.EventObject becomes EventObjectInput
- fullcalendar.ViewObject becomes 'Default' from 'fullcalendar/View'
- fullcalendar.Options becomes 'OptionsInput' from 'fullcalendar/src/types/input-types'
- fullCalendar("getDate") now returns a Moment, so have to add .getDate()

**Comment by acerix** [comment]
It looks like those types getting renamed could be from refactoring, but typescript wasn't added until version 3.7 and I had a quick look and didn't see the old names you mentioned in 3.6.2:

https://github.com/fullcalendar/fullcalendar/tree/v3.6.2/src

Also don't see when the return value of `getDate` was changed since, looks the same as in 3.6.2 (returning a moment).

It makes sense that changes to the API should be documented, I just don't see when those changes were made.  Did you maybe added the typescript stuff to 3.6.2 yourself?

**Comment by pabrams** [comment]
Sorry, I guess I should have mentioned I was using @types/fullcalendar (3.5.1) with fullcalendar 3.6.2.  My understanding was that the types were moved into fullcalendar as of 3.7 or 3.8, and when I try to install @types/fullcalendar with fullcalendar 3.8.2 I get a warning that @types/fullcalendar is deprecated because it is now included in fullcalendar, except that the types are not the same.

https://www.npmjs.com/package/@types/fullcalendar

**Comment by acerix** [comment]
I don't believe that was released by FullCalendar, which would explain why it's not compatible with the type files that were added since then.  So, not really a breaking change or anything to document.
