### ISSUE TITLE
Click Title for Today?

### ISSUE THREAD

**Issue by syberknight** [fullcalendar/fullcalendar#4070]
hello. first of all, this is a fantastic script. thank you!

i'm wondering if i can make the "Title" (in Month view, the month year at top of cal) be a link that acts like the "Today" button, taking the user to the current date.

hoping to have the "Prev" on the "Left" and the "Next" on the "Right" with the "Title" in the middle, that not only shows which month/year is in view but also when clicked will take the user to "Today" if not on today.

does that make sense?
thanks!

**Comment by acerix** [comment]
There is no built-in way to make the title a link, but you could select it's h2 like this to add that functionality:

https://codepen.io/anon/pen/VQxJNW?editors=0010

Another option is to make a custom button, instead of using the built-in title:

https://fullcalendar.io/docs/display/customButtons/

**Comment by syberknight** [comment]
THANK!!!

**Comment by acerix** [comment]
customButtons is better since it is built-in, but you would need to change the text/style to make it look like the title does.  You can use the same method to jump to the current day: `$('#calendar').fullCalendar('today')`.

A problem with using a selector on the h2 is that your code might break if the html is changed after an update. There is an open issue to address that:

https://github.com/fullcalendar/fullcalendar/issues/4028
↑
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
