### ISSUE TITLE
can't change 'editable' on month View

### ISSUE THREAD

**Issue by daart** [fullcalendar/fullcalendar#4081]
Hello, I'm facing a problem with the latest fullcalendar v.3.8.2. We've used v3.4.0 in our project, but recently I've got a task to add some HTML content to columnHeader. I've found out that there was a new feature called columnHeaderHtml, so I've included a new version to the project to test. It turned out that It's impossible to change editable for the month view, like in v3.4.0. Here is codepen for the issue 
https://codepen.io/anon/pen/eVPbow?editors=0010
Can somebody have a look ? Thanks in advance.

**Comment by acerix** [comment]
The `editable` setting is working as a view-specific setting, but if `editable` is set on the event, that setting takes precedence.  eg. Event 3 is not editable in month view here: https://codepen.io/anon/pen/xYmbwy?editors=0010

You need to call [updateEvent](https://fullcalendar.io/docs/event_data/updateEvent/) after making changes to an event but that can't be called in eventRender since it causes another render, so I suggest updating the events in `viewRender` instead:

https://codepen.io/anon/pen/jZXPOp?editors=0010
