### ISSUE TITLE
Dragging screen on iPhone using timeline

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar#4092]
When trying to drag the screen around or scroll the screen, touching within the timeline calendar grid sometimes moves the grid separate from the grid column and row headers.  This might make sense for a horizontally scrolling grid (i.e. to scroll through multiple days in a timeline), but it does not make sense when you are at the top of the grid or left side of the grid and it pulls white space into the grid instead of scrolling the screen.  Any suggestions for how to improve the usability on a phone with respect to this issue?

I am testing this on an iPhone SE using Safari.

**Comment by acerix** [comment]
I tested the [timeline resource view demo](https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.3/demos/simple.html) on Android/Chrome and the headers are always scrolling along with the calendar grid as I would expect.  I didn't see the issue you mentioned of pulling white space into the grid.

If you see the issue in that demo, please give the exact steps to recreate, otherwise please link to a demo that shows the issue or submit a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
