### ISSUE TITLE
Always dayClick event execute

### ISSUE THREAD

**Issue by patilharshal16** [fullcalendar/fullcalendar#4113]
I have added `eventClick` as well as `dayClick` on my calendar but every time `dayClick` events triggered even if I clicked on a particular event.

Ideally,  while clicking on any event on calendar then `eventClick` event should be triggered otherwise dayClick event should be triggered but I noticed if you add both events on the calendar then only dayClick event triggered every time.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Here's an example with both callbacks, dayClick fires when clicking a day, eventClick when clicking an event:

https://codepen.io/anon/pen/eMdBpz?editors=0011
