### ISSUE TITLE
[IE 11] Unable to get property 'clone' of undefined or null reference

### ISSUE THREAD

**Issue by MQTEnt** [fullcalendar/fullcalendar#4115]
Hello, I have a trouble with FullCalendar v3.9.0
When I use with Chrome it works fine, but when I use IE 11 this error occur
![console](https://user-images.githubusercontent.com/14356177/37576600-c9b01ace-2b5f-11e8-8dc8-5840bea23221.png)
and this is reference code with this error
![code](https://user-images.githubusercontent.com/14356177/37576613-d9ae29ca-2b5f-11e8-9626-0299f4c9913c.png)

Here is difference when I use Chrome and IE 11

> ![chrome](https://user-images.githubusercontent.com/14356177/37576780-8cda8fa2-2b60-11e8-9667-fa84c7d0a9f8.png)

> ![ie](https://user-images.githubusercontent.com/14356177/37576782-8eb73b9a-2b60-11e8-9892-65b3f0657c01.png)

And here is my JavaScript code
![myjs](https://user-images.githubusercontent.com/14356177/37576671-0767bca0-2b60-11e8-9cfc-841d5b468b0e.png)

I'm looking forward your answers
Thanks.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I can't test IE 11 at the moment, but your example gives me an error in Firefox because the date is not is ISO 8601 format, the month needs to be zero-padded eg. `2018-02`: 

https://codepen.io/acerix/pen/PRmjLv?&editors=001

**Comment by MQTEnt** [comment]
> Would you be able to post a runnable, stripped-down demonstration of the bug? Would really appreciate it because the time saved reproducing will be time spent fixing.
I can't test IE 11 at the moment, but your example gives me an error in Firefox because the date is not is ISO 8601 format, the month needs to be zero-padded eg. 2018-02:
https://codepen.io/acerix/pen/PRmjLv?&editors=001

Oh, I think we don't need to solve out more, the reason is absolutely the month needs to be zero-padded. It works fine on IE 11.
Thank you and have a nice day ^ ^
