### ISSUE TITLE
move jQuery and moment to peerDependencies

### ISSUE THREAD

**Issue by QuentinFchx** [fullcalendar/fullcalendar#4136]
Hi,

Currently, both jQuery and moment are set as `dependencies`. With current package managers, it might end up in having different versions of these libraries installed without any warning.
Would it be possible to set both of them as `peerDependencies`? Popular libraries and framework are [doing it](https://github.com/angular/angular/blob/master/packages/core/package.json)!

[Blog post](https://nodejs.org/en/blog/npm/peer-dependencies/), and [documentation](https://docs.npmjs.com/files/package.json#peerdependencies) just in case.

**Comment by cellvia** [comment]
seriously, these are some very heavy deps... please make them peer

**Comment by arshaw** [comment]
#4233 was merged. will release soon

**Comment by arshaw** [comment]
released in [3.10.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0)

i wanted to make this a major version bump since, but that would need to be 4.0.0, and since v4 has been so heavily advertised as the "[jquery removal / major overhaul next version](https://fullcalendar.io/docs/v4/release-notes)" i decided to make this a non-breaking semver number 3.10.0 instead. I hope this doesn't break the internet (fingers crossed).

# if you are having problems installing fullcalendar with NPM...

you need to install jquery and moment as peer depedencies:

```
npm install --save jquery moment
```

**Comment by zach446** [comment]
@arshaw Just wanted to let you know that because this was set as a minor release we spent a day trying to figure out why our application was needing a jquery dependency.  Making this a major release might have been a better choice here.
