### ISSUE TITLE
Custom timezone with unix milliseconds not working

### ISSUE THREAD

**Issue by Eseperio** [fullcalendar/fullcalendar#4180]
When using unix milliseconds timestamps as dates only `local` timezone works. Custom timezones are ignored. 

See https://jsfiddle.net/jk0mh2Lk/7/ (toggle comments on timezone)

**Comment by arshaw** [comment]
fullcalendar doesn't know every timezone, it's up to the provider of the start/end dates to give an ISO8601 date with the correct y/m/d/h/m/s values. ISO860 is preferred here. If given a timestamp, `1525730400000` is being converted to `2018-05-07T22:00:00` in UTC.

this is because fc doesn't have arbitrary tz support. see these issues if interested:
https://github.com/fullcalendar/fullcalendar/issues/3188
https://github.com/fullcalendar/fullcalendar/issues/2981

normal docs for timezones:
https://fullcalendar.io/docs/timezone

**Comment by Eseperio** [comment]
Ok, but i think that docs should reflect that `local` means that it will use the browser timezone **offset** . I spent a lot of time thinking that it will use the (string) name of the timezone when using local.
