### ISSUE TITLE
 How to solve this problem?

### ISSUE THREAD

**Issue by leobarussi** [fullcalendar/fullcalendar#4241]
Good afternoon, I'm having trouble implementing FullCalendar, could anyone help me? I shared a folder in my **Google Drive where the images are**. thanks in advance!

[](https://drive.google.com/open?id=1x-trdKC4OdilKpuh7KNpk-GtSsPQ-z3O)

**Comment by acerix** [comment]
If this is a question, please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.  If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/). 

I can't tell what the issue is from those screenshots, appears to be a server error.
