### ISSUE TITLE
Custom properties of event source objects inaccessible in event click handler

### ISSUE THREAD

**Issue by damangio** [fullcalendar/fullcalendar#4244]
I upgraded from FullCalendar 2.9.1 to 3.9.0 and encountered an issue. I've determined that the issue was introduced in v3.5.0.

I define the event sources with the events in the array format like the first example here: https://fullcalendar.io/docs/event-source-object. I also have a custom property on the event source object (called 'custom' in my example). In the event click handler, I access this property as `event.source.custom`. This works in FullCalendar 3.4 but in FullCalendar 3.5 the property is undefined, as demonstrated here: https://codepen.io/anon/pen/oMNGry, https://codepen.io/anon/pen/QBWqXj

I see this in the 3.5 release notes: "Event Objects obtained from clientEvents or various callbacks are no longer references to internally used objects. Rather, they are static object copies." I don't know if my issue is related to that. Can you recommend a workaround? Thanks.

**Comment by acerix** [comment]
While events can have custom properties, there is nothing mentioned in the docs about event sources having custom properties, so it may have worked before but I don't think that's supported. I don't believe it's related to the release note you mentioned.

As a workaround you can store the custom properties in an external array and look it up the source properties by the source ID. You could request custom source properties as a new feature.

**Comment by damangio** [comment]
I was able to get what I needed by using the event source's `id`.

Maybe this issue should be closed. Not sure what the criteria are for that.

**Comment by magicmb** [comment]
Interestingly I'm just contemplating raising an issue concerning the **event.source** property for events originating from an **eventSources** (Google Calendar in my case) which seems related to the above .

I've posted a question on **stack overflow** about this which I'm still awaiting a response for, which is why I came here to search for similar issues and stumbled upon this now closed issue. 

The thing that bugs me is that fullcalendar docs says:

> **source** "Event Source Object. Automatically populated. A reference to the event source that this event came from."

Not sure what the protocol is or even if I should even be posting on "Closed" issues, but can be re-open this issue or should I raise a separate one?

[Event Object property “source” returns [object Object]](https://stackoverflow.com/questions/55188589/event-object-property-source-returns-object-object)
