### ISSUE TITLE
element appended with eventRender function can not response click event on agentweek view!

### ISSUE THREAD

**Issue by zhangsword** [fullcalendar/fullcalendar#4248]
### Bug Reports
Hi Dear
I found element appended with eventRender function can not response click event on agentweek view
but it can work well on month view.
I have a testcase at following url:
https://codepen.io/anon/pen/XBXYGw
Could you pls check what is wrong with this solution?
Thanks in advance.

**Comment by acerix** [comment]
Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.

The problem is that the `<span>` you are appending cannot be clicked on because it's not positioned of top, eg:

https://codepen.io/anon/pen/zLBZxr?editors=0010
