### ISSUE TITLE
Drop on AllDaySlot in AgendaView has date.hasTime() as true

### ISSUE THREAD

**Issue by RikEskes** [fullcalendar/fullcalendar#4263]
**Correct Behaviour**
When an element outside of the FullCalendar view is dropped on the allDaySlot in agendaView, the date parameter is not given a time. This ensures that the check for an ambiguously timed moment with date.hasTime() will always return 'false' when an element is dropped on an all day slot.

**Buggy Behaviour**
An element dropped from outside of the FullCalendar view on the allDaySlot in agendaView can never be checked whether it should be given the property allDay: true, the date parameter of the drop function of FullCalendar namely always returns a date _and_ a time. Therefore the check date.hasTime() always returns 'true'.

**Reproducing**
Codepen: https://codepen.io/anon/pen/yqKzzN

Drag the blue element with text 'Test event' onto the all day slot, and drop it in the slot. The console will return true, and the event will be placed at the correct date, but at 00:00 instead of in the all day slot

**Comment by acerix** [comment]
Thanks for the detailed report.  The docs specify that if an event is dropped on an all-day slot, the `date` should be ambiguously-timed, so `hasTime` should return `false`.

https://fullcalendar.io/docs/drop

**Comment by arshaw** [comment]
the reason this is happening is because of the `start` property you are assigning when you initialize the draggable with `$('.event').data({ ... })`. The date-string you are specifying is supposed to be a *time*, not a full date, so it's getting interpreted as `12:00:00`. v3 takes this into account when reporting the date in the `drop` callback and intentionally assigns a time.

v4 is different with this behavior. 

> If dropped on an all-day slot, the date property will always have a 00:00:00 time, regardless of the startTime in the event data, whereas previously the startTime would have been added.

https://fullcalendar.io/docs/v4/release-notes#event-dragging--resizing

I won't modify this behavior in v3, so I'll close this issue

**Comment by arshaw** [comment]
actually, ill keep this open so that i remember to adjust what it says about the `drop` callback in the v3 docs

**Comment by arshaw** [comment]
v4 works differently: https://fullcalendar.io/docs/eventDrop
