### ISSUE TITLE
Hidden event which hidden from previous day

### ISSUE THREAD

**Issue by PhuQuy** [fullcalendar/fullcalendar#4265]
Hi, I'm not sure how to fix it!
![image](https://user-images.githubusercontent.com/17820409/43561963-ca2b3ffc-9643-11e8-8e8c-2277e6a0e0ac.png)

I have 2 events from 28th to 30th. But it being hided from 28th and keep hiding on 29th and 30th. How can i show these events on 29th and 30th?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I'm not sure what the issue is, but the events might be hidden from the 29 if they end before 9 am on that day, see https://fullcalendar.io/docs/nextDayThreshold .
