### ISSUE TITLE
Restrict date range

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#429]
Originally reported on Google Code with ID 158

```
Is there a way to restrict the viewable dates, i.e. next 2 years only?
```

Reported by `naterowe82` on 2009-10-30 15:12:56

Imported with **31** stars.

**Comment by arca223** [comment]
Hi arshaw !

Any news about this to be released ?
Is it going to be only the navigation restricted or also a way to disable click if the date range < whole month or whole week ?

Something interesting would be to disable cells not in the range, and disable the prev/next when reaching the edges. If event is on 2 weeks, you got the navigation up

![fullcalendarft](https://cloud.githubusercontent.com/assets/9930499/14598571/30483a26-0553-11e6-879c-a5ffabed14d1.png)

I hope it was the right place to post, I don't know if I had to remake an issue since you'd merge it here

Thanks for your help. (PS : sry for the picture fastly made on paint)

**Comment by arshaw** [comment]
Released in **v3.3.0**
Blog post: https://fullcalendar.io/blog/2017/03/fullcalendar-33-and-scheduler-16/

[validRange](https://fullcalendar.io/docs/current_date/validRange/)

**Comment by Bridgeway** [comment]
How do you set the range when the architecture is as follows:

this.eventFingerprint = function (e) {
                if (!e._id) {
                    e._id = eventSerialId++;
                }

                var extraSignature = extraEventSignature({
                    event : e
                }) || '';
                var start = moment.isMoment(e.start) ? e.start.unix() : (e.start ? moment(e.start).unix() : '');
                var end = moment.isMoment(e.end) ? e.end.unix() : (e.end ? moment(e.end).unix() : '');

                // This extracts all the information we need from the event. http://jsperf.com/angular-calendar-events-fingerprint/3
                return [e._id, e.id || '', e.title || '', e.url || '', start, end, e.allDay || '', e.className || '', extraSignature].join('');
            };

**Comment by acerix** [comment]
@Bridgeway Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.  If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
