### ISSUE TITLE
Recurring Event not showing correctly

### ISSUE THREAD

**Issue by mbilal9263** [fullcalendar/fullcalendar#4304]
### Bug Reports
![res](https://user-images.githubusercontent.com/35962473/44838828-a1695580-ac56-11e8-8d33-f9941413398b.png)

### Event JSON
"{"title":"in night","color":"#02b86e","id":2,"textColor":"#ffffff","start":"22:45:00","end":"23:45:00","recurring":true,"frequency":"daily","dow":[0,1,2,3,4,5,6],"ranges":[{"start":"2018-08-30T18:59:59.999Z","end":"2018-08-30T18:59:59.999Z"},{"start":"2018-09-20T17:45:00.000Z","end":"2018-09-27T13:59:59.000Z"}]}"

I want to create recurring event start from 20-Aug-2018 to 27-Sep-2018 But it did not render event on last day I mean on 27-Sep.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by mbilal9263** [comment]
https://codepen.io/mbilal92/pen/pONwEG

**Comment by acerix** [comment]
The events are not rendering because of `eventRender` returning `false`, there is no `ranges` property of events built-in.

You can add a repeating event by adding one event for each time range and giving them the same ID:

https://fullcalendar.io/docs/event-object

For questions, please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.
