### ISSUE TITLE
[v4-alpha.2] updateEvents for v4

### ISSUE THREAD

**Issue by bob76828** [fullcalendar/fullcalendar#4343]
Since the updateEvents function is removed from v4 so how do i batch update events?

**Comment by acerix** [comment]
If this is a question, please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.  If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

https://fullcalendar.io/docs/v4/Calendar-batchRendering

**Comment by dwhyte4** [comment]
I had a look at the examples though, i am still at loss on how i can implement update event with fullcalendar. I want it to update to database. Do you have any relevant link I could use

**Comment by lorinkoz** [comment]
Sorry to ask on this thread, @acerix. Is there any way to update a fullcalendar event with a server fresh event (which would require event parsing first) without using `setProp` or any variant of `setX`, and without removing the event and then adding it again?

Rationale: When I move an appointment, or edit it, I receive from the server an unparsed event (in the server format) where many props may have changed apart from the `(start, end)`. This event would require a run of `eventDataTransform` and then a parsing, and then I just want to replace the event I might have already in the calendar. I can't use any specific `setX` utilities on the existing event because I would have to do hacky work between regular fullcalendar props and extended props. I am currently removing it from the calendar, then adding it again (because that's the only way to get event parsing again), all of that within a batch. It seems not nice from an API perspective.
