### ISSUE TITLE
Add slidetoggle on click of event in day list view

### ISSUE THREAD

**Issue by mahi007rocks** [fullcalendar/fullcalendar#4434]
Hello guys, is there any way to add slide-toggle or collapsible to any event in day list view on clicking of any event?
Where this slide contains info about that Event.

**Comment by acerix** [comment]
It should work if you use it like in the docs:

http://api.jquery.com/slidetoggle/

If it doesn't work, it's best if you can provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by mahi007rocks** [comment]
surely, i will update on it soon
