### ISSUE TITLE
[alpha2] Print version of agenda view is missing borders, time column and events are not positioned at the correct time

### ISSUE THREAD

**Issue by bbalet** [fullcalendar/fullcalendar#4437]
If you compare the printed calendars of alpha 1 and 3, you will notice that their relative heights are inconsistent (see screenshots below):

- alpha1: https://codepen.io/bbalet/pen/EGbwaY
- alpha2: https://codepen.io/bbalet/pen/jXZvqW
- alpha3: https://codepen.io/bbalet/pen/BvmwaJ

The grid lines in the background have disappeared as well. 
In https://github.com/fullcalendar/fullcalendar/issues/3594 you mentioned that you've included a media query into the main CSS file but it looks broken since alpha2.

**alpha1**
![fullcalendar_alpha1](https://user-images.githubusercontent.com/1221546/50672331-015b7880-100a-11e9-92b5-58ddaf8d5541.png)

**alpha2 / alpha3**
![fullcalendar_alpha3](https://user-images.githubusercontent.com/1221546/50672336-05879600-100a-11e9-9d32-d409107bd17a.png)

**Comment by acerix** [comment]
Thanks for the report, it does appear some print styles are missing since alpha2.

https://codepen.io/anon/pen/dwKyVM?editors=0010

**Comment by bbalet** [comment]
This bug is still present in beta.
Cannot find a workaround so far (adding print.css from previous version doesn't solve the issue).

**Comment by arshaw** [comment]
@bbalet, believe it or not, the removal of the horizontal lines in the timegrid views is actually a *feature*. It was present in v3 (try print-preview in [this demo](https://fullcalendar.io/releases/fullcalendar/3.10.0/demos/agenda-views.html)). In v3, the fullcalendar.print.css stylesheet did the work of removing the lines. You probably didn't include the fullcalendar.print.css stylesheet on your page when you were using the alpha versions, however, as of the first beta version, the CSS that is responsible for the removal of the lines has been baked into the `core/main.css` file. That's why you're seeing it now.

If you want to undo this behavior, the best workaround is to use your own `main.css` instead of the built-in one. Remove the part of the CSS that is wrapped in `@media print`

PS- it's considered a "feature" because browsers had a tough time doing absolute positioning of the events overtopof the grid lines, especially with page breaks. it was better just to make them stack and have the time text communicate when an event occurs.
