### ISSUE TITLE
Clear selection when selectable is changed to false with unselectAuto=false

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4449]
### Bug Reports
Instructions are in the demo:
https://codepen.io/frlinw/pen/YdRROd

I just wonder if it makes sense to still see a selection if the calendar is not selectable.

**Comment by acerix** [comment]
You can unselect with `calendar.unselect()`:

https://codepen.io/anon/pen/BvbZxq?editors=0010

**Comment by frlinw** [comment]
@acerix Of course, that's what I did. I just wanted to question the default behavior.

**Comment by acerix** [comment]
To me it seems better to not clear it by default, so setting `selectable=false` is "freezing" the current selection.  It's also easier to clear the selection manually then it would be to recreate the selection if it's automatically cleared.

**Comment by arshaw** [comment]
when disabling the `selectable` flag, it will prevent the user from selecting new periods of times, but it will not disable the selection functionality as a whole (for example, the `select()` method still works). since selecting is still possible, i wouldn't want to clear any existing selections. if disabling the `selectable` flag turned everything off, it'd be a different story
