### ISSUE TITLE
columnHeaderHtml can show the wrong date if not converted to UTC

### ISSUE THREAD

**Issue by ChuckFields** [fullcalendar/fullcalendar#4454]
The columnHeaderHtml parameter is one day prior to what it should be.

Reduced Test Case: [https://codepen.io/anon/pen/jXdOro](https://codepen.io/anon/pen/jXdOro)

![columnheaderhtml](https://user-images.githubusercontent.com/7934525/51122831-bea75680-17e8-11e9-99d9-b30325aa8b7b.png)

**Comment by ChuckFields** [comment]
This is probably related: [https://github.com/fullcalendar/fullcalendar/issues/4392](https://github.com/fullcalendar/fullcalendar/issues/4392)

**Comment by acerix** [comment]
Thanks for the demo.  I'm not sure it's a bug, but it seems to me that your first example _should_ display the correct date and the second one _should_ show the date in UTC, and it's not clear in the docs if converting to UTC _is_ needed in this case.

**Comment by syamdanda** [comment]
I got the same issue, when I use my local timestamp, got resolved after changing it to UTC

**Comment by HugzM** [comment]
After digging more I'm wondering if it's a defect . 
Like you're in local time let's say UTC-5 and you want to render the header for the day february 6th.
The internal date manipulated is february 6th 00:00 UTC which is feb 5th 7pm -5:00  so during the rendering the date to render is sent in local time as well ( february 5th 7pm ) starting there,  in your render callback the date object will be february 5th 19:00. The resason why this is working outside columnHeaderHtml ( native rendering) is because the code do date.getUTCDay() to convert it back from locale to UTC. On my perspective it's not a defect it's just an assumption when they determine the date to render they pick the current day in UTC

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released) This issue is fixed.
