### ISSUE TITLE
[beta 2] defineLocale is missing

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4493]
### Bug Reports
defineLocale is not present in Fullcalendar object:
![image](https://user-images.githubusercontent.com/11896237/52337471-01cfa080-2a08-11e9-8e65-688bd8806096.png)

**Comment by frlinw** [comment]
It's possible to pass an object to the `local` property but it requires a `code` property to work.
- replace `code` by `id` could be more generic
- doc could be more clear about this case

**Comment by acerix** [comment]
I'm not sure where "defineLocale" is from, do you mean in momentjs?

Here are the new docs for setting the locale:

https://fullcalendar.io/docs/v4/locale

https://fullcalendar.io/docs/v4/release-notes#locales

**Comment by frlinw** [comment]
`defineLocale` was a static function until v4.0.0-alpha.4 but does not exist in beta.2
https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha.4/dist/fullcalendar.js#L5777
But maybe it wasn't a part of the public API

**Comment by acerix** [comment]
It seems that was part of Moment.js which was removed:

https://github.com/fullcalendar/fullcalendar/issues/3471

**Comment by arshaw** [comment]
nah, `defineLocale` was something version of fullcalendar prior to the recent alpha exposed so that locales could register themselves.

the way locales register themselves is different in beta.2

you are probably using old locale files with the newest version. us the locales files in `@fullcalendar/core/locales` instead, or use `@fullcalendar/core/locales-all`

**Comment by frlinw** [comment]
I defined my own local manually using `defineLocale`. I fixed it but as I said in my second comment, changelog could be a bit more explicit about this removal
