### ISSUE TITLE
[4.0.0-beta.4] [feature request] resourcesRender callback

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4509]
### Feature Requests
Ability to do something once all resources have been rendered

**Comment by acerix** [comment]
To confirm, you are looking for a callback that happens after all resources have been rendered, but before the events have been rendered?

**Comment by nicegamer7** [comment]
I could use a callback when all events are rendered. It would be very much appreciated.

**Comment by Erika31** [comment]
I agree, it could be very useful to be able to specify a callback function as argument to the following methods :

- Calendar::refetchEvents
- Calendar::refetchResources

**AND**

To be able to specify global callback options :

- eventAfterAllRender (like the ones that exists on V3)
- resourceAfterAllRender

Currently, in V4, I did not find how to cleanly emulate these behaviours...

**Comment by arshaw** [comment]
having `refetchEvents` and `refetchResources` return promises might be useful. @acerix is there an existing feature request like this?

I took `eventAfterAllRender` out because it was a bad design pattern, and won't work with on-demand rendered events when that's implemented. Could you please explain your usecase more? @acerix can you vet?

**Comment by nicegamer7** [comment]
I wanted to use `eventAfterAllRender` to manipulate the list view scroller, because in our webpage the list view is too large for mobile browsers.

So I was using `eventAfterAllRender` to scale the scroller down after all the events had been rendered. Maybe there's a better way to Schreiber this though...

**Comment by arshaw** [comment]
@nicegamer7 , why not use FC's height settings? Set the `height` dynamically?

**Comment by nicegamer7** [comment]
Sorry, I should have been more clear. The width is the issue, not the height

**Comment by arshaw** [comment]
the width is normally related to the height because it is computed with aspectRatio. try setting height to auto and then setting the width of the div to whatever you want.
