### ISSUE TITLE
[beta4] Next/prev does not increment by dateIncrement when there is a visibleRange set

### ISSUE THREAD

**Issue by curiousily** [fullcalendar/fullcalendar#4517]
Reproduction:

https://codepen.io/anon/pen/yZxZKp

I want to create a custom 3-day view where yesterday is the first visible date and tomorrow is the last visible date.

When I start going forward (> button) everything seems fine but after starting to go back (< button) I cannot go to the correct visible date range.

Thanks!

**Comment by arshaw** [comment]
@acerix  can you remember to add the v4 milestone to issues like this?

**Comment by arshaw** [comment]
errrr, maybe this was present in v3 as well. can someone try to make a recreation v3 in order let us know if this is a regression or not?

**Comment by acerix** [comment]
Will do, works as expected in v3

https://codepen.io/anon/pen/RdpzBP?&editable=true&editors=001

**Comment by arshaw** [comment]
I just pushed a commit that prevents things from dying as bad as they are now, but it is still the responsibility of the developer to return a whole-day range from a `visibleRange` function. Right now, you are receiving the current date, which has a time part (like `12:00:00`) and then subtracting/adding days to create the start/end. You should first massage the date to the start-of-day (using a technique [like this](https://github.com/fullcalendar/fullcalendar/commit/8e62ffd48f01aba2c8f6318a7429153c699b74fe#diff-8e8fa3a92eb5a8ebf86a7ad15761416aR2)). Otherwise, you get a range that has times in the start/end, and FullCalendar is forced to round those datetimes to start-of-days, which will result in a 4-day view in your case

**Comment by curiousily** [comment]
Got it. Thanks! 👍
