### ISSUE TITLE
Fullcalendar slotLabelFormat does not change with Locale

### ISSUE THREAD

**Issue by SushmaShashidhar** [fullcalendar/fullcalendar#4518]
It is mentioned in the fullcalendar document here that slotLabelFormat takes Locale into account.
https://fullcalendar.io/docs/slotLabelFormat 

But this is not working. If we set the Locale to German (de-DE), which has time format as H:mm (24 hours), the slot label still appears in 12 hours format which is the default (h:mm) .
This can be tested by setting locale to de-DE

**Comment by acerix** [comment]
There's no locale named "de-DE", but the locale "de" shows the labels in 24 hour format in this demo:

https://fullcalendar.io/releases/fullcalendar/3.10.0/demos/locales.html

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by SushmaShashidhar** [comment]
Hi,

Please see below de-DE is one of the locales. I see quite a few locales are missing in the demo lonk you have shared.

**Comment by acerix** [comment]
The locales come from Moment.js, so if there is something specific to "de-DE" compared to the "de" locale you should submit it there, otherwise use "de" for the locale. 

https://github.com/moment/moment/tree/master/locale
