### ISSUE TITLE
Distribute a version of FullCalendar with all plugins

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#4566]
@toxpal raises a good point about how annoying it is to need to load many different plugin files, whereas in v4 only 1 JS and CSS file were required. Users of a Webkit/Rollup build environment probably appreciate the division into plugins, because their build environment does the bundling for them, and they can save on filesize, but for people who initialize via [script tags and browser globals](https://fullcalendar.io/docs/initialize-globals), this can definitely be annoying.

Something that is annoying for users of *both* techniques is that they need to manually include all required CSS files. This low-tech solution was decided [in this issue](https://github.com/fullcalendar/fullcalendar/issues/4490#issuecomment-465159527).

Something else that doesn't make a whole lot of sense is how the plugin files are used from a CDN (see the "CDN" section on the [Downloads](https://fullcalendar.io/download) page). The whole reason people use CDNs is to make their sites load faster, but if they need to load each individual plugin files (both JS and CSS), it sort of defeats the point. They could end up with ~8 requests.

What I'm getting at is... maybe we should offer a build of FullCalendar that includes ALL of the plugins by default. It wouldn't be necessary to feed them into the `plugins` array. Everything would just work. Of course, this single JS/CSS would be larger.

I'm not exactly sure how this would work with Scheduler's plugins.

**Comment by toxpal** [comment]
I like the idea of having multiple versions - barebone (in case someone wants to manually include only files they need), and full one (where all the functions just work). 

Not because I need absolutely all the functions for every instance of calendar I load in my apps (I really don't need), but because I optimize my apps as much as possible. And for me, loading only 2 files (1 JS + 1 CSS), even if they are bigger in size, makes much more sense (in terms of performance) than making extra HTTP requests every time I need some additional feature.

Personally, I like how CKEditor devs solved this issue - they offer a few versions, so user can choose how many features he wants and download smaller/bigger package - https://ckeditor.com/ckeditor-4/download/

In other hand, it requires extra efforts to create separate packages and maintain them. I guess it's the main reason why they simply bundled all the stuff and offer one package (that just works out of the box) in v5 - https://ckeditor.com/ckeditor-5/download/

**Comment by arshaw** [comment]
For CKEditor 5, they're putting the onus on the developer to make their own custom build via ES6 modules. That's what FullCalendar is doing as well.

You should try using Webpack! It will get you a small filesize AND only one JS/CSS file.
https://fullcalendar.io/docs/initialize-es6

**Comment by johndevman** [comment]
@arshaw The difference between CKEditor and FullCalendar (from my understanding) is that with CKEditor you actually make a build that you can include and then initialise on a DOM element in the web browser. So you kinda exposing an API you can utilise in the browser. In the docs presented above you'll need to render the Calendar to an DOM element in the build.  I'm definitely ++ on using ES6 to make a own build If I can, but I need to use the API in the browser, to determine on which the element should be rendered at. But currently, I need to manually download a .zip to accomplish this desired behaviour, or is there something I'm overlooking.

**Comment by lingtalfi** [comment]
I agree that full calendar should be updated so that the install for the newbie should be easy as possible (like CK editor in one copy paste operation). My use case is this: I'm thinking about creating a course on Udemy for a bootstrap 4 admin template which will contain some plugins.
I saw the fullcalendar used by other admin templates, and so I thought I would integrate that. 
Now when I go to the home page of fullcalendar (as of 2019-05-19), https://fullcalendar.io/,
the first thing I'm looking for is the snippet that I can copy paste to get started (I've lot of other tools to include in m admin, so I have no time to loose...), but I don't find it, so I dig a little.
If I click the obvious "get started" button, I expect to find this snippet again, but again my expectations are not met. I mean, I'm not an npm user myself, and I don't want to bother my non-tech future students with installing a package manager, and I also would like to avoid any downloads, so I'm really looking for a cdn solution. Fortunately, on the "get started" page, there is this CDN section, and I'm confident that I will find the snippet there. But again I'm getting frustrated
as in the CDN section I only see a bunch of text: no snippet. Where is the snippet.

To continue with the comparison idea started earlier with CKEditor, if you take bootstrap 4, the quick start page (https://getbootstrap.com/docs/4.0/getting-started/introduction/) gives you all the snippets you want, including a starter template, which is exactly the kind of snippets I'm looking for.

If you take jquery for instance, it's less obvious but they still give you the one download link you want in the download page (https://jquery.com/download/). 

So, back to fullcalendar, the closest thing I could find is the snippet on the "initialize-globals" page,
https://fullcalendar.io/docs/initialize-globals, and that's fine, except that it forces you to download
the assets manually, so in other words: there is no ready-to-go snippet using a CDN. 

Makes me even doubt if I want to really use fullcalendar in my course.
I will probably dig a little more, and if the setup proposed by this snippet is not too complicated (i.e. if it's easy to gather those core and daygrid files from the snippets), I will include fullcalendar, otherwise I simply won't (learn about yarn or npm is not an option in this use case).

So in the end, I just want to complain about the fact that there is no easy snippet with CDN, and that's really frustrating, because fullcalendar looks attractive and fancy, and the doc should be reflecting that as well.

**Comment by CalvinWu4** [comment]
👍

**Comment by arshaw** [comment]
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by toxpal** [comment]
Sounds great. I guess it won't be compatible with Bootstrap 3? :)

**Comment by steelbrain** [comment]
@arshaw The referenced blog post says there would be a beta on March 2nd. It is long overdue, any updates?

**Comment by arshaw** [comment]
hi @steelbrain , a beta will definitely be coming out on Monday (apr 6). sorry about the delay

**Comment by arshaw** [comment]
this has been implemented in v5-beta. i just released the second beta release. [please see the blog post](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

https://fullcalendar.io/docs/v5/upgrading-from-v4#pre-built-bundles

**Comment by arshaw** [comment]
this has been officially release: https://fullcalendar.io/blog/2020/06/v5-official

**Comment by ppazos** [comment]
I basically can't use the plugins because I don't know how to include them. There is no documentation about what to do, just a link to yarn, something I don't know. So would be greate to have a built distribution with just css and js for the plugins.

**Comment by ppazos** [comment]
Also would be nice to have some documentation in this repo about how to build the project and get the minified js and css as output.

**Comment by iiibbbmmm** [comment]
> I basically can't use the plugins because I don't know how to include them. There is no documentation about what to do, just a link to yarn, something I don't know. So would be greate to have a built distribution with just css and js for the plugins.

There are demos on the right to the docs.

**Comment by Bartheleway** [comment]
Hi @ppazos, I was trying the same as you so here is my solution. I feel it's not really best one ever but at least it's working.
@iiibbbmmm the aim is to have a custom build to integrate as a script tag. Fullcalendar.io only provide full plugins build and in order to optimize loading time, it's great to be able to have a custom build that fits to our particular needs.

1. Take the [Webpack example](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/webpack)
2. Replace the content of `src/main.js` by :
```
import { Calendar } from '@fullcalendar/core';
import allLocales from '@fullcalendar/core/locales-all';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';

(function (global) {
  global.FullCalendar = {
    Calendar: function (elt, options) {
      return new Calendar(elt, Object.assign({
        plugins: [ dayGridPlugin, timeGridPlugin ],
        locales: allLocales,
      }, options))
    }
  }
})(window);
```
3. Build the project using `yarn run build` (or `npm` equivalent)
4. Take the file from `dist/main.js`, and integrate to your website
5. Depending on what plugins you need, add them in `package.json` and `src/main.js`

Note: If you need a minified version, edit `webpack.config.js` and change `mode: 'production'`.
