### ISSUE TITLE
Nearby event titles can overlap in timeGrid when 

### ISSUE THREAD

**Issue by CollinHerber** [fullcalendar/fullcalendar#4599]
Codepen: https://codepen.io/anon/pen/YMPxGj

The area allowed for fc-content appears larger than the available space. This causes text wrapping issues and potential styling headaches for any custom styling.
A picture of the chrome inspector with elements: http://prntscr.com/n5zfuz

**Comment by acerix** [comment]
I can see the issue, but it's not obvious how the view could be changed to avoid that.  

There's a request to limit the number of events in that case which might be a solution:

https://github.com/fullcalendar/fullcalendar/issues/4218

You could also use a larger scale (eg. day view instead of week view) or maybe use shorter titles and show the longer titles only after clicking an event.

**Comment by arshaw** [comment]
the current behavior is by-design, but can be disabled like this: https://fullcalendar.io/docs/slotEventOverlap
