### ISSUE TITLE
"eventPositioned" gets called while dragging an element

### ISSUE THREAD

**Issue by robertCousineau** [fullcalendar/fullcalendar#4600]
When dragging an element over a view that does not the external event to position (e.g. daygGrid), eventPositioned is only called when it is finally droped.  
When dragging the same element over a view that **snaps the element to position** (e.g. timeGrid), _eventPositioned_ is **called in error**. 

To view this bug, open[ this codepen](https://codepen.io/robert-cousineau/pen/WWbLwV), open the developer console in your browser, and try dragging an element over both the dayGridMonth and the timeGridWeek/Day.

**Comment by acerix** [comment]
Thanks for the report, confirmed.

**Comment by arshaw** [comment]
this is intentional. it's getting called for the "mirror" element that is being displayed while dragging (previously called the "helper" element). same with the eventRender hook.

If you need to distinguish between real events and mirror events, the `isMirror` flag is available to you: https://fullcalendar.io/docs/eventPositioned

**Comment by robertCousineau** [comment]
Noted, thanks.
