### ISSUE TITLE
plugin version mismatching

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#4606]
### Bug Reports
![image](https://user-images.githubusercontent.com/11896237/55498758-aa833080-5644-11e9-920b-eeb0a005fa85.png)

from
```js
function memoizeOutput(workerFunc, equalityFunc) {
    var cachedRes = null;
    return function () {
        var newRes = workerFunc.apply(this, arguments);
        if (cachedRes === null || !(cachedRes === newRes || equalityFunc(cachedRes, newRes))) {
            cachedRes = newRes;
        }
        return cachedRes;
    };
}
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by frlinw** [comment]
It's because of version gap https://github.com/fullcalendar/fullcalendar/issues/4492
Open your devtool and switch between dayGrid and timeGrid: https://codepen.io/frlinw/pen/rbxNBv

**Comment by arshaw** [comment]
To fix this, you need to have your @fullcalendar/resource-common plugin be v4.0.2 as well.

Are you not using a package manager? That would have solved this.

If more people run into problems like this, I will thing about publishing a new release for all plugins each time.

**Comment by frlinw** [comment]
I didn't even import `resource-common` in my project because @fullcalendar/resource-timegrid@4.0.1 didn't required it to work and :
- NPM didn't tell me that it was required
- [Upgrade guide](https://fullcalendar.io/docs/upgrading-from-v3) didn't mention `resource-common`
- [Vertical resource view](https://fullcalendar.io/docs/vertical-resource-view) docs is not consistent about it
![image](https://user-images.githubusercontent.com/11896237/55644330-e699cb00-57d5-11e9-94ac-d0cf85e5e74c.png)
- The [plugin index](https://fullcalendar.io/docs/plugin-index) mentions it but you have to read the description to know that others plugins need it and it's a plugin's dependency, not a plugin. Add a column with dependency list could help or extract `@fullcalendar/core` and `@fullcalendar/resource-common` to let us know they are specials.

**Comment by arshaw** [comment]
Sorry, I thought you were using script tags and globals and choosing to manually resolve dependencies.

If you are using NPM, in theory, this should all magically work. You ideally wouldn't need to worry about resource-common.

The problem you are experiencing was due to an error on my part. I released an inter-package breaking change but did not bump the minor version number. Only the patch number. The minor version number for `@fullcalendar/*` packages is supposed to signal compatibility. That would have fixed the problem. NPM would have automatically download the new resource-common and you wouldn't have seen a problem.

Another mistake I made was this: https://github.com/fullcalendar/fullcalendar/issues/4620

Hopefully this won't happen again in the future. Sorry for the troubles.

PS- i might also implement the suggestion you made about listing dependencies on the plugin index page, for those who use script tags still

**Comment by frlinw** [comment]
Not a big deal, thank you for the explanation & keep up the good work

**Comment by kgilden** [comment]
Just for future reference to make this issue searchable by the error.

```
TypeError: equalityFunc is not a function
   at ResourceEventConfigAdder.buildResourceEventUis (main.js:1553)
   at ResourceEventConfigAdder.transform (main.js:124)
   at CalendarComponent.renderView (main.js:6339)
   at CalendarComponent.render (main.js:6266)
   at CalendarComponent.Component.receiveProps (main.js:3960)
   at Calendar.renderComponent (main.js:6877)
   at Calendar.executeRender (main.js:6837)
   at Calendar.tryRerender (main.js:6818)
   at Calendar.requestRerender (main.js:6810)
   at Calendar.dispatch (main.js:6798)
```
