### ISSUE TITLE
columnHeaderHtml example in docs uses moment

### ISSUE THREAD

**Issue by jamesamuel** [fullcalendar/fullcalendar#4613]
Hi all,

Currently using V4.0.2 and trying to manipulate the headerHTML but throwing the below error: "mom.format is not a function". Codepen below:

https://codepen.io/jamesamuel/pen/KYMBNM?editors=1011

Thanks!

**Comment by acerix** [comment]
As of version 4 the param is a date object and should be formatted with `FullCalendar.formatDate(mom)`:

https://codepen.io/anon/pen/xeRJzX?editors=1011

I see the example in the docs still uses moment's `format()`; that should still work if the moment plugin is used instead of the default.

https://fullcalendar.io/docs/columnHeaderHtml

**Comment by arshaw** [comment]
fixed in the docs!
