### ISSUE TITLE
v4 events doesn`t work

### ISSUE THREAD

**Issue by aravael** [fullcalendar/fullcalendar#4622]
I have a little weird with an events: [ { } ] when i try to use fullcalendar v4, events by ajax are not displayed. Look at my examples please:
in this case, it`s okey:
`eventSources: [
           {
                url: '/calendar/load',
                method: 'POST',
            }
        ],
`
-----------------------------------------------------//
in this case, doesn`t work:
`events: [
            {
                url: '/calendar/load',
                method: 'POST',
             }
        ],
`
i am confused! Check this out please

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by aravael** [comment]
@acerix , i made a working example, but... it doesn`t work in both cases (i mean events and eventSources).
As i understood, events (as a json feed works with GET method only, from docs), otherwise eventSources works with POST|GET  ( tell me please is that true )

here is my codepen example, take a look:
https://codepen.io/aravael/pen/wZJwjq?editors=0010

From browser network panel we can see that with eventSources method we got the response in json, however it does not displayed. And i want to mention that with event method we don`t get any response, as i said, looks like it doesn`t work

Regards

**Comment by acerix** [comment]
It looks like the issue is that the JSON needs to be an array of events but yours is just one event so it needs to be wrapped in an array like this example:

https://codepen.io/acerix/pen/EJWqQv?editors=0010

You do need `eventSources` to change it to a POST request, but there is actually an open issue for that since it's not working:

https://github.com/fullcalendar/fullcalendar-scheduler/issues/521
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by aravael** [comment]
@acerix , sorry but i do not see any diff in your example, and the `url` (https://fullcalendar.io/demo-events.json) does not work. I modified my codepen example, it still not working.
You mention that `you do need eventSources to POST request`... its not clear for me

**Comment by acerix** [comment]
Do you mean you don't see any events in my example?

Your example is using the `events` setting which should just be a string (url) but you have an event source object which only works in the `eventSources` setting.

The `events` setting does not have any way to make it a "POST" instead of "GET" so if you need it to be POST you could use `eventSources` (when it's fixed) or for now using a callback function:

https://fullcalendar.io/docs/events-function

**Comment by aravael** [comment]
@acerix , i got it )
Thx for your explanation !
