### ISSUE TITLE
Localization files doesn't work in version 4. I tried to use sq.js file but it doesn't have all fields.

### ISSUE THREAD

**Issue by olsizotaj** [fullcalendar/fullcalendar#4696]
### Bug Reports
Some of languages are working even they are not referenced from the page.

How to translate month and day names.

For example Albanian language (sq.js) doesn't have all needed fields. It shows M05 as name for month May.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

As of version 4, most localisation is handled by the browser, if you need more control you can use the moment plugin which was used in version 3:

https://fullcalendar.io/docs/moment-plugins

**Comment by olsizotaj** [comment]
Hi,

Thank you for your email.

Please us this url to see the translation for “sq” for example. https://fullcalendar.io/docs/locale-demo

[cid:image003.png@01D5128E.EFD2E710]

Please can you send me any link where to find out how to use moment plugin using scripts tags. This case is not described on the link you gave me.

Thank
Olsi Zotaj

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by acerix** [comment]
Here's an example using moment with script tags: https://codepen.io/anon/pen/qwRvqa?editors=0010
