### ISSUE TITLE
Help me/translate a spanish

### ISSUE THREAD

**Issue by KuraTakasaki** [fullcalendar/fullcalendar#4702]
### Help me please
As the title says: Someone knows how I can pass the calendar to **Spanish**?
I tried it with its file in locales/es.js but even so the months and days were not translated

**Comment by acerix** [comment]
Here's a demo, you can change locale to 'es' to get the Spanish:

https://fullcalendar.io/docs/locale-demo

Since the translations come from the browser, if that demo is not translated for you, it means your browser is missing support, in which case you can use a plugin which is more compatible:

https://fullcalendar.io/docs/moment-plugins
