### ISSUE TITLE
hiddenDays parameter deprives events to be resized on the day that are hidden

### ISSUE THREAD

**Issue by Thebleach0** [fullcalendar/fullcalendar#4712]
Hello everyone,

I didn't find in the docs if it's a bug or a normal behavior but here is my issue:

I set hiddenDays: [ 2 ] which hides Thuesdays. However this deprives events that start or end on a Thuesday to be resized.

For example on the pen under my "PROBLEM" event can be resized from its start but not from its end.

https://codepen.io/Thebleach/pen/eabrRY

Thanks for your help, I hope this is clear enough

**Comment by acerix** [comment]
Thanks for the detailed report. I can see that it's not possible to drag an event from the end if it end's during a "hiddenDay" but am not sure that is a bug, especially since there is an arrow that appears on the event in that case.

**Comment by Thebleach0** [comment]
Hello, thank you very much for your answer.
I understand we can't say for sure if it's a bug. However do you have any idea what could be a workaround to make the end of that event draggable ? I can't find the function that is related to hidden days that makes it not draggable.

**Comment by acerix** [comment]
Here's the code that checks if the event is editable at the end in the timeline view:

https://github.com/fullcalendar/fullcalendar-scheduler/blob/a256037c158bbdaa106f281c4d37d9ea41849160/src/timeline/TimelineLaneEventRenderer.ts#L24

You could hack that to work like you want but that is not a very clean solution and I can't think of another workaround.

Maybe instead of hiding those days you could change the color (eg. using [businessHours](https://fullcalendar.io/docs/businessHours) so events on that day can still be interacted with.

**Comment by Thebleach0** [comment]
Hello,
sorry for that late reply. Modifying that bit of code works perfectly even though it's not very clean :)
I closed the issue, thanks for your help
