### ISSUE TITLE
setProp("id",value) doesn't update .id property

### ISSUE THREAD

**Issue by nickmarkfurness** [fullcalendar/fullcalendar#4730]
Please check pencode for working example of the issue:
https://codepen.io/nickmarkfurness/pen/qzZReJ?editors=1000

Issue is appearing the same as a previous closed issue:
https://github.com/fullcalendar/fullcalendar/issues/4344

I do not seem able to update the .id property using .setProp().
Using the codepen sample just drag and drop the single draggable item onto the calendar.
I want to update the .id field to 12345 (after my ajax call to the db) but i get the original set value all the time.

Am i doing something wrong or is this a bug?

**Comment by acerix** [comment]
Thanks for the report.  I can see that `setProp('id'` doesn't work and made a simplified test case showing that:

https://codepen.io/acerix/pen/MMemVx?editors=0011

I'm not sure if it should be possible to change the ID with setProp, it's not mentioned in the docs:

https://fullcalendar.io/docs/Event-setProp

**Comment by nickmarkfurness** [comment]
Hi,

My use case for wanting to is to match the id given to the event in my database. So when a user drags and drops onto the calendar it open my modal dialogue with the event initially saved in the db. 
If i can never set the id how do i match up the events to the database or even the point of the property?
The items i drag and drop are template events so have their own id in the db. 
If there is a different intended use of the events and the id property then im not sure i follow so any guidance on how i could change things to work around would be great cheers 

Nick

**Comment by Invincibear** [comment]
@nickmarkfurness you can use extended props to store the db's ID. So you'd have event.id which is assigned by FC, and you can then set something like event.extendedProps.db_id to contain your DB id.
https://fullcalendar.io/docs/Event-setExtendedProp

**Comment by nickmarkfurness** [comment]
yeah i think i will do that to get me moving again. Also means to lookup any event by id i can't use the api calendar.getEventbyid method, instead i will have to iterate through them all to find myself which is no issue.
To come full circle back to the use of .id then i still don't get its use if its -1 all the time. I don't see fullcalendar setting the .id itself too. If fullcalendar sets its own thats fine for uniqueness and its own use but you wouldn't realistically refer to the event by that id either because it could be anything and/or change, especially if you refresh the page?

I also need to compare to using the addEvent and if you are able to set the id yourself there because if you can you should really be able to by drag and drop.

I would be interested to see other people comments on this too to see if it is just me.

**Comment by Invincibear** [comment]
I import events from my DB. Server exports JSON, including Id. The Id is
defined ssrver-side and reflects the Id in the DB. So that mechanism does
allow you to set an event Id, but I don't know about changing it afterwards.

**Comment by arshaw** [comment]
this should be possible. this is a bug

**Comment by ZJaume** [comment]
Is this bug going to be fixed?

**Comment by sanjaypatil51** [comment]
I am also facing same issue on drop events. Any idea when this will be fixed

**Comment by easy2order** [comment]
Any progress on that ?

**Comment by Jedve** [comment]
Same issue for me.

**Comment by MarianoMoreyra** [comment]
I'm having the same issue. 
I see that the EventAPI returns the _def.publicId instead of _def.id, which is correctly modified after doing a setProp("id",val):

`get id(): string { return this._def.publicId }`

What would be the consequences of changing that line to?:

`get id(): string { return this._def.id }`

**Comment by MarianoMoreyra** [comment]
> I'm having the same issue.
> I see that the EventAPI returns the _def.publicId instead of _def.id, which is correctly modified after doing a setProp("id",val):
> 
> `get id(): string { return this._def.publicId }`
> 
> What would be the consequences of changing that line to?:
> 
> `get id(): string { return this._def.id }`

Definitely **not the way to go**! 

A quick workaround tho it would be to add the following at line 2020 of the generated main.js file, just before calling the mutate method:

`                if(name === 'id') {
                    name = 'publicId';
                }`

Otherwise the mutate method will merge the "new" id property to _def instead of replacing the existing publicId.

Another workaround could be to add the publicId to NON_DATE_PROPS and call setProp with 'publicId' as first parameter instead of 'id', although I don't like it very much, as it changes the way we call the setProp.

It's not nice to apply this kind of "patches" although I think it might help others that can't apply other suggested solutions. In my case, I don't want to refresh the calendar every time an external event gets dragged.

Hope this helps, and please, let me know if my workarounds break any other use cases, since I'm still testing them!

**Comment by Ewen-Lgy** [comment]
Thanks @MarianoMoreyra, your solution definitely helped me !

I hope this issue will be fixed soon

**Comment by doit-jochem** [comment]
Hi everybody,

 in my case I have events in the database and with dropping events the event gets saved to the database. Because there is also a week view, Fullcalendar gets the events again for the weekview and matches already existing events in the calendar with the events from the database on the key 'id'. Because i can't set the ID with the drop, Fullcalendar cannot compare the newly added event with the event in the database. This causes fullCalendar to show the events twice (one with ID and one without ID). If I could set the id after dropping them with setProp(), this issue would be solved and events would not get generated twice. 

Is there any ETA for solving this issue?

**Comment by MarianoMoreyra** [comment]
Hi @doit-jochem 

I'd love to contribute a solution, although I'm not a front-end developer and I'm having a hard time trying to build the package in order to be able to test different ideas. 

I'll keep trying anyway!  😃

**Comment by arshaw** [comment]
this was surprisingly easy to fix given the v5 codebase. queued for release

**Comment by arshaw** [comment]
this has been released!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0

demo:
https://codepen.io/arshaw/pen/rNjLRgQ?editors=0011

**Comment by William-Wildridge** [comment]
> this has been released!
> https://github.com/fullcalendar/fullcalendar/releases/tag/v5.6.0
> 
> demo:
> https://codepen.io/arshaw/pen/rNjLRgQ?editors=0011

This works really nicely for most views. It seems to delete the event however if done in a resourceTimelineMonth view. resourceTimelineWeek and resourceTimelineDay work as in the codepen.
