### ISSUE TITLE
when one of extraParams is null

### ISSUE THREAD

**Issue by huajiongyu** [fullcalendar/fullcalendar#4736]
### Feature Requests
when one of extraParams is null, and post to the background program, I got the text "null". 
could it post the null or empty string to the back program?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by tcytra** [comment]
This is not difficult to reproduce.

In the options.events.extraParams add any key with a default value of null, assuming this is a model for a form field to filter calendar events via user input. The code executing the request wraps null as a literal string and sends that to the back-end.

The reason this matters is (for example) laravel validation rules allowing nullable for what would otherwise be a record id (ie: 'nullable|exists:users,id') will choke on this "null" string. It's an easy (but not very elegant) workaround to avoid this problem but still, shouldn't be necessary.
