### ISSUE TITLE
Inverse background docs refers to old `id` option for repeating events

### ISSUE THREAD

**Issue by inquisitive-stha** [fullcalendar/fullcalendar#4746]
Rendering : inverse-background not working in month view

You can check code on this [CodepenLink](https://codepen.io/inquisitive/pen/KjWLBN)

I have tried sending data with time and without the time and both are not working

```
{
      "title": "Test 3",
      "id": 2,
      "start": "2019-06-18 07:00:00",
      "end": "2019-06-18 08:00:00",
      "rendering": "inverse-background",
      "allDay": true
}
```

**Comment by acerix** [comment]
Since you have multiple events with `inverse-background` but with different times, the "space" where the events exist get colored by the other events that are not in that space.  It is more clear with just 2 events:

https://codepen.io/acerix/pen/gNRvPK?editors=0010

You can assign the same `groupId` to all such events which I believe is what you are looking for:

https://codepen.io/acerix/pen/WqOMGW?editors=0010
