### ISSUE TITLE
locale="fa" displays Gregorian dates in version 3

### ISSUE THREAD

**Issue by timsar2** [fullcalendar/fullcalendar#4782]
as you can see in your demo from official web site
when you set locale="fa". the name of days will be change but title not change.
for example date of 2019/07/18 must change to 1398/04/27 in title.
maybe  it must call some 
`fullCalender.gotoDate("1398/04/28");`

you can test it from official link. just set local to 'fa' for each version.
version 3:
[https://fullcalendar.io/docs/v3/locale-demo](https://fullcalendar.io/docs/v3/locale-demo)
version 4:
[https://fullcalendar.io/#demos](https://fullcalendar.io/#demos)

**Comment by acerix** [comment]
I can see in version 3 the date shows up as "ژوئیه ۲۰۱۹" which is incorrect because it should be using the Persian calendar. In version 4, the date shows as "۱۳۹۸ تیر – ۱۳۹۸ مرداد" which seems to be the correct calendar.

There is an open request to add support for the Persian calendar: 

https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Since that will not likely be added to version 3, it might work to use this plugin for momentjs:

https://www.npmjs.com/package/moment-jalaali
