### ISSUE TITLE
Events showing incorrectly in timeGridDay

### ISSUE THREAD

**Issue by JuanManuelSivianes** [fullcalendar/fullcalendar#4791]
Good morning everyone, first I want to apologize for my English, I am Spanish and I am using a translator.

I have an error when I try to show the events in the view:
![image](https://user-images.githubusercontent.com/10671906/61828732-aa16db80-ae67-11e9-8e7a-fc5574ec2553.png)

As you can see the event does not adjust to the specified time, but when I change to week or month view and return to the day, the event already appears correctly.

Do you have any idea why this happens?

I have seen that it has been spoken here: https://github.com/fullcalendar/fullcalendar/issues/2838
But your solution does not work for me.

**Comment by JuanManuelSivianes** [comment]
I leave the configuration I use to load the events:
![image](https://user-images.githubusercontent.com/10671906/61828906-0f6acc80-ae68-11e9-8a3b-3ec55dc088c4.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It sounds similar to https://github.com/fullcalendar/fullcalendar-scheduler/issues/551 , so might work correctly with `slotDuration: {minutes: 15}`.
