### ISSUE TITLE
hook for modifying DOM of resourceLabelText

### ISSUE THREAD

**Issue by vinicius-sf** [fullcalendar/fullcalendar#4838]
Hey there!

I'd like to know if there is a way to take control of the resources header element and render a custom element instead of just passing the text via the `resourceLabelText` option.

If this is not currently possible, how hard would be to add it? Something along the lines of the render* callbacks used for resource and events rendering.

We are currently evaluating fullcalendar + scheduler and this is a needed feature for our product. A prompt response would be very much appreciated.

Thanks!

**Comment by harohl** [comment]
I am also interested in a hook for the resource header text on the timeline view.  I will also warn that modifying in viewSkeletonRender or datesRender is not a reliable solution.  It appears that the resource header is modified in resourceRender.  Therefore if resourceRender is still rendering resources after viewSkeltonRender is complete, it will overwrite your change.  This happens for one of my customers that has 100 resources.  In general since this code seems to run asynchronously, it is difficult to predict the event order.

**Comment by lukkor89** [comment]
Unfortunately, I was forced to use an older version of the Full Calendar (v3) library that did not have the method described. I found a workaround that might be useful to someone:
1. set the "resourceLabelText" property to any text,
2. override the "viewRender" function,
3. replace the order of the table header rows with jquery: headerColumns.after (headerText),
4. in the same function, set headerText.innerHTML to any HTML view.

**Comment by muhammadumairaslam** [comment]
here's my code which i m using currently. just add the line [here ](https://github.com/fullcalendar/fullcalendar-scheduler/blob/681b108127745047dbb24d550e753d42207132e3/resource-timeline/src/SpreadsheetHeader.ts#L83)

`context.calendar.publiclyTrigger('resourceHeaderRender', [{ el: this.tableEl, view: context.view }]);`

i was stuck when using [resourceOrder](https://fullcalendar.io/docs/resourceOrder) option dynamically, because both callback functions `viewSkeletonRender` and `datesRender` are not fired.

please correct me, if i m wrong.

**Comment by arshaw** [comment]
now possible with these hooks:
https://fullcalendar.io/docs/resource-area-header-render-hooks

**Comment by Mario-aj** [comment]
You should use `resourceAreaHeaderContent`.
