### ISSUE TITLE
Installing fullcalendar-scheduler with npm generates a package.json with old dependency of fullcalendar

### ISSUE THREAD

**Issue by PhilMDev** [fullcalendar/fullcalendar#4842]
It appears that the version on npm is different than your github version.  The npm version still has a dependency of fullcalendar.  This causes problems when you use both.  Great product!  Thanks!

**Comment by arshaw** [comment]
The release dates discrepancy you are seeing in package.json is a red herring... at the time of scheduler 1.9.4's release, the entry was "2018" (https://github.com/fullcalendar/fullcalendar-scheduler/blob/v1.9.4/package.json#L11). You were just looking at the master, which has moved on from that.

The real problem as you mention is that there are two version of fullcalendar in the node_modules directory. One is in the root. The other is in fullcalendar-scheduler/node_modules. 

I've been wrestling with NPM this morning. I can't understand why it always installs two version, even when I explicitly write semver ranges that should be compatible.

I believe the problem is related to the fact that the newest version of scheduler 1 (1.9.4) is NOT compatible with the newest version of fullcalendar 3 (3.10.0). It's compatible with fullcalendar 3.9.0 only. I'll make a new release of scheduler 1 (1.10.0) and see what happens.

**Comment by arshaw** [comment]
I released v1.10.0 of fullcalendar-scheduler which is compatible with v3.10.x of fullcalendar. I have verified that this fixes the problem.

As part of releasing v1.10.0 I needed to make fullcalendar-scheduler reference jquery and moment as **peerDependencies**. This tripped people up when we did this for the fullcalendar package: https://github.com/fullcalendar/fullcalendar/issues/4136#issuecomment-453357934

@acerix , can you be mindful of this when people write into support and whatnot?
