### ISSUE TITLE
no mention of schedulerLicenseKey

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#4913]
on this page https://fullcalendar.io/docs/scheduler

there should be a mention of schedulerLicenseKey

**Comment by dakala** [comment]
No longer valid in the current version of the website which has this:

`schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source'`

**Comment by dakala** [comment]
Minor punctuation fix

**Comment by arshaw** [comment]
Hey @dakala , I don't understand why it's no longer valid? what was the punctuation fix?

FWIW, the original problem this ticket reported has since been fixed when i redesigned the website.

**Comment by dakala** [comment]
@arshaw I've updated my "no longer valid" comment. I should have said "fixed". 

Not sure about the punctuation now because, initially, I had more than 1 issue in a single branch. https://github.com/fullcalendar/fullcalendar-site-static/pull/71 is probably the PR from around the same time as this issue. It's closed without any comments.
