### ISSUE TITLE
Week view is missing slashes in IE11

### ISSUE THREAD

**Issue by mdentremont** [fullcalendar/fullcalendar#5058]
Can be reproduced on the demo site: https://fullcalendar.io/#demos

Firefox (slashes are present):
![image](https://user-images.githubusercontent.com/1106324/65697154-d5c56600-e050-11e9-8c73-d62afd3bfb28.png)

IE11 (slashes are missing):
![image](https://user-images.githubusercontent.com/1106324/65697110-bfb7a580-e050-11e9-873d-8b8f6b8f3577.png)

**Comment by acerix** [comment]
Thanks, confirmed.  

As of v4, the dates are rendered with `native DateTimeFormat`, but IE11 uses a space instead of a slash as this basic demo shows:

https://cdpn.io/acerix/debug/eYOovZQ/jVMpobJWjNyk

It might work to add the Intl.js polyfile, or you could use a plugin like moment.js which has more consistent formatting:

https://fullcalendar.io/docs/moment-plugins
