### ISSUE TITLE
Some background events or parts of them don't receive pointer events like hovering

### ISSUE THREAD

**Issue by rodriguesgiancarlo** [fullcalendar/fullcalendar#5110]
I am trying to use Fullcalendar 4.3.1 with Bootstrap theme to show holidays in background while other events are shown on same date. My aim is when users mouse over days I show the holiday name through tooltip, while the background is in another color and other events can be added. However when I set event's rendering option as 'background' only the last one event's tooltip is shown.

This pen (by Andrew) reproduces the situation https://codepen.io/ADyson82/pen/zYYZJJZ?editors=0010

Thanks in advance.

**Comment by acerix** [comment]
Thanks for the report,  it looks like two different issues are causing this.  I made a demo with just a hover effect which shows it's not just a problem with the tooltip:

https://codepen.io/acerix/pen/vYYJeyd?editors=0110

The first of the month does not respond to the mouse at all which seems the same as this issue, and the same CSS fixes it:

https://github.com/fullcalendar/fullcalendar/issues/4750

Similarly, there is a "skeleton" for the foreground events which is causing the middle part of the background events to not respond and can also be fixed with `pointer-events: none`:

https://codepen.io/ADyson82/pen/zYYZJJZ?editors=0110

**Comment by rodriguesgiancarlo** [comment]
The "skeleton" solved the problem. Thank you @acerix

**Comment by OBreidenbach** [comment]
I have a similar problem. If I have several background events in one row, only the last is responding to click events. See:
https://codepen.io/obreidenbach/pen/RwWYNXJ

**Comment by arshaw** [comment]
this is fixed in v5: https://codepen.io/arshaw/pen/VweMByK?editable=true&editors=001

though there's a minor related remaining bug: https://github.com/fullcalendar/fullcalendar/issues/5560
