### ISSUE TITLE
Wrong now indicator

### ISSUE THREAD

**Issue by linkillhz** [fullcalendar/fullcalendar#5114]
When max time exceeds 24 o'clock.

My config
```
    nowIndicator: true,
    minTime: '09:00',
    maxTime: '1.09:00', // == 33:00
    now: '2019-10-28T08:30:00' // just for demo
```

Demo
https://codepen.io/qlgctaoz/pen/LYYLwwy

**Comment by acerix** [comment]
Thanks for the report.  `maxTime` does not have a number of days, so the format should be "33:00" but I can see that also has the issue when nowIndicator shows at the top of the view when it should not be displayed since you specified "now" as before the view starts.

https://codepen.io/acerix/pen/zYYddqX

**Comment by mladibejn** [comment]
Hi @arshaw, do you know possibly when this would be fixed?

**Comment by BoLaMN** [comment]
i believe its got todo withhttps://github.com/fullcalendar/fullcalendar/blob/master/packages/core/src/View.ts#L338 as its calculating the time now as 5pm when its 7am 🤔

**Comment by arshaw** [comment]
this has been fixed in v5: https://codepen.io/arshaw/pen/NWxaBYz?editable=true&editors=001
