### ISSUE TITLE
Now line not rendering correctly on reload rails and webpack

### ISSUE THREAD

**Issue by lguenier** [fullcalendar/fullcalendar#5126]
### Bug Reports
On loading or reloading the page, it shows the now line at an incorrect hour, if I navigate with turbolinks it works correctly.

Here is the [github](https://github.com/lguenier/rails-and-fullcal) of the project stripped to the bare minimum 

Here is the more detailed [stackoverflow](https://stackoverflow.com/questions/58785527/now-line-and-events-not-displayed-correctly-ruby-2-6-3p62-rails-6-0-1-webpac) question.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

The demo should be able to run in the browser (eg. codepen) and not use server-side code like Ruby that is in your project.

**Comment by lguenier** [comment]
The problem is that I guess the problem comes from the integration of fullcalendar in rails.
To reproduce it, it's literally 6 steps I've detailed in the readme.

Thanks in advance.

**Comment by acerix** [comment]
The calendar is only client-side, so if the bug is only reproducible in rails (backend), it's not a bug in the calendar.

**Comment by lguenier** [comment]
I understand that it's only client-side but the integration in rails has a bug, that's why I thought it was on your side. Guess I'm on my own to try and find what's wrong with it.
Thanks
