### ISSUE TITLE
upgrade documentation

### ISSUE THREAD

**Issue by Goddard** [fullcalendar/fullcalendar#5130]
The documentation is some what lacking when trying to upgrade.  Correct me if I am wrong please.

I have version 3.9 of fullcalendar in a project. I just came into and also the timeline version 1.9.4  I am in the process of seeing if they have support account, but I would still think this kind of some is documented some where.

I have no idea what if these versions are compatible, how to upgrade them, or even how to download older versions.

I want to upgrade to 4, but I think stepping through a less drastic change is best.

Please advise.

**Comment by acerix** [comment]
We have a guide for the upgrading from v3 to v4 in case you didn't see it:

https://fullcalendar.io/docs/upgrading-from-v3

You can update to the latest release of v3 (versions 3.10.1 and 1.10.0) without updating your code, but would need to follow the guide to upgrade to v4 since there are some major changes.

**Comment by jmz527** [comment]
Hi @acerix! I'm just going to include my question onto this issue.

You mentioned updating to the latest release of v3 (version 3.10.1). I looked in the repo's changelog and only found [v3.10.0](https://github.com/fullcalendar/fullcalendar/blob/master/CHANGELOG.md#v3100-2019-01-10) documented, same goes for the [releases](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0).

However, on npmjs.com I did find both [v3.10.1](https://www.npmjs.com/package/fullcalendar/v/3.10.1) and [v3.10.0](https://www.npmjs.com/package/fullcalendar/v/3.10.0).

So is there any difference between v3.10.0 & v3.10.1? If so, what changed?

**Comment by jmz527** [comment]
@acerix never mind, I answered my own question by pulling down both v3.10.0 and v3.10.1 so I could diff them side-by-side. I found out the changelogs diverge by a hair.

This is what I found in the CHANGELOG.md for v3.10.1:

> v3.10.1 (2019-08-10)
> --------------------
> 
> Released solely to change the [package description text](https://www.npmjs.com/package/fullcalendar)
> to reference v4 packages.

**Comment by arshaw** [comment]
@Goddard , to answer your original question, with FullCalendar v4 and v5, all minor versions of each package are compatible. For examples `@fullcalendar/core` versions `5.1.x` will be compatible with `@fullcalendar/resource-timeline` versions `5.1.x`. We don't really mention this in the docs anymore because it's mostly taken care of by NPM. And as of v5, the `fullcalendar-scheduler` combined bundle contains ALL packages, so you don't need to worry about compatibility between it and anything else (in the past you'd need to make sure it was compatible with the `fullcalendar` package). Hope that makes sense.
