### ISSUE TITLE
Option to disable the internal event storage

### ISSUE THREAD

**Issue by Phibedy** [fullcalendar/fullcalendar#5150]
It would be great if the internal event storage could be disabled, so drag and drop/resizing does not modify the events.
Would be an easy fix for: https://github.com/fullcalendar/fullcalendar-react/issues/33

**Comment by acerix** [comment]
Do you mean that dragging an event should not change the start/end time of the event in the calendar even though the event is moved to a new time?  For that you can fetch the original event from the source instead of getting the instance from the calendar.   It might help if you can provide an example of how you are expecting it to work since I'm not sure I understand what you are looking for.

**Comment by Phibedy** [comment]
Sorry for answering that late.
Example:
* I drag/drop an event
* calendar notifies me
* I send an request to the backend
* backend rejects the event modification
* calendar shows event that is not in sync with the passed events (as the data given to the Fullcalendar did not change)

**Comment by acerix** [comment]
You can contact the backend from `eventDrop` and call `info.revert()` if the request is rejected.

https://fullcalendar.io/docs/eventDrop

**Comment by Phibedy** [comment]
Yes, just needs some time. I did not provide one from the start as I thought you might want to wait till version 5 to see if it still fails.
