### ISSUE TITLE
Ability to change alignment of slot label text

### ISSUE THREAD

**Issue by neontuna** [fullcalendar/fullcalendar#5159]
<img width="972" alt="Screen Shot 2019-11-27 at 11 51 59 AM" src="https://user-images.githubusercontent.com/7414827/69743377-59acd480-110c-11ea-9b73-9facfceefb2c.png">

[Demo here](https://codepen.io/neontuna/pen/XWWvXpL)

Maybe this is intended behavior but when adding multiple tiers to `slotLabelFormat` for instance 

```
slotLabelFormat: [
  { day: '2-digit' }, 
  { weekday: 'narrow' },
]
```

It seems like the text ought to be centered in container.  However it does this sort of shifting alignment where days to the left of today are aligned right, today is centered, and days to the right are aligned left.  

Maybe this in intended behavior but I would like to just center everything if possible.  I wasn't sure if one of the render callbacks could be used to change this.

**Comment by acerix** [comment]
The top tiers is aligned like that since it can have very long slots and the label should stay visible, eg:

https://codepen.io/acerix/pen/vYYogaE?&editable=true&editors=001

It could be useful to have an option to make them always centered so I'll leave this as a feature request.

Since your tiers are the same size, one option is to simply combine them:

https://codepen.io/acerix/pen/PooMWyz?editors=0010

Otherwise you can use `datesRender` to remove the alignment CSS or add some HTML:

https://fullcalendar.io/docs/datesRender

**Comment by acerix** [comment]
For reference, CSS hack to make them left aligned:

https://codepen.io/acerix/pen/vYYogaE?editors=0100

**Comment by arshaw** [comment]
the original issue is no longer happening in v5:
https://codepen.io/arshaw/pen/BajwOyO?editable=true&editors=001 (no CSS workaround necessary)
