### ISSUE TITLE
Option to also display timeslots on right side of time grid

### ISSUE THREAD

**Issue by michalfordonski** [fullcalendar/fullcalendar#5178]
### Feature Requests

Hi, we use your solution in the company and customers often report to us the need for hours to move left right (fixed) just like the resources in Vertical Resource View. Quite often applications are also to put the list of hours on the left and right at the same time. Is it possible that you will introduce such a solution? Or if there is a way to do it, can you give me a hint because we were looking and none of us found a solution to this problem.

**Comment by acerix** [comment]
If I understand, are you looking to have a copy of the time slots column show on the right side?

That is not built-in, but I think you could use datesRender to make a copy of that column. Otherwise you could make a custom view that works that way.

There's an open request to add horizontal scrolling which sounds like what you mean by making them "fixed":

https://github.com/fullcalendar/fullcalendar/issues/3022
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by michalfordonski** [comment]
Yes, that's the point, thank you. I didn't think about this copy of the column on the right using the datesRender method. Thanks again.

**Comment by Tyagi-Naveen** [comment]
> Yes, that's the point, thank you. I didn't think about this copy of the column on the right using the datesRender method. Thanks again.

Hi michal,

I also want to implement the same thing, can you please share the solution code. It will be really helpful. 

Thanks.
