### ISSUE TITLE
Column width are rounded to the whole pixels so are not always uniform width

### ISSUE THREAD

**Issue by Stalyon** [fullcalendar/fullcalendar#5203]
Hi,

In my use case, and in any example I found, column width is not the same everywhere.

Ex: For a calendar of 1436px, with 7 columns, 6 first are at 205px and last one at 206px.
Why column width is not ~205.15px for the 7?

In my particular use case, I have a dayGridWeek overlaped by my own component and so the columns are not matched.

Thank you for your great job here.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Stalyon** [comment]
https://codepen.io/Stalyon-Pwi/pen/ZEYaXVJ

I just use your default CodePen example and set a width for the calendar (801px).
If you look at the columns in month view, you will see the first 6 columns are at 114px, and the last one (Saturday) is at 115px.
Same in week view (first 3 at 114px and last 4 at 115px).

**Comment by acerix** [comment]
Thanks for the demo, I can see the last column has the "extra" pixel but it's not obvious without looking in dev tools, so it would help if you can show the alignment issue.

I believe it works like that because some browsers have issues with partial pixels, but doing it as you suggest is probably better if all browsers handle it nicely now (since IE9 is no longer supported).

**Comment by arshaw** [comment]
the browser's native table layout engine is doing this. it seems most browsers prefer to do integers for table widths
