### ISSUE TITLE
[Request] hiddenDays - option to enable them when sending request to backend

### ISSUE THREAD

**Issue by fadafez** [fullcalendar/fullcalendar#5277]
Hello, 
I've searched among old requests and I couldn't find anything related to this topic.

**Description:**
I'm receiving events from backend, and my calendar has hiddenDays: [0] (Sunday) setup.
As in March 2020, the 1st is on sunday, my backend service fails to return long events, as the start day is hidden, and so fullCalendar is sending as start parameter, the first visible day (2 of march).

**Request:**
It would be nice if possible, to have an option that:
- Will make hiddenDays processing work as usual, hiding them in the calendar
- Make start/end parameters sent to backend service, consider hidden days, instead of the first/last visible day

Having this option would save a lot of code on server side, especially when switching between different views. I mean, without it the backend service must check if the day passed as parameter is after/before an hiddenDay, and if that is the case, then subtract/add a day to the query.

I know that is not that hard to implement, but in my opinion, is better if the calendar remains as the only source of truth for the filtering condition. Otherwise one needs to share hiddenDays configuration with the backend.

**Comment by acerix** [comment]
I don't see how it would be useful for the backend to know about the days that are hidden. It might help if you post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) of the issue. 

If you mean in your example that you want to include events that start on March 1 and are a few days long, your backend query should also check the end time of events to find any that are in the visible range.

**Comment by fadafez** [comment]
Isn't more polite to see the answer before to close the thread ?

**Comment by acerix** [comment]
We close all invalid issues, I can reopen it if there is a valid request.

Since your issue is your backend failing to return events during the visible range that can only be solved on the backend.

I don't understand how telling the backend about hidden days would be useful for that, but you could use `extraParams` to pass that info.

**Comment by f-ricchiuto** [comment]
Let me try to explain:

The calendar is setup to hide sundays.

The backend has events recorded with a start and a end date. 

Let's take an example event on the db, with start date set to sunday 1st of any month, and end date set to the 7th of the same month.

The calendar when is opening the "month view", will send a request to the backend to show events starting from the 2nd day of the month, until the end of the month. 

The problem happens when the hidden day happens on the first day of the month, probably even when the hidden day is the last day of the month.

That's because the backend receives a start and a end date, and configures the query like this:
```SELECT * FROM events WHERE start >= DATE($start_date) AND end_date <= DATE($end_date)```

Do you see the problem here? If the calendar sends 02/01/2020 as start date, any event with start set to 01/01/2020 will not be catched by the condition, and so it will be excluded from the returned results.

It's a bit tricky to implement a logic on backend side to handle that dynamically. 
While I suppose that enabling an option in the calendar that will send the ```start``` & ```end``` parameters to the backend, excluding the hiddenDays logic, would give more flexibility, and save a lot of problems.

I don't know, it seems way easier to implement this on frontend side, while I see doing it on backend a lot more complicated and prone to errors.   

In my head I see the calendar as the source of trouth, speaking about configuration, while the backend must only interpret those options and return data accordingly. But that's only a personal consideration.

Please keep in mind that this problem happens only when the hidden day is the first shown in the calendar, independently if the view is monthly or weekly. 

Maybe it's a problem on how I set up my configuration.

**Comment by acerix** [comment]
To find events in the range the query needs to be like `(StartA <= EndB) and (EndA >= StartB)`.

https://stackoverflow.com/a/325964

**Comment by f-ricchiuto** [comment]
That question seems related to finding an intersection between two date periods....In this case we have only one period, with one start and one end... 

Database (event records)

```
S - M - T - W - T - F - S - S - M - T
1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9 - 10 <- Days
[------------- Event A ---------]
           [-----------Event B---------]

```

Ok, so the calendar is set with sundays hidden. It will send:

```
start: 02-01-2000
end:  10-01-2000
```

How do I get startA/endA - startB/endB values? 

For me in these days developers are used to have two values when talking about html elements that are handling dates (read: datepickers). Those elments have a `value` and a `formattedValue`, the first is what is sent to the backend, the second is what is shown in the DOM. 

Is nearly the same discourse for the calendar...I'm seeing the week with sundays exluded, but I'm considering the whole week when requesting data from the backend. 

Why? Because in this way the query doesn't need to be too much selective, and so one can switch from a normal calendar (that shows all days) to one which is hiding some of them, without sending any extra parameters, and switch query, it will just work..

**Comment by acerix** [comment]
The query needs to find all events that intersect the visible range, so the date range is one period and the other period is that of each event. So your query should be `WHERE start <= DATE($end_date) AND end >= DATE($end_date)`.

Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.
