### ISSUE TITLE
Having problem initializing the library inside a mithril component

### ISSUE THREAD

**Issue by raaffaaeell** [fullcalendar/fullcalendar#5289]
Hello, I'm trying to get started with a simple view only, but I'm not sure what I'm doing wrong.

     const m = require('mithril');
     let { Calendar } = require('@fullcalendar/core');
     const dayGridPlugin = require('@fullcalendar/daygrid');

    let calend = {
        oncreate: (vnode) => {
            console.log(vnode);
            let calendar = new Calendar(vnode.dom, {
                plugins: [dayGridPlugin]
            })
        },

        view: (vnode) => {
            return m("div");
        }
    }

    m.mount(document.body, calend);

The error I'm getting is this one, I assume it has to do with how I'm importing the plugin ?
`
![stacktrace](https://user-images.githubusercontent.com/6959662/75788584-d1f3e900-5d3e-11ea-881a-1cce8e0de8a4.PNG)

I just have webpack setup to output a file (with just this code) as pointed https://mithril.js.org/installation.html

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing. Your link gives me an error "Non-Image content-type returned".

This page explains how to import it, it might help to use the webpack example project as a starting point:

https://fullcalendar.io/docs/initialize-es6

**Comment by raaffaaeell** [comment]
I'm not sure why the link didnt work. Also, I'm not sure how I'ld create a reproducible jsfiddle or codepen of it, I'm not using the script tags directly

[mithrilteste.zip](https://github.com/fullcalendar/fullcalendar/files/4283395/mithrilteste.zip)

I uploaded the project, I believe you dont even have to run the npm install & start, I included a generated js with the error.

You see, I think I'm having a problem with the plugin (based on the error), I'ld like to check if this

const dayGridPlugin = require('@fullcalendar/daygrid');

is the same as this

import dayGridPlugin from '@fullcalendar/daygrid';

Or do I have to put it in the domContentLoaded event ? I'm trying to get it to work with this SPA framework.

I'll try the webpack example, I haven see it before

**Comment by acerix** [comment]
Since there is no built-in support for mithril, I believe you should just include the calendar as in the webpack example.  I'm not familiar with mithril methods but those method might not be compatible and I get the same error when I test it.

You could use codesandbox.io to make a runnable demo, eg: https://codesandbox.io/s/2z6wp2jozn

**Comment by raaffaaeell** [comment]
I see. I managed to make it work, created a webpack config and then used the imports from the link you posted. Sorry for the confusion, now I know where to find some of the stuff on the site.

The only thing I changed was the imports, instead of using require I put import and it worked, I really dont know why the difference

Thank you for your time, sorry for the confusions.
