### ISSUE TITLE
Events cannot be moved directly below other events

### ISSUE THREAD

**Issue by Ryanauger95** [fullcalendar/fullcalendar#5314]
### REPRODUCTION
https://codesandbox.io/s/ecstatic-stonebraker-gk1vf?fontsize=14&hidenavigation=1&theme=dark

To reproduce, drag event "D" underneath event "F", so that F begins at 7:00am. Now try dragging "F" below "D" so that D begins at 7:00am. What you will see is that the calendar blocks D from being directly below F, but will not prevent F from being directly below D.

The strange thing is that if you drag an event from the right panel onto the calendar, those events have no issue with their times rubbing up against each other.

I'm incredibly confused by this, and usually that means I'm doing something wrong. I produced this issue as minimally as I could, so that you can see it in action

**Comment by acerix** [comment]
Since the size of the time slots is 30 minutes, dragging events moves them in exactly 30 minute intervals.  Your events are not exactly on the half-hour though,  eg. "D" starts and ends 18 seconds and 962 milliseconds after the hour and for "F" it's "18.965", so they overlap by a few milliseconds if D is dragged right after F.
