### ISSUE TITLE
Improve Handlers/Callbacks/functions documentation

### ISSUE THREAD

**Issue by koosvanderkolk** [fullcalendar/fullcalendar#5332]
The documentation could be greatly improved if there would be just a searchable list with all functions and callbacks.

For example: I am now looking for a callback when the calendar is done rendering. Where should I look?

https://fullcalendar.io/docs/handlers -> nope
https://fullcalendar.io/docs/render -> nope
https://fullcalendar.io/docs/view-api -> almost
https://fullcalendar.io/docs/datesRender -> maybe? An example would be helpful here, as I do not understand how to implement this callback.

I think the folks at the Datatables library did a great job here, e.g. https://datatables.net/reference/event

A searchable table, with filtering options. Each event has its own page (e.g. https://datatables.net/reference/event/init) with an elaborate description and examples.

Maybe you can use this as an example?

**Comment by acerix** [comment]
There is a table of contents that you can search with your browser (eg. Ctrl-F).

https://fullcalendar.io/docs#toc

There is no callback for "done" since the calendar is never considered "done rendering".  You should be able to simply put your callback code after calling `render()`. If you want to run something after all the events are loaded, you can specify the events "as a function" and put the call at the end of that function.

`datesRender` is intended for modifying the DOM elements related to the calendar dates.  I agree it would be good to have more examples in the docs and it could be explained better.

**Comment by acerix** [comment]
I just noticed there is already a request for this:

https://github.com/fullcalendar/fullcalendar/issues/4196
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
