### ISSUE TITLE
Typescript declarations missing for locales

### ISSUE THREAD

**Issue by timthelion** [fullcalendar/fullcalendar#5335]
If I try to use the example [here](https://fullcalendar.io/docs/locale) in typescript I get an error:

```
ERROR in /app-v/apps/dpnk/static/ts/locale-test.ts
[tsl] ERROR in /app-v/apps/dpnk/static/ts/locale-test.ts(2,22)
      TS7016: Could not find a declaration file for module '@fullcalendar/core/locales/es'. '/app-v/node_modules/@fullcalendar/core/locales/es.js' implicitly has an 'any' type.

ERROR in /app-v/apps/dpnk/static/ts/locale-test.ts
[tsl] ERROR in /app-v/apps/dpnk/static/ts/locale-test.ts(3,22)
      TS7016: Could not find a declaration file for module '@fullcalendar/core/locales/fr'. '/app-v/node_modules/@fullcalendar/core/locales/fr.js' implicitly has an 'any' type.
```

Here is `locale-test.ts`:

```
import { Calendar } from '@fullcalendar/core';
import esLocale from '@fullcalendar/core/locales/es';
import frLocale from '@fullcalendar/core/locales/fr';
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the error? Would really appreciate it because the time saved reproducing will be time spent fixing.

Here is the example with locales in Angular:

https://stackblitz.com/edit/fullcalendar-angular-demo?file=src%2Fapp%2Fapp.component.ts
