### ISSUE TITLE
[v5 Regression] New lines no longer preserved in formatSlotLabel

### ISSUE THREAD

**Issue by steelbrain** [fullcalendar/fullcalendar#5374]
Filing a bug because couldn't find this behavior documented in the upgrade guide @ https://fullcalendar.io/docs/v5/upgrading-from-v4

In v4, we could feed `\n` to `formatSlotLabel` / `slotLabelFormat` and it would be rendered as such (calendar translated `\n` to `<br />`) but in v5, it's ignored

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

`slotLabelFormat` only accepts a "date formatting object" so I'm not sure how you are passing the `\n`.

In v5, there is `slotLabelContent` for injecting content there:

https://fullcalendar.io/docs/v5/content-injection

**Comment by steelbrain** [comment]
`slotLabelContent` fixes this for me, thank you.
Re formatSlotLabel: It accepts a callback in v4, even in v5, that callback can return any formatted string it wants, v4 converted `\n` in that formatted to `<br />`, v5 does not
