### ISSUE TITLE
eventDidMount is not triggered when changing the view range for events that show in both ranges from showNonCurrentDates

### ISSUE THREAD

**Issue by badger-github** [fullcalendar/fullcalendar#5407]
Hi

Thank you for this project.

I have been trying out v5b2 (eventDidMount) on my existing code and came across an issue with popups, on v4 these are working (eventRender).

Example: [https://codepen.io/codepen_account/full/NWGMjwg](https://codepen.io/codepen_account/full/NWGMjwg)

Page Load (May): Popup works on both events 25/5, 1/6
Click Next (June): Popup not working on 1/6, works on 8/6
Click Prev (May): Popup works on 25/5, not working on 1/6

Is this an issue or is it something I will have to investigate with the other scripts (jquery/semantic)

Thank you for your time.

Pete

**Comment by dariovinci** [comment]
i don't know if this solution is ok for your project but if you add

`showNonCurrentDates: false,`

it works

**Comment by acerix** [comment]
Thanks, confirmed.  Seems to be caused when the same event shows in both view ranges, so as a workaround you could change to another view temporarily to force any existing events to be "unmounted".

**Comment by arshaw** [comment]
When switching between months, the weeks that are in-common are reused. The week with "event 2" is reused, so the event never really unmounts.

However, internally FullCalendar uses Preact, and for whatever reason Preact decides to briefly remove that `<tr>` node from the DOM and then reinsert it.

Your fomantic lib listens for removals:
https://github.com/fomantic/Fomantic-UI/blob/2.8.4/dist/components/popup.js#L114
and then destroys the popover interaction.

You can disable this by setting `observeChanges: false` in the popover creation. demo of things working: https://codepen.io/arshaw/pen/zYvyrKJ

**Comment by gnujeremie** [comment]
I seem to have a problem maybe related to this issue. I just upgraded to 5.3.1 (angular version). I use a function to modify the rendered html of my events with `eventDidMount`. For instance, I sometimes have to add icons. To do so, I have this code : 
```
    const fcTime = info.el.querySelector('.fc-event-time');
    // Check some conditions, if true then : 
    fcTime.innerHTML = '<i class="fas fa-users"></i> ' + fcTime.innerHTML;
```

The first rendering is OK, but if I change the view, then it gets mixed up for in-common : 

![Capture d’écran 2020-09-18 à 16 07 43](https://user-images.githubusercontent.com/245343/93607481-aa5a2a80-f9c9-11ea-9d16-78cd6c88ade0.png)

![Capture d’écran 2020-09-18 à 16 07 56](https://user-images.githubusercontent.com/245343/93607477-a9c19400-f9c9-11ea-8595-214d97e23119.png)

I have the option `showNonCurrentDates` to `false`. Did I miss something, or is this a bug because ? 
thanks
