### ISSUE TITLE
Events are displayed on the wrong date and get dragged together with jQuery 3.5

### ISSUE THREAD

**Issue by lsiden** [fullcalendar/fullcalendar#5414]
In [Version 3 Event Dragging/Resizing Demo](https://fullcalendar.io/docs/v3/event-dragging-resizing-demo) all but the first event are displayed as lumped together.  When I try to drag one to a different date, they all drag together.  On mouse-up, they all snap to May 9.

I verified this in Chrome Version 81.0.4044.138 (Official Build) running (64-bit) in incognito mode to insure that no extensions may be interfering, and in Firefox 76.0 (64-bit).  

If I open the demo in CodePen and comment out "editable: true", then each event is rendered in the correct position in the monthly calendar, but of course I can no longer drag and resize them.

This affects our app which uses Version 3. I am surprised that no one else has complained about this. Is Version 3 now deprecated in favor of Version 4?

**Comment by acerix** [comment]
Thanks for the report. I found this is caused by the jQuery update to 3.5, it works with 3.4:

https://codepen.io/acerix/pen/pojZjMY

There is another issue for jQuery 3.5 support which may also fix this:
https://github.com/fullcalendar/fullcalendar/issues/5348
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by toxpal** [comment]
Upgraded to Jquery 3.5 today and found the same issue. I'm very happy to see it was already reported and will probably get a fix.

**Comment by arshaw** [comment]
fixed! https://github.com/fullcalendar/fullcalendar/issues/5348#issuecomment-630563193
