### ISSUE TITLE
Display event groups with number of events in each

### ISSUE THREAD

**Issue by danvernon** [fullcalendar/fullcalendar#5436]
Is there documentation on a use case where you can group events together like this. So you would a number of different events with different stages grouped together?

![image](https://user-images.githubusercontent.com/428197/82556961-ad035b00-9b62-11ea-8e2d-4e7a9ae9af45.png)

**Comment by acerix** [comment]
It's not built in but I can see how it would be useful as a feature.  For now you could provide the groups that you want displayed as the "events" instead of the events themselves which could be styled like your mockup.

There is [a similar request](https://github.com/fullcalendar/fullcalendar/issues/4765) for "grouped events" but it's not really the same as this.

**Comment by danvernon** [comment]
Is there a way to pass custom props - like the count?

**Comment by acerix** [comment]
Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.

You can use [extended props](https://fullcalendar.io/docs/event-object#non-standard-fields) for that.
