### ISSUE TITLE
Empty space between date and all day section in Firefox on Linux

### ISSUE THREAD

**Issue by Virusmater** [fullcalendar/fullcalendar#5443]
1. Use Firefox 76.0.1 (64-bit) on Linux
2. Open examples/full-height.html
3. Switch to week or day view
4. Reduce height of the browser to make scrollbars appear
5. Check the space between date and all day section
Expected (fullcalendar-4.4.0):
https://ibb.co/fX3WHFJ
Actual (5.0.0-beta.3):
https://ibb.co/58SDH4K

Works fine in Chrome (both mobile and desktop) and Firefox Mobile.

**Comment by brennanmurphy** [comment]
The issue is caused by the minimum size for a scrollbar in Firefox is bigger than the row height, and Firefox forces scrollbars to be present for all elements with `style="overflow: scroll"` or similar css styles.

Potential solution, see screenshot. By changing the element style tag attribute to `overflow: hidden auto` from the current `overflow: hidden scroll` the issue disappears.
![Screenshot_2020-05-24_00-25-50](https://user-images.githubusercontent.com/13474579/82761936-1ed5e180-9dbb-11ea-80c7-18ec531ac3e5.png)

**Comment by acerix** [comment]
Thanks, confirmed in this demo:

https://fullcalendar.io/docs/v5/timegrid-standard-view-demo

**Comment by arshaw** [comment]
this is only happening on Firefox on **Linux**. It has a very strange behavior when applying `overflow: hidden scroll`. See this demo:

https://codepen.io/arshaw/pen/BajmoZd?editors=1100

## Correct rendering:

![scrollbars-chrome](https://user-images.githubusercontent.com/56520/86146724-97b90f00-bac6-11ea-9001-910927e4b5a8.png)

----------

## Firefox on Linux:
![scrollbars-linux-ff](https://user-images.githubusercontent.com/56520/86146787-a69fc180-bac6-11ea-8b45-542e49741c84.png)

Firefox on linux adds weird extra height. It seems impossible to detect this extra height from a JS perspective.

**Comment by arshaw** [comment]
The workaround of setting it to `overflow: hidden auto` will prevent the column-widths from syncing, which will be very obvious in timegrid and timeline views.

**Comment by Virusmater** [comment]
Fixed
