### ISSUE TITLE
5.0.0-beta.3 - eventDrop doesnt get called when moving from allDay event to non-allDay event in week/day view

### ISSUE THREAD

**Issue by hanselke** [fullcalendar/fullcalendar#5458]
events are passed as an object from parent to FullCalendar.

In week/day view, when events are dragged from allDay row into the non-allDay rows, eventDrop event doesnt trigger.

It works when dragging from non-allDay into allDay. Works when moving allDay to allDay. Works on month view.

**Comment by acerix** [comment]
It seems to be working in the latest release:

https://codepen.io/acerix/pen/BaoegyW?editors=0011

Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if it's not working. Would really appreciate it because the time saved reproducing will be time spent fixing.
