### ISSUE TITLE
DayGridMonth overflows in Firefox

### ISSUE THREAD

**Issue by wartmanm** [fullcalendar/fullcalendar#5524]
Test case: https://codepen.io/wartmanm/pen/QWyvbmJ
The last row of dates overflows onto the following text in Firefox 68 through 79.  Chrome and Safari are unaffected.

Firefox 79:
![image](https://user-images.githubusercontent.com/3869625/85338814-9e34fe80-b4a8-11ea-9456-5df530d9aeba.png)
Iridium 2020.04:
![image](https://user-images.githubusercontent.com/3869625/85338931-cae91600-b4a8-11ea-9d64-c841b0c4a0d7.png)

**Comment by arshaw** [comment]
confirmed on firefox

**Comment by kamilchlebek** [comment]
@arshaw 
I'm having similar issue. In our project, we have full height calendar, in firefox last row is cut in the middle. Seems it's because `.fc-daygrid > table.fc-scrollgrid` is bigger than it's parent `.fc-daygrid`

See the screenshot
![image](https://user-images.githubusercontent.com/40219331/86008949-d644c000-ba19-11ea-8346-932af92f689f.png)

Demo: https://codepen.io/pen/?editors=0010 link straight from https://fullcalendar.io/reduced-test-cases

**Comment by DarkNami** [comment]
Page https://fullcalendar.io/docs/month-view-demo on Chrome v83, height is 791px.

![Chrome83_height_791px](https://user-images.githubusercontent.com/5100919/86453181-f3e29400-bd4f-11ea-876c-fae1959819ce.png)

Page https://fullcalendar.io/docs/month-view-demo on Firefox v78, height is 812px.

![Firefox78_height_812px](https://user-images.githubusercontent.com/5100919/86453230-06f56400-bd50-11ea-95c3-65fa7e6f675e.png)

**Comment by arshaw** [comment]
no longer an issue in v5.2.0: https://codepen.io/arshaw/pen/MWKNGaK (viewed in Firefox of course)
