### ISSUE TITLE
fullcalendar v5 bundle doesnt include rrule plugin

### ISSUE THREAD

**Issue by BoLaMN** [fullcalendar/fullcalendar#5525]
the bundle doesnt include fullcalendar/rrule plugin only the rrule.js plugin so its never initialized

![2020-06-23_16-41-45](https://user-images.githubusercontent.com/414479/85372164-993b8200-b570-11ea-93f8-bf3da979849c.jpg)

**Comment by arshaw** [comment]
the bundle intentionally does not include anything related to rrule. on these pages that list the bundle contents, rrule isn't mentioned:

https://www.npmjs.com/package/fullcalendar
https://fullcalendar.io/docs/initialize-globals

You'll need to use [an ES6 build system](https://fullcalendar.io/docs/initialize-es6) if you want to use rrule functionality

**Comment by BoLaMN** [comment]
But it includes the rrule.js vendor library in the zip?

**Comment by arshaw** [comment]
woops, including it in the archive was a mistake. I've removed it in v5.0.1

**Comment by 21Junipers** [comment]
I've copied text from the v5 docs under RRule Plugin below that I find confusing..... I understand that rrule is no longer distributed as a part of any FC package/zip. But due to the statement below, it is unclear to me whether it is possible to use in in ver 5 as it was in v4. That is to say, add a script tag at the top of the page that includes a reference to the rrule.js (in addition to FC as described in v5 docs. As a novice, these two statements appear to be contradictory. 
---------------
From v5 docs: RRule Plugin (emphasis added)

"The rrule plugin can **ONLY** be used with an ES6 build system. It CANNOT be used with script tags and browser globals.

If you are using <script> tags and browser globals, you must ensure the original non-plugin rrule.js dist file from the rrule site is included on your page first."

**Comment by arshaw** [comment]
sorry about that. i forgot to remove that line. it's now removed

**Comment by 21Junipers** [comment]
Thanks for the replay. No convincing you to make a bundle/build that includes rrule.js I suppose.....;) 

v5 is such a step forward in so many ways. Just disappointing for us script tag jockeys, since recurring events are so much a part of scheduling/calendaring.
