### ISSUE TITLE
Fullcalendar and bootstrap modal messes up the styling

### ISSUE THREAD

**Issue by martijnhiemstra** [fullcalendar/fullcalendar#5537]
I have discovered that when I put the Resource-Timeline View in a bootstrap 4 modal that the timeline is completly messed up. When I use inspector I can see that the top rows have a height of either 0px or 2px.

Here is an example of the generated code:
```
<div class="fc-datagrid-cell-frame" style="height: 2px;">
  <div class="fc-datagrid-cell-cushion fc-scrollgrid-sync-inner">
    <span class="fc-datagrid-expander fc-datagrid-expander-placeholder">
      <span class="fc-icon">
      </span>
    </span>
    <span class="fc-datagrid-cell-main">Users</span>
  </div>
</div> 
```

Here is a screenshot:
![Website 6-24-2020 11-16-29 AM](https://user-images.githubusercontent.com/22905318/85528451-2c75c580-b60c-11ea-8617-efa1133739c1.png)

As you can see the resource names are mostly gone and the header is almost invisble. I am using angular however since this is a css issue I'm guessing it has nothing to do with that.

Thanks in advance

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

You may need to call `updateSize` after the modal is displayed.

https://fullcalendar.io/docs/updateSize
