### ISSUE TITLE
Can't change event text color on dayGridMonth view

### ISSUE THREAD

**Issue by Freezard** [fullcalendar/fullcalendar#5566]
Since 5.0.0 text color is always blackish for dayGridMonth view no matter if what I set for general setting _eventTextColor_ or _textColor_ on event sources. It looks bad on the background colors I'm using so I want to set it to white but the black text seems hardcoded.

It was fine in 5.0.0 RC.

**Comment by acerix** [comment]
If you mean background events, I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5528
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

Otherwise, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
