### ISSUE TITLE
Calendar render bug bootstrap tab

### ISSUE THREAD

**Issue by aldwnesx** [fullcalendar/fullcalendar#5577]
Weird rendering issue when used with bootstrap navigation tabs

screenshot:
https://imgur.com/6t7JeFp

if i in zoom out or in, then it will render properly.
I also tried to render only when tab is selected but it's still bugged

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by andrejm7** [comment]
??????????????

**Comment by andrejm7** [comment]
You stop closing the questions. And teach people how to use the library

**Comment by pierresh** [comment]
Many people got problems with tabs (me included), but no any answer....

**Comment by opensourcelib** [comment]
### Well the issue is still there 😬
In [Stack overflow](https://stackoverflow.com/a/23267110/3941547) I found out a good explanation on how to solved this issue,  In conclusion the problem is with bootstrap tabs so **after refereeing to the bootstrap css** file. **You need to add the following css style:**
`<style>`
`/* bootstrap hack: fix content width inside hidden tabs */`
`        .tab-content > .tab-pane:not(.active),`
`        .pill-content > .pill-pane:not(.active) {`
`            display: block;`
`            height: 0;`
`            overflow-y: hidden;`
`        }`
`        /* bootstrap hack end */`
`</style>`

**Comment by waltare68** [comment]
thanks,@opensourceLib
