### ISSUE TITLE
Boostrap next/prev buttons repeat themselves onclick

### ISSUE THREAD

**Issue by NicolasCARPi** [fullcalendar/fullcalendar#5613]
Hello,

There seems to be a bug with the arrow button in the bootstrap theme:

![out](https://user-images.githubusercontent.com/3043706/87368101-009b8f00-c57d-11ea-861b-14918aa22fe6.gif)

Here is the reproducible codepen: https://codepen.io/Osef1212/pen/eYJjoYB?editors=0111 (just added bootstrap + fontawesome and enabled it with themeSystem)

If `bootstrapFontAwesome` is set to `false`, the bug doesn't appear (and is a good workaround while this bug is being addressed).

**Comment by arshaw** [comment]
Thanks for the report. I recently figured out the root cause of this. Please go here to see an explanation and workaround:
https://github.com/fullcalendar/fullcalendar/issues/5544#issuecomment-658390524
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
