### ISSUE TITLE
Can I add an event without rerender the existing ones

### ISSUE THREAD

**Issue by b0r1slav** [fullcalendar/fullcalendar#5619]
I'm using v3 and I have a lot of events and most of all a lot of logic in "eventRender". Rendering all events takes 3-4 seconds and that's mean when the user drop an external event for example, he have to wait 4 seconds to be dropped.

I'm looking for a way to drop an event without rerender(not trigger "eventRender") all already existing ones?

Thanks in advance!

**Comment by acerix** [comment]
All events need to be rendered again since the position can change when one event is changed so that can't be avoided but there is an open request to optimize it:
https://github.com/fullcalendar/fullcalendar/issues/3003
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
