### ISSUE TITLE
RRule plugin incoherent behaviour between string and object initialisation

### ISSUE THREAD

**Issue by gongAll** [fullcalendar/fullcalendar#5642]
Currently, when we try to pass an RRule to the calendar in the form of a string, it will execute the rrule lib's "rrulestr" method, which is implemented in a way that, if we do pass exrules or exdates, for example, will compile them properly. However, when passing these same parameters in an rrule object, this will not be the case, given that you only thought of the case of an RRule object and not on the extender object RRuleSet, which provides further capabilities that the RRule object on its own does not possess. Would gladly create a pull request for this, would there be interest on your side.

Quick example on how this is currently an issue for me:
 -- Passing an RRuleSet as a string to the fullcalendar with an exrule in it does not allow me to set the dtstart of the exrule, given that the rrule as a string can only have ONE dtstart.

**Comment by 21Junipers** [comment]
@gongAll - Have you seen that there are a couple of open PRs that seem related: #5097 (needs tests) and #5326?

**Comment by gongAll** [comment]
Oh, thank you for the heads up on that. Seems to me that the #5326 does not achieve this, tho, only #5097.

**Comment by 21Junipers** [comment]
Agreed re: #5097. I thought you might be interested in that one since you were offering a PR to address the RRuleSet issue. And since #5097 has been accepted and is "only" awaiting tests, I thought maybe you might want to address the testing issue. If I were capable I would do so myself. I only added mention of #5326 because it seems to me 'related'.

**Comment by gongAll** [comment]
I've never done tests, so I would also be a newbie for that... If I have some time I will do it in the future.

**Comment by ganySA** [comment]
Just an update to this - the latest of RRULE throws an error when trying to specify EXDATE.
So an update is needed or need to specify a working version of RRULE.

**Comment by arshaw** [comment]
@ganySA, would you be able to post a [runnable, stripped-down demonstration of the bug](https://fullcalendar.io/reduced-test-cases) in a separate ticket?

@gongAll, I was never able to verify your bug report because of lack of test case, but as of v5.5.0, we call the `rrulestr` function with the `forceset` flag: https://github.com/fullcalendar/fullcalendar/blob/v5.5.0/packages/rrule/src/main.ts#L139
