### ISSUE TITLE
addEvent in eventReceive

### ISSUE THREAD

**Issue by sama55** [fullcalendar/fullcalendar#5676]
### Reduced Test Case

https://codepen.io/sama55/pen/ZEQNPMp

### Bug Description
1. D&D event from left items to any date. For example, today.
2. Move event from today to tomorrow.
3. Re-move(Restore) event from tomorrow to today. <== Can't move event to old day.
If we move event even once,  cannot make/move event on that day.
If eventOverlap is set to true then this issue does not occur.

**Comment by iiibbbmmm** [comment]
```javascript
info.event.remove();
```
at the beginning of `eventReceive`

**Comment by sama55** [comment]
Hi iiibbbmmm.
I don't know why user must voluntarily remove event (???),.
Anyway, your advice has helped me avoid issue.
Thank you so much.

**Comment by iiibbbmmm** [comment]
`addEvent` doesn't mean to replace the original one.

**Comment by sama55** [comment]
I got it. Thanks.

**Comment by acerix** [comment]
Dropping an event on the calendar automatically adds it, but it's not showing up in your demo because your events have both an `endTime` and a `duration`, they can only have one or the other:

https://codepen.io/acerix/pen/dyGBgWP

Although the event was not showing, it still causes a conflict when trying to move the other event to the same day.  You could remove the event that is added automatically, or just use it instead of calling `addEvent` to add another.
