### ISSUE TITLE
Add draggable on event with jQuery on "did mount" event not working

### ISSUE THREAD

**Issue by florentm35** [fullcalendar/fullcalendar#5681]
### Reduced Test Case
https://jsfiddle.net/florent_martin35/eu2xzgok/5/

Test with FullCalendar 5.0.0 to 5.2.0
JQuery 3.5.1
JQuery-ui 1.12
### Bug Description
When we make an event draggable with jQuery-ui on eventDidMount and we drag an event on the same date, they freeze and is not revert, in all other case that's ok.

Note: Sometime the revert work

### Screenshot

![Alt Text](https://i.imgur.com/CGxEsl6.gif)

**Comment by acerix** [comment]
The issue seems to be with making the event element draggable with jQuery-ui when it's already draggable from setting `editable: true`.  I believe they is not compatible, so you should turn off `editable` to use your own dragging.  

There's an open request to allow dragging events outside the calendar:

https://github.com/fullcalendar/fullcalendar/issues/3140
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by florentm35** [comment]
If that can help someone with added a inner content div and the drag on theirs, with jQuery this work, an example with tooltip and a external list for the data : https://jsfiddle.net/florent_martin35/eu2xzgok/24/
_See july 2020 for the example of data_

![Alt text](https://i.imgur.com/vufpIkF.gif)
