### ISSUE TITLE
Events are not printed in order according to their start time

### ISSUE THREAD

**Issue by jonathan-SA** [fullcalendar/fullcalendar#5709]
### Reduced Test Case :
[https://codepen.io/Scottynou/pen/vYGEjMR](https://codepen.io/Scottynou/pen/vYGEjMR)

### Bug Description

When print the calendar with the timeGridWeek view events are not in the correct order.

### Screenshots
![Browser view](https://user-images.githubusercontent.com/22292178/89871481-c2af7c00-dbb7-11ea-8ea4-9753be893a2e.jpg)
![print view](https://user-images.githubusercontent.com/22292178/89871489-c6430300-dbb7-11ea-866a-6322a5587def.png)

**Comment by acerix** [comment]
Thanks for the report.  I simplified the test a bit and can see that events get printed in the order they are defined, so that seems like a bug, I would expect them in order of when they start. 

https://codepen.io/acerix/pen/ExKVEre?editors=0010

**Comment by arshaw** [comment]
this has been fixed in [5.3.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.3.0)

**Comment by espen** [comment]
I think this still is an issue. I am trying https://codepen.io/acerix/pen/ExKVEre?editors=0010:

Safari: Works. Shows calendar borders for each hour.
Chrome: Display events in reverse order. Does not show borders in the grid.
Firefox: The outline and week header is shown but no events or anything in the calendar body.

Safari:
![safari](https://github.com/fullcalendar/fullcalendar/assets/32258/b6425b34-0411-419b-9047-7f91b40449f0)
Chrome:
![chrome](https://github.com/fullcalendar/fullcalendar/assets/32258/c78cf34b-806c-4ae0-b230-13420f3fdd91)
Firefox:
![firefox](https://github.com/fullcalendar/fullcalendar/assets/32258/d8a85095-145f-46fa-9aed-7ffb663a8fa9)

**Comment by acerix** [comment]
I don't see any issue with the event ordering after updating the demo to the latest release: 

https://codepen.io/acerix/pen/jOdgdQv?editors=1010

It's intentional that the time grid lines are not visible in the print version, the adaptive plugin makes the view more compact by not using a time grid. (I am unable to test Safari at the moment, but it seems like a bug if the grid shows there.)  You can print the time grid by _not_ enabling the "adaptive" plugin, there's also an issue about this here:

https://github.com/fullcalendar/fullcalendar/issues/5465
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

Please create a new issue with a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is still a bug.

**Comment by espen** [comment]
obviously the demo was using the old version 🤦‍♂️🤦‍♂️ Sorry for the confusion.

Anyways, I found the issue. I had `eventOrder` set to `title`. I guess this was due to sorting for overlapping events, however the result is that the browser view is sorting by start (and if there were overlapping events it would sort by title) and the print sorts by title only. Not sure if this is expected behaviour or not?
