### ISSUE TITLE
Vue erro console - read 'seg' of undefined

### ISSUE THREAD

**Issue by maico910** [fullcalendar/fullcalendar#5859]
### Reduced Test Case

[Full calendar demo](https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/vue?file=/src/DemoApp.vue)

### Bug Description

Just runing Vue demo project will warn about erro in mounted, trying to read 'seg' of something (see screenshots)

### Screenshots

![image](https://user-images.githubusercontent.com/24510745/94222123-eb1edb80-fec2-11ea-999f-b5667aa16b0e.png)

Erro get changing view to month, and after this erro, can't change more view mode
![image](https://user-images.githubusercontent.com/24510745/94275747-bd1ab500-ff1d-11ea-94c1-9f98ba194953.png)

**Comment by MSRChrisMcMillan** [comment]
I have been looking into an error very similar. Seems to occur when the width of the calendar is about the width of the iPhone or Android handset in portrait. Landscape no problems. On a desktop - shrinking the width of the page redraws the calendar but controls like move to the next month stop working and an error is thrown - the debug console reports an error like "Unable to get property 'seg' of undefined or null reference.".

**Comment by acerix** [comment]
Thanks, confirmed. The same error was reported in the React component so it seems the issue is not with either component:
https://github.com/fullcalendar/fullcalendar-react/issues/96
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

Using "contentHeight: 'auto'" also fixes the error in your demo.
