### ISSUE TITLE
How do I make them look 5 weeks on the calendar? 

### ISSUE THREAD

**Issue by damianlluch** [fullcalendar/fullcalendar#5862]
Hi guys, first thanks for your work.
Second, I need to see 5 weeks in the calendar, I have not found in the documentation some parameter that makes this work, I have only found the option "fixedWeekCount" but in some months it shows me 6 rows.
Thanks again.

PS: I love FullCalendar

![image](https://user-images.githubusercontent.com/1463804/94295278-48696a00-ff61-11ea-8281-fb3fae368fff.png)

![image](https://user-images.githubusercontent.com/1463804/94295311-56b78600-ff61-11ea-956a-08fd617aafa4.png)

**Comment by acerix** [comment]
Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.  If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

You can use "dayGrid" instead of "dayGridMonth" to show less than 1 month:  

https://codepen.io/acerix/pen/wvGbdrV

**Comment by damianlluch** [comment]
Thanks Acerix!
