### ISSUE TITLE
webpack : Please import the top-level fullcalendar lib before attempting to import a plugin.

### ISSUE THREAD

**Issue by wimurk** [fullcalendar/fullcalendar#5886]
### Bug Description

Hi, i am trying to import the interactionPlugin using these [docs](https://fullcalendar.io/docs/selectable) within es6 [laravel-mix](https://laravel.com/docs/8.x/mix)

After compiling (compiling succeeds!) i get the following error in my console. `webpack : Please import the top-level fullcalendar lib before attempting to import a plugin.`. I followed to docs, i removed all serverside scripts. I updated all my packages.

When i remove all the code and import only the 3 packages the error also occurs. Something goes wrong when importing.

Packages used
```json
"@fullcalendar/core": "^4.4.2",
"@fullcalendar/daygrid": "^4.4.2",
"@fullcalendar/interaction": "^5.3.1",
"@fullcalendar/list": "^4.4.2",
 "@fullcalendar/timegrid": "^4.4.2"
```

### Code

```javascript
import { Calendar } from '@fullcalendar/core';
import interactionPlugin from '@fullcalendar/interaction'; // for selectable
import dayGridPlugin from '@fullcalendar/daygrid'; // for dayGridMonth view


//### Below is not executed because of the console error.

class Billings
{

    constructor()
    {
        this.loadCalendar();
    }

    loadCalendar()
    {
        let calendar = new Calendar(document.getElementById('billingCalendar'), {
            plugins: [interactionPlugin, dayGridPlugin],
            initialView: 'dayGridMonth',
            selectable: true
        });
    }

}
```

### Screenshots

![image](https://user-images.githubusercontent.com/14072334/95310511-c6e0d880-088c-11eb-81da-6c9c4bd2f7d8.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

You can use the example project to get started:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/webpack

**Comment by sergiopantoja** [comment]
@wimurk @acerix The same thing happened to me. I discovered it's because I was using version 4.x for the calendar and version 5.x for the plugin. Reproduction with the example project: https://github.com/sergiopantoja/fullcalendar-example-projects/pull/1/files

The fix is to either downgrade your plugin to version 4.x, or [upgrade your calendar to version 5.x](https://fullcalendar.io/docs/upgrading-from-v4).

**Comment by arshaw** [comment]
I've written something explaining why this problem is happening and how I plan to solve it in the future: https://github.com/fullcalendar/fullcalendar/issues/6371
