### ISSUE TITLE
resourceTimelineWeek does not work in shadow dom

### ISSUE THREAD

**Issue by mlarue** [fullcalendar/fullcalendar#5888]
### Reduced Test Case

https://codesandbox.io/s/github/mlarue/fullcalendar-resourcetimelineweek-test

(this codesandbox is crazy shit ;) )

### Bug Description

I'd expect `resourceTimelineWeek` to work also in shadow dom.

When you use `resourceTimelineWeek` in shadow dom, it does not work and throws an error to console.

`resourceTimelineDay` and `resourceTimelineMonth` just work in shadow dom.

https://github.com/mlarue/fullcalendar-resourcetimelineweek-test/blob/main/src/app-root-shadow.js (does not work)
https://github.com/mlarue/fullcalendar-resourcetimelineweek-test/blob/main/src/app-root.js (works)

### Screenshots

![Bildschirmfoto von 2020-10-07 12-57-21](https://user-images.githubusercontent.com/6511748/95333440-16cf9780-08ad-11eb-9c0d-a40f910259a6.png)

**Comment by mlarue** [comment]
When I add `commonStyle` outside shadow dom, it works. So not only `@font-face` must be defined outside shadow dom (#5884). At the moment I still have no clue which css-rule makes trouble here. 

You'll have to add commonStyle outside AND inside shadow dom. Good enough for a workaround, I guess.

**Comment by anderssonjohan** [comment]
We are experiencing the same issue, but with a custom view spanning several days (resourceTimeline + duration >1 day). The common thing around the issue is of course the header with dates above the hours that are sticky during scrolling. Just wanted to add to others that it's not just the resourceTimelineWeek view that is not working in the shadow root.

**Comment by anderssonjohan** [comment]
We just confirmed this workaround worked for us in our solution that uses StencilJS components (rendering to the Shadow DOM).

**Comment by arshaw** [comment]
wow, props for figuring out a workaround with the stylesheets. I've fixed the root cause of this bug and will make a release very soon

**Comment by arshaw** [comment]
this has been fixed in [5.9.0(https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

you'll notice there is no longer a JS error:
https://codesandbox.io/s/objective-driscoll-1luqx?file=/src/app-root.js

one of your hacks was to put the fullcalendar stylesheets both with the shadow-dom root and on the page-level root. it just needs to go within the shadow-dom root now.
