### ISSUE TITLE
dayGridMonth not compatible with background event & google calendar

### ISSUE THREAD

**Issue by botris** [fullcalendar/fullcalendar#5930]
### Reduced Test Case
https://codepen.io/botris/pen/bGeYvvw?

### Bug Description
If you import data from a Google calendar and set the events as `display: 'background'` then the do not show if the viewmode is ` initialView: 'dayGridMonth',`

What do you expect to happen?
See the items as background items.

What happens instead?
See nothing, unless you change to `initialView: 'timeGridWeek',`

**Comment by botris** [comment]
I've found that if you have a multiday event, the days are not seen as all day events. So this is not a full day event:
```
Object {
  start: "2020-08-10T00:00:00+02:00",
  end: "2020-08-21T00:00:00+02:00",
}
```
I ended up using a `eventDataTransform` function to work around this, but this does see like a bug to me.
[Workaround](https://codepen.io/botris/pen/JjKpbKY)

**Comment by acerix** [comment]
The events need to be "allDay" to show in month view, but your events are not considered "allDay" because they have a time of day with the dates.  The demo of holidays from Google works because it doesn't have a time of day:

https://codepen.io/acerix/pen/WNxJqXL?editors=001

So the issue seems to be that your data has a time of day on Google,  you could remove that or else just use `eventDataTransform` to fix.
