### ISSUE TITLE
React demo example breaks in sandbox

### ISSUE THREAD

**Issue by ndueber** [fullcalendar/fullcalendar#5947]
### Reduced Test Case

[link to bug](https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/react?file=/src/DemoApp.jsx).

### Bug Description

I expected I can run the react demo example that is linked in the docs. Or to run the react example when i download it.  
however there Is an error about webpack.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5822
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates. That will be fixed in the next release and for now you can use that workaround.
