### ISSUE TITLE
Vue + SSR  - window is not defined

### ISSUE THREAD

**Issue by gregbengis** [fullcalendar/fullcalendar#6026]
not reproducible with a link (as the stack trace appears in my server logs)

### Bug Description

I am using @fullcalendar 5.4.0

When I try to run my app on my server using SSR, I get this:

![image](https://user-images.githubusercontent.com/16412865/102116964-60f16e00-3e46-11eb-9b14-d233c6407429.png)

Please assist?

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue. Would really appreciate it because the time saved reproducing will be time spent fixing.

If using Nuxt/Next or similar, this might help:

https://github.com/fullcalendar/fullcalendar/issues/4784#issuecomment-667539521
