### ISSUE TITLE
dates are not called in  dayCellDidMount property in month view, when switched from  week view to month view

### ISSUE THREAD

**Issue by divya-sk-tfs** [fullcalendar/fullcalendar#6089]
Reduced Test Case::   https://codepen.io/divyask53/pen/XWjywgE?editors=001

Bug Description:
we have some logic written in dayCellDidMount in month view, and we see some dates are not called in  dayCellDidMount in month view, when switched from  week view to month view

1)click month view
2)click week view 
3)in week view, we can see Jan 3 – 9, 2021 dates are rendered in view by default
4)click month view
5) in console output, we cannot see Jan 3 – 9, 2021 has been displayed in a console output from dayCellDidMount in month view (attached the screenshot of the console)

Screenshot:
![Capture2](https://user-images.githubusercontent.com/65533209/104683062-2b2cf700-571c-11eb-860f-44a73123825d.PNG)

**Comment by acerix** [comment]
This is intentional, since they are the same view type, the DOM nodes from the week view are reused so they don't need to be mounted again.  This issue is to better document that and has some more details:

https://github.com/fullcalendar/fullcalendar/issues/5543

Depending what you are using `dayCellDidMount` for, another callback may work better.

**Comment by TanvirArjel** [comment]
@acerix I am also facing this issue. Please help me how can I force to mount all cells again when prev or next month is clicked.

**Comment by codeNicho** [comment]
I need to be able to mount all cells again when prev or next month is clicked too help!!

**Comment by codeNicho** [comment]
@acerix help needed!
https://github.com/fullcalendar/fullcalendar/issues/6089#issuecomment-1263639196
