### ISSUE TITLE
af (afrikaans) locale does not update day title text and calendar title

### ISSUE THREAD

**Issue by zachbresler21** [fullcalendar/fullcalendar#6275]
### Reduced Test Case

https://codepen.io/pen/?editors=0010

In the example above if you set the locale to "af" it does not change the day titles and main title of the calendar

### Bug Description

Setting the locale to af (afrikaans) does not update the title and the day of week text. Only the buttons are updated

<img width="1126" alt="Screenshot 2021-04-21 at 15 53 25" src="https://user-images.githubusercontent.com/49684878/115565494-b7216280-a2b9-11eb-9fe2-6ef46fc5d82a.png">
<img width="270" alt="Screenshot 2021-04-21 at 15 53 36" src="https://user-images.githubusercontent.com/49684878/115565536-be487080-a2b9-11eb-87a4-5f2ea9274f59.png">
<img width="1558" alt="Screenshot 2021-04-21 at 15 53 51" src="https://user-images.githubusercontent.com/49684878/115565576-c7394200-a2b9-11eb-8518-ed3d4a045948.png">

**Comment by acerix** [comment]
Those translations are handled by the browser, so your browser is missing that locale.  You can use the moment plugin instead of relying on browser support, there is an open issue to enable that for all dates:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
