### ISSUE TITLE
Chrome 91 update breaks fullcalendar when using a slotWidth value that is less than 20

### ISSUE THREAD

**Issue by MrOldham101** [fullcalendar/fullcalendar#6338]
### Reduced Test Case

"not reproducible with a link"

### Bug Description

Set your slotWidth value to something less than 20 and make sure your on version 91 of chrome. When you do this for some reason the entire calendar stops working. You cannot drag, you cannot resize, the only thing that you can do is click on the event.

I have tested changing versions of chrome and it is definitely related to something released in the chrome 91 update however google have not released their changes as of yet.

**Comment by acerix** [comment]
I don't see any issue in Chromium 91, do you get the issue in this demo:

https://codepen.io/acerix/pen/GRWMdGK?editors=001

If not, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by labomatik** [comment]
I also experienced an issue after the update to chrome 91, just did the update this morning and the calendar is not showing anymore.
I've narrow it down: i've changed `allDaySlot: false`, to `true`, and the calendar was correctly working again.
it's clearly not that. i'm trying to reproduce on a codepen...

**Comment by s-r-x** [comment]
fc-scrollgrid-section-liquid {
    height: 1px !important;
  } 

quick fix that worked for me

**Comment by labomatik** [comment]
On a working calendar (with allDaySlot = true):
![image](https://user-images.githubusercontent.com/179987/120068578-ab2b7c00-c081-11eb-96bc-a02f9ae4c338.png)

On a failed one (with AllDaySlot = false):
![image](https://user-images.githubusercontent.com/179987/120068603-c8f8e100-c081-11eb-932d-fbbe3cee694f.png)


Seems linked to .fc .fc-scrollgrid-section-liquid {
   
}
if i remove the height:auto all is ok

**Comment by miking-the-viking** [comment]
Bless you, @s-r-x

**Comment by ljr97** [comment]
> I don't see any issue in Chromium 91, do you get the issue in this demo:
> 
> https://codepen.io/acerix/pen/GRWMdGK?editors=001
> 
> If not, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

No issue with the demo, I will try and recreate on a codepen.

The issue is definitely a result of the latest chrome update (v91) as our full calendar setup no longer allows dragging or resizing on chrome v91 but works fine on v90. Also works fine on the latest versions on other browsers (Edge, Firefox, Safari).
The lines of code that seem to cause issue is slotWidth when less than 20 and slotLabelInterval.

**Comment by TomGrobbe** [comment]
> > I don't see any issue in Chromium 91, do you get the issue in this demo:
> > https://codepen.io/acerix/pen/GRWMdGK?editors=001
> > If not, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
> 
> No issue with the demo, I will try and recreate on a codepen.
> 
> The issue is definitely a result of the latest chrome update (v91) as our full calendar setup no longer allows dragging or resizing on chrome v91 but works fine on v90. Also works fine on the latest versions on other browsers (Edge, Firefox, Safari).
> The lines of code that seem to cause issue is slotWidth when less than 20 and slotLabelInterval.

I've had similar issues where the calendar would stretch to be extremely wide suddenly after updating to chrome v91.

From what I've just tested (on Chrome v91), if I *do not* set the `slotWith` property, and I only set the `slotDuration` to something less than or equal to 30 minutes, it causes the calendar to break (stretch very far to on the x axis).

(Side note: 30 minutes and 1 second works, but since it's not an even number it has other visual issues)

However, after setting the `slotDuration` to `01:00:00` and setting `snapDuration` to `00:30:00` (which is what we had for `slotDuration` before), and still *not setting* the `slotWidth` option, everything returns back to normal and the calendar doesn't grow extremely large (in width).

I don't know exactly why this solves my problem but it did for our use case, which is to show a hourly slot, being snappable and editable with a 30 minute duration. Hope this helps narrow it down.

This may not be the exact problem originally posted in this issue, but I hope it helps some people that have the same problem that I did and ended up here looking for solutions.

**Comment by conceptualitis** [comment]
We've been experiencing some issues with our calendar in Chrome 91 as well, so I'll share our experience.

We're on v4, have a resource timeline that uses grouping, a `slotWidth` of `20`, and `slotDuration` of `00:15:00`.

A few of the deeply nested `<table />` elements are expanding to be very wide. For example:

<img width="535" alt="markup of first malfunctioning table" src="https://user-images.githubusercontent.com/422175/120357524-2764d000-c2cb-11eb-80e4-8714b4a9a9bf.png">

That highlighted `<table />` is being rendered at `2956.88px` wide, though it is contained in an `.fc-scroller-canvas` element which is correctly set to `1920px`. I have applied no special styles to it, and in fact styles have no effect! 

See:

<img width="368" alt="directly applied styles have no effect" src="https://user-images.githubusercontent.com/422175/120357982-a22deb00-c2cb-11eb-829c-2f4f03b46f49.png">

I hardcoded a width of `555px` and it's ignored:

<img width="260" alt="Dev tools computed styles" src="https://user-images.githubusercontent.com/422175/120358948-ba523a00-c2cc-11eb-83a2-4292402330ea.png">

I've tried variations of applying styles to the elements themselves, using `!important` to try to override, and regular selectors: nothing can prevent these `<table />` elements from having that width.

One final example:

<img width="426" alt="two nested tables, two different widths" src="https://user-images.githubusercontent.com/422175/120358536-326c3000-c2cc-11eb-8835-a463938a577d.png">

Of the two deeply-nested `<table />` elements in that screenshot the first is has the correct width of `1920` and the second has the blown-out width of `2956.88px`.

For now I've widened the `slotWidth` so that it matches up with this `min-width` Chrome seems to be enforcing.

Safari and Firefox are fine. It appears that Chrome is having serious issues but I'm half-hoping I've simply missed something obvious.

**Comment by pwaddles** [comment]
> I don't see any issue in Chromium 91, do you get the issue in this demo:
> 
> https://codepen.io/acerix/pen/GRWMdGK?editors=001
> 
> If not, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

Hi @acerix ,

Just add 'slotDuration: "00:15:00",' to your example and it introduces a horizontal scroll bar at the bottom of the screen,  I add this line just under the 'slotMinWidth' line.

**Comment by atotic** [comment]
This was triggered by a rewrite of tables in Chrome91. This was a big change. The [developer notes](https://docs.google.com/document/d/16PFD1GtMI9Zgwu0jtPaKZJ75Q2wyZ9EZnVbBacOfiNA/edit?usp=sharing
) might give you some hints about where to look. 

I am the author of the tables rewrite, and would like to help you get to the bottom of this.

Currently, we have only 1 known interesting table bug in M91: [wide-cell percentage distribution](https://crbug.com/1214206).

Our fullcalendar bug is [Chrome 91 update breaks fullcalendar when using a slotWidth value that is less than 20](https://crbug.com/1215394).

**Comment by arshaw** [comment]
@pwaddles , that horizontal scrollbar is intended behavior. I don't think there's a bug w/ that.
@atotic , thanks for the update on the Chromium side.
@s-r-x , thanks for the workaround.

EVERYONE ELSE: please provide a **runnable example**. If not in a code sandbox, then a running live website will do. If I can't reproduce this, then I can't fix it. There must be some magic combination of FullCalendar settings that reveals the bug.

Also, is everyone using FullCalendar v4? People are talking about `slotWidth`, which has been removed in v5. Anyone with problems in v5?

**Comment by arshaw** [comment]
I've reproduced the mentioned timeline problem, which only happens in v4:
https://codepen.io/arshaw/pen/NWpyEEY?editors=0010

But I'm waiting on somehow to help demonstrate the **timeGrid** problem (w/ `allDaySlot:false`), which from the screenshots seems to be happening in v5.

**Comment by pwaddles** [comment]
Also having this issue with V3.

**Comment by atotic** [comment]
> I've reproduced the mentioned timeline problem, which only happens in v4:
> https://codepen.io/arshaw/pen/NWpyEEY?editors=0010

The problem here is:
.fc-time-area col {
    min-width: 2.2em; (or 30.7px).
}

I think FF and Chrome 90 ignore the min width.

**Comment by pwaddles** [comment]
Thanks @atotic  - I've been able to pull that line out and I'm all up and running again :)

**Comment by atotic** [comment]
col { min-width: auto !important; } will restore old min-width behavior in all your tables.

**Comment by arshaw** [comment]
the issues have been fixed. there were two distinct issues, one for timeline and one for timegrid. please read these tracking tickets for more info:
https://github.com/fullcalendar/fullcalendar/issues/6357
https://github.com/fullcalendar/fullcalendar/issues/6358

**Comment by atotic** [comment]
Sorry about this. 

Redistribution of table height over sections is probably one of the least interoperable parts of table standard. There is no spec, and browsers implemented very different things.
