### ISSUE TITLE
Align verticaly the appointements by color/group

### ISSUE THREAD

**Issue by Slayess** [fullcalendar/fullcalendar#6347]
### Checklist

Please mark these items with an [x]

  - [X] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [ ] Other people will find this feature useful

### Feature Description
I'm working over an old project using FullCalendar V3, I'm searching a way to group verticaly the appointements. As you can see on the screenshoot some appointements for the same user are not aligned «one below the others ». I tried some different ways mentionned on the guid without success :(

Thanks in advance for your help.

![16215780660419_cal1](https://user-images.githubusercontent.com/52039612/120274541-4ace5180-c2b0-11eb-8a14-794cd1cd8ab1.jpg)

**Comment by acerix** [comment]
Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.  If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

The events always display at the time they occur in this view so you would need to set the start of each so that they are in the position you want. Or render it as one big event and change the content to appear like that.
