### ISSUE TITLE
Events in dayGridDay view overlapping when eventOrderStrict: true

### ISSUE THREAD

**Issue by richardhills** [fullcalendar/fullcalendar#6393]
### Reduced Test Case
https://codepen.io/richard-hills/pen/NWpZLjj

### Bug Description
See Reduced Test Case. The bookings on Thursday are all stacked on top of each other.

This is running in FullCalendar 5.8.0.

We encountered this with a few dozen events, but have reduced to just these 5. Removing any one of the events causing them to be laid out correctly.

**Comment by rangermeier** [comment]
I (or rather: a customer) also encountered this weird bug. It seems to happen only if there are certain numbers of events on prior days in the same week. Not sure what triggers this, but I also observe it without setting `eventOrderStrict: true`

From stepping through the code, I think the culprit is somewhere in [common/src/seg-hierarchy.ts#L133](https://github.com/fullcalendar/fullcalendar/blob/90da1d253a64e7fc18287ef17778b29bc09c65c1/packages/common/src/seg-hierarchy.ts#L133) where events of the same day receive the same `levelCoord` under some circumstances. Although the code is nicely commented, I don't manage to wrap my head around what's going on there...

This results  `currentMarginTop` in [daygrid/src/event-placement.ts#L167](https://github.com/fullcalendar/fullcalendar/blob/90da1d253a64e7fc18287ef17778b29bc09c65c1/packages/daygrid/src/event-placement.ts#L167) to becomes the negative height of the event.  Which in turn results in `margin-top: -19px` or similar for the second/third/... `.fc-event-harness` element.

**Comment by hmnd** [comment]
Happening with me in DayGrid View, without `eventOrderStrict: true`, too. Started as of v5.8.0.

**Comment by kgilden** [comment]
Can also confirm this happening in DayGrid and appearing somewhere between v5.7.0..v5.8.0.

**Comment by MichaelHeydon** [comment]
Also experiencing this issue, the events with a negative `margin-top` will not be visible on the calendar. Like @rangermeier, have found it depends on the number of events currently displayed as to whether this error occurs. But I haven't been able to determine a key factor to cause the issue. 
![hidden-events](https://user-images.githubusercontent.com/74880856/125380456-8f7ff900-e3d5-11eb-9707-884977f6f914.jpg)

**Comment by arshaw** [comment]
reproduced. [updated repro](https://codepen.io/arshaw/pen/KKmXmPE?editors=0010).

**Comment by arshaw** [comment]
fixed in [5.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.9.0)

updated repro:
https://codepen.io/arshaw/pen/BaRrQvm?editors=0010

**Comment by richardhills** [comment]
Thank you! Looks good from our end.
