### ISSUE TITLE
Background color of background events not displayed on Internet Explorer 11

### ISSUE THREAD

**Issue by BC-M** [fullcalendar/fullcalendar#6789]
### Reduced Test Case

https://fullcalendar.io/docs/background-events-demo

#### Describe how to recreate the bug.

Open the calendar with background-events on IE11 will not display the background-color on these events.

#### What do you expect to happen?

See the background as same as opened on Chrome, Firefox, Safari and co.

#### What happens instead?

Background color not displayed.

#### Internet Explorer 11:

<img width="1728" alt="Background events on IE11" src="https://user-images.githubusercontent.com/40334865/161069756-fa8f4c82-97e8-4569-a2c6-641153625ba9.png">

<img width="1728" alt="DOM-Explorer on Internet Explorer 11" src="https://user-images.githubusercontent.com/40334865/161069869-fe86e82a-a359-459b-b2bc-3947ac34b51f.png">

#### Firefox (works as expected)

<img width="1728" alt="Background events on Firefox" src="https://user-images.githubusercontent.com/40334865/161069895-8fffab9e-3882-43db-b309-a42e2c854d41.png">

**Comment by arshaw** [comment]
This hs

**Comment by arshaw** [comment]
This has been fixed in [v5.11.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.11.4)

Please test out https://fullcalendar.io/docs/v5/background-events

Screenshot of Edge in IE11 mode:
![Screen Shot 2023-01-24 at 5 39 32 PM](https://user-images.githubusercontent.com/56520/214437318-6fea4226-f34f-4441-a775-c1c2d5b21a74.png)
