### ISSUE TITLE
calendar.getDate() returns a date in local time (no UTC-coercion)

### ISSUE THREAD

**Issue by anrikun** [fullcalendar/fullcalendar#7005]
### Reduced Test Case

https://codepen.io/anrikun/pen/poVmBGv

### Bug Description

According to documentation https://fullcalendar.io/docs/Calendar-getDate:

> Calendar::getDate
> Returns a Date for the current date of the calendar.
> **For month view, it will always be some time between the first and last day of the month.**

Unfortunately, the returned month is incorrect once you navigate between month views.
Try the codepen above, open Console and navigate to see the bug.

For your information, a workaround to display the correct month is the undocumented:
`calendar.getCurrentData().currentDate`

**Comment by Invincibear** [comment]
I wasn't able to reproduce this, I got the correct month every time when navigating the month forward/back

**Comment by anrikun** [comment]
I'm in France so it might have to do with the timezone.

**Comment by anrikun** [comment]
I'm adding a screenshot.
![2022-10-20 09_35_20-calendar getDate() returns an incorrect month  — Mozilla Firefox](https://user-images.githubusercontent.com/8371969/196886428-805a6074-3ce2-48d2-8cd3-425c5bc6f8e7.png)

**Comment by acerix** [comment]
The native date objects are not in the correct time zone so `getDate` won't work in general, you should first use `toISOString` as in your second example. This is explained here:

https://fullcalendar.io/docs/timeZone#UTC-coercion

**Comment by anrikun** [comment]
That doesn't change the fact that what's stated in documentation is wrong.

**Comment by acerix** [comment]
That is referring to the [getDate](https://fullcalendar.io/docs/Calendar-getDate) method of the calendar, not JS Date.

**Comment by acerix** [comment]
I looked too quickly and thought you were using `Date.getDate` from JS, but looking closer it does seem inconsistent that `calendar::getDate` is in local time so I'll reopen.

**Comment by arshaw** [comment]
I'll try to explain why the current behavior is intentional. Keep in mind this timezone stuff is rather confusing, even for myself, mainly because JS Date doesn't support timezones which makes unintuitive workarounds necessary. In v7 we'll be using the Temporal API, which will be more intuitive.

When no timeZone is specified, like in your codepen, it's assumed to be `'local'`. All dates emitted from the API will be local. That is what's happening with `Calendar::getDate()` as you notice. UTC-coersion only comes into play when the timeZone is set as a string (like `America/New_York`) and there isn't a timeZone plugin (like Luxon or Moment-timezone).

If you'd like to continue to use the `'locale'` timeZone, but want to use a UTC-ified version of`getDate()`, you can do something like this:

```js
datesSet: function() {
  const localDate = calendar.getDate()
  const utcDate = new Date(Date.UTC(localDate.getFullYear(), localDate.getMonth(), localDate.getDate()))
}
```
