### ISSUE TITLE
[v6.0.0-beta.1] @fullcalendar/common bundle size increased by +1000% on bundlephobia

### ISSUE THREAD

**Issue by lucas-labs** [fullcalendar/fullcalendar#7029]
### Reduced Test Case
not reproducible with a link

### Bug Description

I was testing the new beta version and I noticed a bundle size rise with v6 in comparision with 5.x. 
Aparently, the rise comes from the package `common`, which has rised its size +1000%. 

https://bundlephobia.com/package/@fullcalendar/common@5.11.3
https://bundlephobia.com/package/@fullcalendar/common@6.0.0-beta.1

### Screenshots

![image](https://user-images.githubusercontent.com/12949236/202890041-d09efba3-b35d-4163-a260-fd7a6135d3b8.png)

**Comment by arshaw** [comment]
Thanks for pointing this out. Really strange. I think the problem is w/ how bundlephobia calculates sizes. See the two minified files:

- https://cdn.jsdelivr.net/npm/@fullcalendar/common@5.11.3/main.min.js
- https://cdn.jsdelivr.net/npm/@fullcalendar/common@6.0.0-beta.1/main.min.js

They're similar sizes. Seems like the new bundlephobia size is correct and the old one was always wrong.

**Comment by arshaw** [comment]
Thanks for pointing this out. Really strange. I think the problem is w/ how bundlephobia calculates sizes. See the two minified files:

- https://cdn.jsdelivr.net/npm/@fullcalendar/common@5.11.3/main.min.js
- https://cdn.jsdelivr.net/npm/@fullcalendar/common@6.0.0-beta.1/main.min.js

They're similar sizes. Seems like the new bundlephobia size is correct and the old one was always wrong.

**Comment by arshaw** [comment]
I looked into this a bit further. I believe the v6 beta versions are showing as their correct size, whereas versions prior were forcing bundlephobia to choke and report deceivingly low filesize because fullcalendar's JS code would import .css files (turns out to be incompatible with many tools).

FWIW, the @fullcalendar/common package no longer exists in beta.2 or beta.3. The @fullcalendar/core package does everything. Here's the latest bundlephobia link for it:

https://bundlephobia.com/package/@fullcalendar/core@6.0.0-beta.3

It's 5.7k smaller than the [beta.1 common package](https://bundlephobia.com/package/@fullcalendar/common@6.0.0-beta.1), so things are at least moving in the right direction as we're releasing the betas.
