### ISSUE TITLE
Duplicated external event

### ISSUE THREAD

**Issue by dtconsultingltd** [fullcalendar/fullcalendar#7053]
**Reduced Test Case**
https://codepen.io/damiantaylor/pen/JjZQoBm

**Bug Description**
I have an issue where dragging an external event on to the calendar, then calling refetchEvents() is causing the event to be duplicated.
In my application, events are retrieved via an ajax call and event IDs are assigned by the server - once written to the database.
So, when a new event is added to the calendar, it must be written to the DB, then I use refetchEvents() to refresh the calendar view.
This all works great, except for when I drop an external event.
I'm using the eventReceive callback to open a modal, allowing the user to make changes before the event is saved.
Once the user clicks save, I write the event to the DB via ajax. The event ID is returned from the server, and I update the current event using info.event.setProp('id', ....)
I then fire a refetchEvents() call which I figured would realise there was already an event on the calendar with the returned ID, but it just duplicates it instead.

I've done the best I can to simulate the issue here https://codepen.io/damiantaylor/pen/JjZQoBm
This sets the event ID once dropped on to the calendar and also adds it to the event source with the same ID, and then calls refetchEvents(), causing the event to be duplicated.
Clicking on either of the events displays the event ID - which show to be identical.

Steps to reproduce:
1. Drag 'My Event 1' external event to a free slot on the calendar
2. Click 'OK' on the confirmation window
3. Now the event has been duplicated, click on both events separately to see their IDs are identical

Am I doing something wrong with the way I'm handling the dragging of external events?

**Comment by acerix** [comment]
`refetchEvents` doesn't remove external events that were dropped on the calendar which is why they remain after refreshing.

There is an issue here regarding unique `id` for events:

https://github.com/fullcalendar/fullcalendar/issues/4499
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

Since you are refreshing the events immediately after dropping an event, you can call `revert()` to remove the one that was dropped:

https://codepen.io/acerix/pen/zYagqay
