### ISSUE TITLE
`setExtendedProp` does nothing

### ISSUE THREAD

**Issue by timofei-maximov-saritasa** [fullcalendar/fullcalendar#7094]
### Reduced Test Case

https://codesandbox.io/p/sandbox/focused-dew-fzkmt8

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Extended prop that is set inside `eventDidMount` callback doesn't appear on the first render in event after clicking on it.

Bug appears only in v6, v5 works fine

Here is the first render: 
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/86595911/208372498-8588e2be-b9bd-489e-9b38-928840f6b080.png">

Here is the result after changing dates backwards and forwards:
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/86595911/208372749-3e54079d-2ec7-4aa1-92c0-2654c440e215.png">

**Comment by acerix** [comment]
`backgroundColor` is a built-in property on events, so it needs to be set with `setProp` instead.

https://codesandbox.io/p/sandbox/reverent-waterfall-2uv1vf?file=%2Fsrc%2FCalendar.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A67%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A67%7D%5D

**Comment by timofei-maximov-saritasa** [comment]
@acerix This is just an example. Besides, there is no access to background color when events has not pre-set background color with resource that has color

**Comment by acerix** [comment]
It does seem that calling `setExtendedProp` from `eventDidMount` does not update the value, but I'm not sure it's a bug since `eventDidMount` is intended for attaching listeners to the event elements, for example, so I'm not sure why you are updating it from there.   To set the `extendedProp` initially, it can be included on the event object:

https://codesandbox.io/p/sandbox/quizzical-dew-7kwhhy?file=%2Fsrc%2FCalendar.tsx&selection=%5B%7B%22endColumn%22%3A45%2C%22endLineNumber%22%3A23%2C%22startColumn%22%3A28%2C%22startLineNumber%22%3A23%7D%5D

**Comment by acerix** [comment]
`backgroundColor` is a property of the event so from  `eventClick` it  can be accessed in `event.backgroundColor`:

https://codesandbox.io/p/sandbox/amazing-firefly-zlrchr?file=%2Fsrc%2FCalendar.tsx

**Comment by baba43** [comment]
@acerix I seem to have the same trouble and I think my use case is legit:

I use `eventDidMount` to register a context menu. Within this context menu I have an action that is changing the `extendedProps` of the element. Now my problem is that the updated `extendedProps` are not available within `eventDidMount` and so I can not access them within my context menu or following actions.

That brings me to the question how to get this done otherwise?
