### ISSUE TITLE
Nuxt 3 Cannot find module /node_modules/@fullcalendar/vue3/dist/FullCalendar' imported from /node_modules/@fullcalendar/vue3/dist/index.js

### ISSUE THREAD

**Issue by kishanbhensadadiya** [fullcalendar/fullcalendar#7098]
### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

I have set up fresh nuxt 3 and installed the vue 3 fullcalendar v6. After importing needful things it returns the error `Cannot find module /node_modules/@fullcalendar/vue3/dist/FullCalendar' imported from /node_modules/@fullcalendar/vue3/dist/index.js`

![image](https://user-images.githubusercontent.com/41226289/208878099-a1a2d212-4c56-47eb-8225-4d54f9badb52.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

This example shows how to use it in Nuxt:

https://github.com/fullcalendar/fullcalendar-examples/tree/main/nuxt
