### ISSUE TITLE
A number of properties missing in v6 types compared to v5

### ISSUE THREAD

**Issue by hisuwh** [fullcalendar/fullcalendar#7122]
### Reduced Test Case

https://codesandbox.io/s/zealous-haze-4d8e6m?file=/src/index.tsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

With full calendar v5 I was import `CalendarOptions` from `@fullcalendar/vue`.  

With v6 I'm now importing it from `@fullcalendar/core` however it doesn't seem to have the same API.  Specifically `schedulerLicenseKey` is missing meaning I get a build error:

![image](https://user-images.githubusercontent.com/4470351/210597061-3e08a58f-d3f4-47b3-aa85-fee5b4738bae.png)

**Comment by hisuwh** [comment]
Looks like there are some other properties missing from the type:
- `eventDragStart`
- `eventDragStop`
- `resourceGroupField`
- `resourceGroupLabelContent`
- `resources`

Also:
- `DateSelectArg` is missing property `resource`
- `EventResizeDoneArg` from `@fullcalendar/interation` is missing `event` and `revert`

**Comment by acerix** [comment]
The `schedulerLicenseKey` option is only added when using a premium plugin, for example it works by including `@fullcalendar/resource-timeline`:

https://codesandbox.io/s/naughty-franklin-f896j4?file=/src/index.tsx

Similarly for the other options, eg. `eventDragStart` is added from the interaction plugin.

**Comment by hisuwh** [comment]
I'm referencing all those packages.  But the typings are missing now

**Comment by hisuwh** [comment]
My scenario is more like this:
https://codesandbox.io/s/nervous-thunder-fl84nb?file=/src/index.tsx

**Comment by hisuwh** [comment]
@acerix the license key property issue seems to be fixed but there seems to be another of types missing still:

```
ERROR in ./src/common/schedule/builders/EventApiBuilder.ts:31:20
TS2693: 'EventApi' only refers to a type, but is being used as a value here.
    29 |     public build(): EventApi {
    30 |
  > 31 |         return new EventApi(
       |                    ^^^^^^^^
    32 |             new CalendarContextBuilder().build(),
    33 |             this.event,
    34 |             {} as EventInstance
ERROR in ./src/common/schedule/builders/ResourceApiBuilder.ts:3:15
TS2614: Module '"@fullcalendar/resource"' has no exported member 'Resource'. Did you mean to use 'import Resource from "@fullcalendar/resource"' instead?
    1 | /* eslint-disable @typescript-eslint/consistent-type-assertions */
    2 | import { ResourceApi } from "@fullcalendar/resource";
  > 3 | import type { Resource } from "@fullcalendar/resource";
      |               ^^^^^^^^
    4 |
    5 | import { CalendarContextBuilder } from "./CalendarContextBuilder";
    6 |
ERROR in ./src/common/schedule/data/eventAllow.ts:19:22
TS2339: Property '_def' does not exist on type 'EventApi'.
    17 |     }
    18 |
  > 19 |     if (draggedEvent._def.resourceEditable === false
       |                      ^^^^
    20 |         && draggedEvent._def.resourceIds.some(id => id === dropInfo.resource?.id) === false
    21 |     ) {
    22 |         return "no";
ERROR in ./src/common/schedule/data/eventAllow.ts:20:25
TS2339: Property '_def' does not exist on type 'EventApi'.
    18 |
    19 |     if (draggedEvent._def.resourceEditable === false
  > 20 |         && draggedEvent._def.resourceIds.some(id => id === dropInfo.resource?.id) === false
       |                         ^^^^
    21 |     ) {
    22 |         return "no";
    23 |     }
```

**Comment by hisuwh** [comment]
Anyone going to take responsibility for this?  Typings seem to have been nerfed

**Comment by arshaw** [comment]
@hisuwh I will take responsibility for this. Not many people are reporting this type-nerfing problem, so maybe it's your specific case only. [Can you post a Stackblitz?](https://fullcalendar.io/reduced-test-cases)

**Comment by pkro** [comment]
Type EventApi is now also missing the _instance property which I used to get the start time of an instance of a recurring event. This is keeping me (again) from updating to v6, which we bought in addition to our v5 license.

`export function getInstanceForParentDate(eventInfo: EventApi) {
    // ...
    const eventStart = eventInfo._instance!.range.start;
    // ...`

Or is there now a better / easier way to do this?

**Comment by lmillucci** [comment]
I've created a very simple Stackblitz to reproduce the error:  `Object literal may only specify known properties, and 'schedulerLicenseKey' does not exist in type 'CalendarOptions'.(2345)`. Let me know if anything is missing.
 https://stackblitz.com/edit/typescript-rbq98j?file=index.ts

**Comment by danydev** [comment]
@acerix @arshaw we're having the same problem described by @lmillucci do you think we need to provide something else or is the issue clear?

**Comment by bhowell2-fleetio** [comment]
This was not a great change. 

This is what I'm having to do to get the `CalendarOptions` type...

```typescript
// dumbest hack ever... cant believe they changed to make us have to do this
type CalendarOptions = Omit<(typeof FullCalendar)['prototype']['props'], 'children'>
```

Now you can use like this:
```typescript
type FullCalendarDateClick = CalendarOptions['dateClick']
```

I don't understand why this library would hide some of the fundamental interfaces? Many of those in `internal-common.ts` could be used by external consumers.

**Comment by woahitsjc** [comment]
Any updates on this?

**Comment by crustamet** [comment]
Yes, there is a major problem loading content from fullcalendar archive instead of the fullcalendar-scheduler archive

The key actually works only if you load the fullcalendar-scheduler but this scheduler does not have all the packages from the fullcalendar archive.

What i am witnessing is this:
Resource timelines works only with this fullcalendar-scheduler exactly like it states in the documentation but the other views from the simple calendar is not supported fully, they work along if you import the packages from the **simple one** into the **scheduler** it does not work the other way around.

After testing a lot. I found that events initialized with the **simple one** prev & next do not syncronize if you take the **events**, as you need to implement **resources** like the resources is for the **scheduler** and not for the **simple one**

I would really appreciate if someone can build the full bundle packages into a "release" so we can use it properly.


The real problem is this : 
[https://fullcalendar.io/docs/initialize-globals#premium-bundle](url)
![image](https://github.com/fullcalendar/fullcalendar/assets/36475250/994e38c7-87b1-4dec-af4e-b672c66b1452)

On this link you can check for yourself the bundle and in the descriptions it states there are includes the following packages
But when i download the archive and open it there are packages missing
![image](https://github.com/fullcalendar/fullcalendar/assets/36475250/ffe5ade1-a7cb-416d-9e60-67f44c0e608e)

**I'm sure we can add those missing packages to the release for the bundle aswell.**

**Comment by Anubarak** [comment]
I have the very same issue for events, my IDE complains as soon as I am trying to add the property `resourceId` to an event, saying `resourceId` is not in type `RawOptionsFromRefiners<Required<EventRefiners>>` 
But it seems like it's not planned to fix anytime soon is it?
The only way seem to be to use Fullcalendar without Typescript.
