### ISSUE TITLE
timezone is wrong

### ISSUE THREAD

**Issue by oysterlovers** [fullcalendar/fullcalendar#7136]
### Reduced Test Case

xxx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

```ts
dayjs.tz.setDefault("Asia/Taipei");

export function tzDayjs(date?: ConfigType)
{
	return dayjs.tz(date ?? void 0, "Asia/Taipei")
}
```

```js
[{
		id: '0',
		sourceId: '0',
		title: 'event title',
		start: tzDayjs('2023-01-8').format(),
		end: tzDayjs('2023-01-11').toDate(),
		item: {},
		eventResourceEditable: true,
		durationEditable: true,
		startEditable: true,

	}]
```

![image](https://user-images.githubusercontent.com/107333049/211589864-1fbd8829-4601-4a20-bc0d-893446f080f9.png)

================

```js
[{
		id: '0',
		sourceId: '0',
		title: 'event title',
		start: tzDayjs('2023-01-8').toDate(),
		end: tzDayjs('2023-01-11').toDate(),
		item: {},
		eventResourceEditable: true,
		durationEditable: true,
		startEditable: true,

	}]
```

![image](https://user-images.githubusercontent.com/107333049/211590713-70a68936-228d-4693-b369-3812b2c56870.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

The native date objects are not expected to have the correct timezone as explained here:

https://fullcalendar.io/docs/timeZone#UTC-coercion
