### ISSUE TITLE
Error using v6.1 and eventContent function with vue3

### ISSUE THREAD

**Issue by martinfruehmorgen** [fullcalendar/fullcalendar#7175]
### Reduced Test Case

https://stackblitz.com/edit/github-lvjyb4?file=src/DemoApp.

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

Hello,
using Vue3 and the eventContent function I get in my setup the following error:
Uncaught (in promise) TypeError: customRendering.generatorMeta is not a function
    at Proxy.render (FullCalendar.ts:40:28)

In the test case I can't see that error in the console, but the event is not rendered correctly.

Thanks,
Martin

**Comment by arshaw** [comment]
queued for release https://github.com/fullcalendar/fullcalendar-workspace/commit/a9ef031dad2aa8fdb0b26f0b7310839d75d73cd4

**Comment by arshaw** [comment]
Resolved in [v6.1.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.1). This repro no longer shows an error:
https://stackblitz.com/edit/github-lvjyb4-s8c7j2?file=package.json

However, if you're using the Vue connector and use an `eventContent` function in the CalendarOptions instead of defining a slot in the template, you need to use Vue's `h` to return JSX from the function. The object you're returning is not a JSX vnode, but luckily Vue is not complaining.
