### ISSUE TITLE
Error on Custom View for React

### ISSUE THREAD

**Issue by white3km** [fullcalendar/fullcalendar#7207]
### Reduced Test Case

https://codesandbox.io/s/full-calendar-v6-custom-view-rwsq7y

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Similar to https://github.com/fullcalendar/fullcalendar/issues/7120

For version 6.1.4, when a custom view is provided an error is returned when trying to view the custom view.
/node_modules/preact/dist/preact.module.js
TypeError - Cannot add property __, object is not extensible

**Comment by jayldce** [comment]
Could someone please update on this issue? When can we expect fix for the same.

**Comment by sahilalam0** [comment]
Hi , can we know when can we expect the fix for it as i was facing the same issue ?

**Comment by arshaw** [comment]
Using `view.[custom-name].component` was never supposed to work. That is reserved for internal use. If you change it to `content` it should work. Example:
https://codesandbox.io/s/full-calendar-v6-custom-view-forked-95c8uj?file=/src/CustomViewPlugin.tsx

However, I understand many people look at the official plugins' source code for inspiration on how to write a custom view. So, in [v6.1.8](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.8) I've mapped `component` -> `content` when this scenario is detected. Example:
https://stackblitz.com/edit/github-woxsdv?file=src%2FDemoApp.jsx
(I had to convert to stackblitz because codesandbox doesn't work well for me)

Please let me know if all this is okay.

**Comment by ajuanjojjj** [comment]
Apologies if this is unrelated to the issue here, I'm just starting with react and I'm kinda lost generally speaking; 

The official docs suggest using creating a `customView` that `extends React.Component`. This does not seem to work (at least using typescript); I get all sorts of errors when doing so. 

The example @arshaw provided doesn't even seem to be using the imported `React` reference, so, are the docs outdated/wrong? Did I just mess up some of the generics (TS) on `React.Component`?
