### ISSUE TITLE
ICalendar events with 'TZID' displayed in wrong timezone

### ISSUE THREAD

**Issue by leoleoasd** [fullcalendar/fullcalendar#7456]
### Reduced Test Case

https://github.com/leoleoasd/calendar_bug_demo

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

reduced ical:
```
BEGIN:VEVENT
CREATED:20230917T160840Z
LAST-MODIFIED:20230917T171829Z
DTSTAMP:20230917T171829Z
UID:40597b6c-e9bf-4206-9a2f-97acc0b94f8f
SUMMARY:test
X-MOZ-LASTACK:20230917T162602Z
DTSTART;TZID=Asia/Omsk:20230917T100900
DTEND;TZID=America/New_York:20230917T010900
TRANSP:OPAQUE
X-MOZ-GENERATION:5
SEQUENCE:2
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
END:VALARM
END:VEVENT
```
this event is shown as it begins on 10:09 am and ends on 11:09 am NO MATTER BROWSER LOCAL TIMEZONE SETTING:
![image_2023-09-16_15-05-15](https://github.com/fullcalendar/fullcalendar/assets/37735580/94c4d243-5575-4db6-90db-4c9bbd046a83)

![image_2023-09-16_15-00-19](https://github.com/fullcalendar/fullcalendar/assets/37735580/33d52e7b-fd7d-4d1a-a982-40a6cef37cfd)

Which should be (after fix in #7450):
![image_2023-09-16_15-06-11](https://github.com/fullcalendar/fullcalendar/assets/37735580/31f93a9a-dc0f-46ce-916c-d72d33efc97e)

**Comment by acerix** [comment]
Thanks for the detailed report and the fix.  I hadn't realised the issue was with the `timeZone` setting, I believe this existing ticket is actually for the same issue:
https://github.com/fullcalendar/fullcalendar/issues/7364
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
