### ISSUE TITLE
React: dayHeaderContent – Warning "flushSync was called from inside a lifecycle method" (JSX)

### ISSUE THREAD

**Issue by malte94** [fullcalendar/fullcalendar#7520]
### Reduced Test Case

https://github.com/fullcalendar/fullcalendar/issues/7334

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Hey there,

Exactly the following issue can be reproduced on the "dayHeaderContent" (and possibly other functions when using JSX?):

https://github.com/fullcalendar/fullcalendar/issues/7334

It was likely introduced with 6.1.7

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by malte94** [comment]
Hi @acerix,

Thank you for your quick reply.

I could directly reproduce it using the following code (and functional components in React):

```
          dayHeaderContent={(args) => {
            return (
                <>
                    Test
                </>
            );
        }}
```

Here's the URL to Stackblitz:

https://stackblitz.com/edit/github-vd59ca

**Comment by acerix** [comment]
Thanks for the demo but I don't actually see the warning when running it.  I believe the issue is the same as in this existing ticket regarding React 18 though:
https://github.com/fullcalendar/fullcalendar/issues/7448
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
