### ISSUE TITLE
Events showing as all day on timeline month view independently of the configuration provided

### ISSUE THREAD

**Issue by adri95cadiz** [fullcalendar/fullcalendar#7587]
### Reduced Test Case

https://stackblitz.com/edit/github-w6hh2x?file=src%2Fapp%2Fapp.component.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

In the timeline view, if the view is week, month or longer, the event will show as full day event independently of the start and end time of the event, and the configuration provided.

In the documentation there is a differentiation between slotDuration and slotLabelInterval, but these don't seem to make any effect, it would be important to be able to configure this as some use cases like ours require events to show positioned in the exact timeframe and can span several days but start and end at very specific moments of the day.

The expected behaviour is that if configured the events can show lasting from the position that corresponds to the start and the end time of the event, instead of at the start and end of the day.

![image](https://github.com/fullcalendar/fullcalendar/assets/10522017/f0cfe88a-22ce-4a2e-a863-22f2afd4fd0a)

**Comment by acerix** [comment]
The issue is that events snap to the size of the cell, and the size of the cell is determined by `slotLabelInterval` which makes each cell a full day.  You could set `slotLabelInterval` to display hours so each slot will be 1 hour which will show the actual times of the events.

I believe this existing ticket captures the need to display the actual times of events without having labels on each slot:
https://github.com/fullcalendar/fullcalendar/issues/4937
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by adri95cadiz** [comment]
Hello @acerix ,

Even though what you commented is a workaround toward this. It is not a valid solution, as It only serves to hide labels from  some intervals, but still produces a lot of nasty side effects, like extremely long views and unwanted layouts.

If there is a differentiation between slotDuration and slotLabelInterval It should be for these kinds of reasons, one thing is how we want to display the dates, and another is how we would want to display the events, and being a timeline it makes a lot of sense to want to display the events with more nuance than snapped to the day.

In fact, in the day view this nuance exists as the events start and end is renderer in between hours even though the label duration is of one hour.

**Comment by d-corler** [comment]
Hello, could we reopen this issue ? We’re still running into this on the latest release (6.1.19).

This misleads our users into thinking a whole slot is occupied by an event, even if the event is only a fraction of the slot duration.

#### Example with a week viewport, one column per day.

> We tried with a `slotDuration` of 1 hour and a `slotLabelInterval` of a day.

##### Current behavior:

```
┌―――――――――――┬―――――――――――┬―――――――――――┬―――――――――――┐
│  monday   │  tuesday  │ wednesday │ ...       │
├―――――――――――┼―――――――――――┼―――――――――――┼―――――――――――┤
│           │           │           │           │
│╭┄┄┄┄┄┄┄┄┄┄│┄┄┄┄┄┄┄┄┄┄┄│┄┄┄┄┄┄┄┄┄┄╮│           │
│┆//////////│///////////│//////////┆│           │
│╰┄┄┄┄┄┄┄┄┄┄│┄┄┄┄┄┄┄┄┄┄┄│┄┄┄┄┄┄┄┄┄┄╯│           │
└―――――――――――┴―――――――――――┴―――――――――――┴―――――――――――┘
```

‼️ Events render at the full column width even when they last only a few minutes.

##### Expected behavior:
```
┌―――――――――――┬―――――――――――┬―――――――――――┬―――――――――――┐
│  monday   │  tuesday  │ wednesday │ ...       │
├―――――――――――┼―――――――――――┼―――――――――――┼―――――――――――┤
│           │           │           │           │
│╭┄┄┄┄┄┄┄┄┄┄│┄┄┄┄┄┄┄┄┄┄┄│┄┄╮        │           │
│┆//////////│///////////│//┆        │           │
│╰┄┄┄┄┄┄┄┄┄┄│┄┄┄┄┄┄┄┄┄┄┄│┄┄╯        │           │
└―――――――――――┴―――――――――――┴―――――――――――┴―――――――――――┘
```

✅ Events render with a proportional width of the column, regarding the `slotDuration` configuration.

---

Thanks!
