### ISSUE TITLE
Accessibility: moreLinkDidMount giving stale value even after FullCalendar re-renders

### ISSUE THREAD

**Issue by palakrathor** [fullcalendar/fullcalendar#7591]
### Reduced Test Case

https://stackblitz.com/edit/github-sockzv?file=src%2FDemoApp.jsx,package-lock.json,src%2Fdata.js,src%2Fevent-utils.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Linked issue: https://github.com/fullcalendar/fullcalendar/issues/7570

We tried by the way that you suggested (i.e _moreLinkDidMount_), but in our specific use case, we apply a filter due to which number of Events changes and the calendar re-renders, this changes the **MoreLink** text but **moreLinkDidMount** arguments (`const { num, el } = arg`) still remain the same, looks like moreLinkDidMount doesn't trigger on the calendar re-rendering and only gets triggered when calendar mounts for the first time.

As we are extracting the `num` from `args` from moreLinkDidMount and using it in aria-label, this gives us stale information after we apply the filter.

And here is the sandbox link replicating the same issue mentioned above: https://stackblitz.com/edit/github-sockzv?file=src%2FDemoApp.jsx,package-lock.json,src%2Fdata.js,src%2Fevent-utils.js

https://github.com/fullcalendar/fullcalendar/assets/139961895/60349340-b930-4f18-8c5a-77aef7e31b8a

**Comment by acerix** [comment]
`moreLinkDidMount` does not get called when the events are refreshed when the "more" element is re-used (since it is already mounted).

You should instead use `moreLinkContent` to update the content with the number of events since that is called when events are refreshed.  To also include the date, you could store the date in the element from `moreLinkDidMount` and retrieve it in `moreLinkContent`. There's a request for including the date here:

https://github.com/fullcalendar/fullcalendar/issues/6095
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
