### ISSUE TITLE
More link from eventMaxStack is displayed as a bar and also not displayed separately for each group 

### ISSUE THREAD

**Issue by Deepads** [fullcalendar/fullcalendar#7597]
### Reduced Test Case

More link from eventMaxStack is displayed as a bar and also not displayed separately for each group 

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

![1](https://github.com/fullcalendar/fullcalendar/assets/20455908/f8349162-b952-4786-b96b-154a70abe6b8)
When we have single group the bar is shown as given in the screenshot.

But if we have multiday event or event with longer duration the bar is shown for the event with the max time due to which big bar is displayed beside the event which covers almost the event UI itself.
![image](https://github.com/fullcalendar/fullcalendar/assets/20455908/197b8aee-7cc4-4394-bc6b-5a0c87586f5e)

Is it expected behavior for showing the aggregated count?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I believe it is displaying as expected, you may need `dayMinWidth` to make the calendar wider so it looks better in this case.
