### ISSUE TITLE
Mirror events unmount and remount when changing the start/end

### ISSUE THREAD

**Issue by austintackaberry** [fullcalendar/fullcalendar#7689]
### Reduced Test Case

None

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When clicking and dragging to create an event, if you use eventContent content injection, then the component unmounts and remounts every time the start or end change. Seems to be caused by a new instance id being created each time the start/end is updated.

This is ok when you are clicking and dragging on the calendar to change the mirror event start and end. However, this is problematic in the following scenario:

If you want to have an event draft popover open when you first create the event mirror, and there is a form inside the popover where you can change the event start or end in the form, and you want to have the mirror event updated when you change the start/end (similar to Google Calendar).

When you try to do this using `calendarApi.select()` API, this will then result in the event and the popover unmounting and remounting which causes a flicker and messes up the focus.

I think the code is here: https://github.com/fullcalendar/fullcalendar/blob/27d3106a081b9655471332b6612946f2869a37e4/packages/core/src/structs/date-span.ts#L160-L169

Looks like when it generates the event range, it doesn't have a persistent instance, so it has to create a new one every time. You also can't use eventApi.setStart or eventApi.setEnd because the event is set editable false.

**Comment by acerix** [comment]
If you are you looking for a way to update the start/end of the selection without recreating the DOM element of the selection, I don't believe that would work in general since selections can have multiple DOM elements, so there may be different number of them after the update. (e.g. if the selection is extended to multiple days).

If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
