### ISSUE TITLE
resize hide the event

### ISSUE THREAD

**Issue by mmartinez0308** [fullcalendar/fullcalendar#7693]
### Reduced Test Case

https://stackblitz.com/~/github.com/mmartinez0308/fullcalendarTest?file=src/app/event-utils.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

When I modify the width of the site it hides the event F1 of the second row

the event F1 dissapear:

 
![imagen](https://github.com/fullcalendar/fullcalendar/assets/91630822/56ef9eef-7e37-4269-bbb0-ff68f448848e)

**Comment by mmartinez0308** [comment]
sorry bad simple

**Comment by mmartinez0308** [comment]
i do some correction, help please

**Comment by acerix** [comment]
The event moves into the "more" popover when the width is smaller because the height is also smaller which causes the event not to fit.  You can set a fixed height so the event will also still in that case:

https://stackblitz.com/~/github.com/mmartinez0308/fullcalendarTest?file=src/app/app.component.ts
