### ISSUE TITLE
Add event element.

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#864]
Originally reported on Google Code with ID 594

```
Have event.element or something similar reference the actual element that the event
maps to.  If there is more than one element that the event references, I suppose it
could be an array of elements.

This could be useful for individually modifying the html on events.  Such as when filtering
through all the client events.

```

Reported by `me@andrewhays.net` on 2010-08-09 21:20:58

**Comment by hotmeteor** [comment]
I'm not sure if this is the correct thread, but I'm wondering if we can repurpose the existing `ui` argument in some of the methods. Currently it's empty, because of moving away from jQueryUI. Can we get the "new" element in there once an event has been resized or dropped? This would be super helpful.
