### ISSUE TITLE
Long Events that Skip Weekends in fullcalendar 1.4.7

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#890]
Originally reported on Google Code with ID 620

```
How to skip weekends when use long Events.or not dispay events on satdays and sundays?
```

Reported by `su4859@sina.com` on 2010-08-30 10:05:06

**Comment by trigbit-sukhwinder** [comment]
Events that Skip Weekends in fullcalendar in timeline view . how it can be achieved thanks

**Comment by trigbit-sukhwinder** [comment]
Question 2: How to get to know how many events are there in each resource? so that i would be able to get the total duration taken by events rendered over each resource row?

**Comment by acerix** [comment]
@trigbit-sukhwinder Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.

This ticket was closed because it's a duplicate of:
https://github.com/fullcalendar/fullcalendar/issues/338
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Here is an example counting event duration per resource:
https://codepen.io/acerix/pen/zRYjjP?editors=0011
