### ISSUE TITLE
Disable multiple events overlapping same time

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#970]
Originally reported on Google Code with ID 700

```
Dear sir,

First of all, I want to thank you for your wonderful code and that you keep it opensource.
This was just what I was looking for but I miss 1 small thing. 

Could it be possible to make sure that people can not create events that overlap?

Thank you 

Maxim

(ps: When I get it fully implemented in my project I will certainly make a donation)
```

Reported by `maximschelfhout` on 2010-11-03 23:04:01

**Comment by manojverma086** [comment]
Sir, 
How can I do check if time slot for which i am creating an event has a event already? I have attached two screen shots. I am creating an event of one hour but when there only one slot available of half an hour and I clicked on that then it creates an event which shares last half an hour of below event which I do not want. I want to check if there is only half an hour available due to another event so that I would not allow an event for  above half an hour event.

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/issues/3217
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
